### ISSUE TITLE
[UX] Remove max-width setting of .container class to take advantage of screen real estate. 

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#1038]
**Is your feature request related to a problem? Please describe.**
No how big your monitor or your browser window is, the content of the site will never take up more than 1400px due to the CSS setting of `max-width: 1400px` on the `container` css class. 

**Describe the solution you'd like**

Remove the one line of CSS that restricts our content width to 1400px. 

**Additional context**

I used the developer console to try it out: 

![image](https://user-images.githubusercontent.com/96254688/193361021-2a39ada7-a94a-4fca-b767-cd749dc4237b.png)

**Comment by OyaleSalami** [comment]
Hello, please assign me this task. Thanks

**Comment by vimalMK** [comment]
@nateynateynate @OyaleSalami  is anyone working on this or can create a PR for this issue?

**Comment by Leigh-Ola** [comment]
@nateynateynate I've made the changes @ #1119 
Please review/merge

**Comment by nateynateynate** [comment]
Hi @Leigh-Ola - I tested your solution, and it works perfect. I think there was some concern with our documentation site builders that it takes away consistency between the two sites. I think we're going to wait on this one until we coordinate with them and then re-evaluate. 

I want to thank you personally for your submission though, and when we come up with the solution we want I'll make sure to tag you. Deal? :-)
