### ISSUE TITLE
Reduce the URL signature of blogs. 

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#1052]
**Is your feature request related to a problem? Please describe.**

Our URL structure for blogs is a little elongated. Remove the date components from the URL for our blog posts to leave it as just `/blog/blogtitle`

**Describe the solution you'd like**

A one line change to Jekyll's `_config.yml` to have a new permalink value should do the trick. 

This introduces one issue - we have a community meeting post that has the same title but a different date component, so we'll have to change the title so that we're not double publishing. Only one blog post suffered this coincidence. 

**Additional context**

I believe that the elongated URLs make it hard for Google to classify our results.

**Comment by krisfreedain** [comment]
This is complete thanks to @nateynateynate! 
https://github.com/opensearch-project/project-website/pull/1229
