### ISSUE TITLE
Update Querqy Documentation for 2.3.0 release

### ISSUE THREAD

**Issue by ps48** [opensearch-project/project-website#1054]
**Is your feature request related to a problem? Please describe.**
The current documentation for Querqy Plugin on [OpenSearch website](https://opensearch.org/docs/latest/search-plugins/querqy/index/) is not up to date. 

**Describe the solution you'd like**
The installation steps for Querqy are much more simpler now with Querqy being released for 2.3.0. As seen [here](https://docs.querqy.org/querqy/index.html#opensearch).

**Additional context**
On a side note, it would be great for customers wanting to use Querqy to see some sample APIs or examples on the website.

**Comment by ariamarble** [comment]
Updated for 2.3 ~ https://github.com/opensearch-project/documentation-website/pull/1451

**Comment by krisfreedain** [comment]
thanks @ariamarble - closing this one out
