### ISSUE TITLE
[BUG] non-standard quote characters used in some documents

### ISSUE THREAD

**Issue by rursprung** [opensearch-project/project-website#1070]
**Describe the bug**
just a minor thing i noticed while working with the files on the console:

the standard quote characters should be `"` and `'` and the latter should also be used to shorten words (e.g. "don't"). some editors (namely e.g. MS Word) automatically convert these to language-specific - and often left/right specific - symbols and it seems that some of them have snuck into the files in this repository.

**To Reproduce**
see e.g. the word "don’t" here:
https://github.com/opensearch-project/project-website/blob/3e5aefa496daa16b852e65b11e8f6873c0bf2acf/_posts/2022-10-03-hacktoberfest-2022.md?plain=1#L18

or the quotes around "contribute" here:
https://github.com/opensearch-project/project-website/blob/3e5aefa496daa16b852e65b11e8f6873c0bf2acf/_posts/2022-10-03-hacktoberfest-2022.md?plain=1#L22

**Expected behavior**
IMHO this shouldn't be the case as there's no need to use non-ASCII chars (these characters are all in the extended range / UTF-8) for these things. it's probably better to just use `"`, `'` & co. (there are e.g. also different forms of `-`). the existing files could be cleaned up with a one-off search & replace, for new contributions it might make sense to put some automated check in place? otherwise just look out for this when doing the reviews?

**Comment by nateynateynate** [comment]
This is a good find, @rursprung. I can confirm your findings. We'll have to get our reviewers to keep a closer eye on that, although I have to admit I don't have any strong feelings about it. Either way, we should choose what side of the fence we're on. Ideally we should make everything non language specific.

**Comment by krisfreedain** [comment]
thanks @rursprung 
resolved with https://github.com/opensearch-project/project-website/pull/1276
