### ISSUE TITLE
Link to the Playground.

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#1073]
**Is your feature request related to a problem? Please describe.**

We want to draw people to the playgrounds to try our stuff out. 

**Describe the solution you'd like**

We should add a quick link on the upper navbar to link to the playground that says, "Live Demo!" or "Try it out!"

**Comment by krisfreedain** [comment]
You are ON IT! Thanks for opening this @nateynateynate

**Comment by AbhishekTiwari23** [comment]
I am ready to contribute. Please assign.

**Comment by vimalMK** [comment]
@nateynateynate Trying to understand the process here. Can we just create a PR for this issue or wait for an approval(get assigned) to start working on it ?

**Comment by vimalMK** [comment]
@krisfreedain  @nateynateynate does something like this works

![image](https://user-images.githubusercontent.com/35750792/197941064-0965c97e-f291-4fdf-9dce-40ea53fd8fef.png)

**Comment by vimalMK** [comment]
PR #1109

**Comment by nateynateynate** [comment]
Thanks @vimalMK ! This looks fine to me - it's all we needed. Sorry I missed out on all the mentions - I need some email rules for those.

**Comment by vimalMK** [comment]
@nateynateynate No worries!  And thank you :)

**Comment by nateynateynate** [comment]
@ahopp - I wanted to get your input on this one, as I do recall there being some kind of discourse about placement. I personally would rather have a link there at the top sooner rather than later. When more features are added to the playgrounds, it will give us a good reason to blog and tweet and get people checking back again. What do you think?

**Comment by ahopp** [comment]
> I wanted to get your input on this one

@nateynateynate Thanks for the ping! I think it's as good a place to start as any.

> it will give us a good reason to blog and tweet and get people checking back again

I think we should probably pass folks directly to the playground in most cases of outbound comms (e.g., blogs, tweets, etc.) but I think inclusion on the banner absolutely makes sense for evaluating users visiting opensearch.org properties.
