### ISSUE TITLE
[Blog for Hacktoberfest] First Bite of OpenSearch Segment Replication

### ISSUE THREAD

**Issue by rockybean** [opensearch-project/project-website#1108]
Hi Team,

Just publish a blog about `Segment Replication` and wish to be tagged with `Hacktoberfest`.

Please help to review and much appreciated~

https://medium.com/@rockybean/first-bite-of-opensearch-segment-replication-b22d0808e4c9

**Comment by krisfreedain** [comment]
@dtaivpp - can you take a look on this?

**Comment by dtaivpp** [comment]
Closed as accepted!
