### ISSUE TITLE
[FEATURE] Momentum stats carousel.

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#1115]
**Is your feature request related to a problem? Please describe.**

In September at OpenSearchCon, we shared a number of impressive metrics around the project. We need to highlight these publicly on the website. Evaluate proper placement; idea - near top of right-hand side bar- Evaluate responsibility and cadence for updating (once a month? once a quarter?)

**Describe the solution you'd like**

Some kind of slideshow / accordion / carousel, somewhere near the top of the right hand column. Above or below the Download buttons? Fade out old / fade in new at regular intervals. 

Make it look cool. I vote skulls and fire and laser beams, but that's probably outside our branding guidelines.  Presentation layer will require some debate. 

**Describe alternatives you've considered**

Adding an image and changing it regularly via PR. 

**Additional context**

The process of updating and adding new 'stats' should be considered, as well as the potential of numbering them by hand. Allow for an _include keyword to be passed that tells it to show in random order and how long to wait until the image / div flips.

**Comment by krisfreedain** [comment]
Meeting notes:
2022-1105 - @jhmcintyre has a working doc completed. Team need to evaluate. 
2022-1028 - @jhmcintyre  will get a draft of what the metrics are, what the cadence for collecting is, and a proposed timeframe for us to update/repub. Then @nateynateynate will use it to
2022-1025 - Nate Boot will build template for this (top of right side bar) -- @jcgraybill will work on compiling this and working to get appropriate approvals

**Comment by krisfreedain** [comment]
@jhmcintyre presented doc - we owe him a response by EOD 11/21 and we can move forward.

**Comment by krisfreedain** [comment]
WIP - 
thanks @nateynateynate https://github.com/opensearch-project/project-website/pull/1218

**Comment by krisfreedain** [comment]
We have a set of defined metrics to share - pulling together ownership plan to refresh & publish 
longer term - will look into ways to automate the 

AI:
- @jhmcintyre - owns schedule and reminders to update
- @nateynateynate - will take first attempt at dropping numbers into the PR template he's made and pass around before we publish.

**Comment by krisfreedain** [comment]
@jhmcintyre - we have the stats - working on a procedure on updating

**Comment by nateynateynate** [comment]
@krisfreedain - looks like this one is still assigned to me. Could someone send me the stats we want to publish and I'll throw up a PR to get them on the home page?

**Comment by krisfreedain** [comment]
@nateynateynate - yeah, once the procedure from @jhmcintyre is complete and the stats are all approved, we'll get this one out. Thanks all

**Comment by krisfreedain** [comment]
@jhmcintyre working through legal review with our ideas. Update next week

**Comment by jcgraybill** [comment]
> Meeting notes: 2022-1105 - @jhmcintyre has a working doc completed. Team need to evaluate. 2022-1028 - @jhmcintyre will get a draft of what the metrics are, what the cadence for collecting is, and a proposed timeframe for us to update/repub. Then @nateynateynate will use it to 2022-1025 - Nate Boot will build template for this (top of right side bar) -- @jcgraybill will work on compiling this and working to get appropriate approvals

LOL @krisfreedain did you assign a task to me?

**Comment by krisfreedain** [comment]
> > Meeting notes: 2022-1105 - @jhmcintyre has a working doc completed. Team need to evaluate. 2022-1028 - @jhmcintyre will get a draft of what the metrics are, what the cadence for collecting is, and a proposed timeframe for us to update/repub. Then @nateynateynate will use it to 2022-1025 - Nate Boot will build template for this (top of right side bar) -- @jcgraybill will work on compiling this and working to get appropriate approvals
> 
> LOL @krisfreedain did you assign a task to me?

HAHAHA!! type-ahead must have added you instead of @jhmcintyre -- I'll fix that. Hope you're doing well Jules.

**Comment by dblock** [comment]
Another article that used outdated stats in https://www.tecracer.com/blog/opensearch-vs-elasticsearch-2024/ that could use this!
