### ISSUE TITLE
Unexpected UI behavior with 'File Signature & Signature Verification links' when selecting options to download OpenSearch/ OpenSearch Dashboards  for Linux [ARM64 /Yum] . 

### ISSUE THREAD

**Issue by vimalMK** [opensearch-project/project-website#1128]
**Describe the bug**
Unexpected UI behavior when trying to download OpenSearch/ OpenSearch Dashboards  for Linux [ARM64 /Yum] . 

**To Reproduce**
1. Go to Downloads page
2. Select dropdown options as OpenSearch Linux [ARM64 / Yum]
3. You will see a repeated links for 'File Signature and Signature verification how to'

**Expected behavior**
No Repeating similar Links

**Screenshots**

[proof.webm](https://user-images.githubusercontent.com/35750792/199062080-1a9e70dc-1804-4fe1-9dca-9af14be9c300.webm)

![image](https://user-images.githubusercontent.com/35750792/199061047-4ce0b589-0a19-4080-9d21-b9b2b2c5c563.png)

**Host/Environment (please complete the following information):**
Browser: Chrome
Chrome Version: 107.0.5304.88 (Official Build) (64-bit)
Operating system: Windows 10

**Additional context**
I can work on the fix and will PR soon.

**Comment by vimalMK** [comment]
@krisfreedain Hello Kris.  Do you think its PR priority or not?

**Comment by krisfreedain** [comment]
@vimalMK - interesting! thanks for point it out - I hadn't noticed it. @AMoo-Miki - would you have time to confirm on this one? I believe @vimalMK would be able to help us with a fix.

**Comment by vimalMK** [comment]
> @vimalMK - interesting! thanks for point it out - I hadn't noticed it. @AMoo-Miki @nateynateynate @dtaivpp - would you have time to confirm on this one? I believe @vimalMK would be able to help us with a fix.

Sure ! No problem.  Happy to help.

**Comment by krisfreedain** [comment]
talked through this one and @dtaivpp will work with @vimalMK
