### ISSUE TITLE
SEO Experiment for previously published article. 

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#1129]
**Is your feature request related to a problem? Please describe.**

In response to our low SEO rankings for certain keywords, I'm going to take one of my old articles and sprinkle a keyword for which we currently have no SERP ranking on google. After publish the SERP keyword (`data ingestion`) will be monitored for a SERP appearance. 

**Additional context**

A sanctioned experimental change that can't be done on staging.

**Comment by nateynateynate** [comment]
@krisfreedain - please assign to me.

**Comment by krisfreedain** [comment]
[TRIAGE] @nateynateynate  - still working on this. Please update with notes/date when you can

**Comment by nateynateynate** [comment]
This one is going to have to be on hold for a bit. As it turns out we don't have the option to alter the meta keywords for any individual page. Will file a new issue.
