### ISSUE TITLE
Add a description and location to opensearch-project

### ISSUE THREAD

**Issue by dblock** [opensearch-project/project-website#113]
Add a description to opensearch-project org, compare:

<img width="383" alt="Screen Shot 2021-06-03 at 5 05 11 PM" src="https://user-images.githubusercontent.com/542335/120711867-e23ccb80-c48d-11eb-9f36-8d094fa66543.png">

<img width="401" alt="Screen Shot 2021-06-03 at 5 04 59 PM" src="https://user-images.githubusercontent.com/542335/120711872-e49f2580-c48d-11eb-95e7-111b6f1d122e.png">

I propose "A community-driven, open source fork of Elasticsearch and Kibana."

Not sure we want a location, but I think it's OK to make it Seattle.

I think an org admin can do this, maybe @hyandell?

**Comment by stockholmux** [comment]
@dblock This is a org wide change, right?

(P.S. I'd make it Palo Alto, but it's debatable!)

**Comment by dblock** [comment]
Correct. I don't know which repo to put an issue for the org, so I picked the most public one ;)

**Comment by krisfreedain** [comment]
![Screen Shot 2022-11-15 at 11 02 26 AM](https://user-images.githubusercontent.com/4873623/202003726-4849af3e-9526-4957-b35e-10d94792f593.png)
Not sure when, but this was completed.
