### ISSUE TITLE
OpenSearch 2.4.0 is available today!

### ISSUE THREAD

**Issue by jhmcintyre** [opensearch-project/project-website#1136]
**Describe the blog post your would like to write**
A clear and concise description of what subject the blog post will cover.
Blog post will announce the availability of OpenSearch 2.4.0

**What is the title of the blog post?**
Tentatively "OpenSearch 2.4.0 is available today!"

**Who are the authors?**
Who will be listed as the authors of this blog post
James McIntyre and others TBC

**What is the proposed posting date?**
Provide the date which you wish this post to go live

Nov. 10, 2022

**Comment by krisfreedain** [comment]
https://github.com/opensearch-project/project-website/pull/1159
