### ISSUE TITLE
Blog post: The thud test: Measuring OpenSearch documentation content

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/project-website#1137]
**Describe the blog post your would like to write**
The point is to describe the progress the documentation team has made in creating content for OpenSearch. I want our community to know the different areas of documentation that we've touched. The concept is around an old joke about 'the bigger the thud, the more documentation you have."  

**What is the title of the blog post?**
The thud test: Measuring OpenSearch documentation content

**Who are the authors?**
Heather Halter

**What is the proposed posting date?**
November 18 or later

**Comment by krisfreedain** [comment]
thanks @hdhalter - closing this issue out with https://github.com/opensearch-project/project-website/pull/1150 
blog published: https://opensearch.org/blog/feature/2022/11/thudtest/
