### ISSUE TITLE
Blog Post on Writing Aggregations in OpenSearch

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/project-website#1138]
**Describe the blog post your would like to write**
I would like to write a blog post on Writing Aggregations in OpenSearch. The blog post will first build a basic understanding of the Aggregations Framework in OpenSearch. Then will use an example to explain how to code an Aggregation in OpenSearch.

**What is the title of the blog post?**
Writing Aggregations in OpenSearch

**Who are the authors?**
@navneet1v 

**What is the proposed posting date?**
01/15/2023

**Comment by alicejw-aws** [comment]
Hi @navneet1v , when you are ready for me to review your draft, please let me know. Thanks

**Comment by navneet1v** [comment]
Hi @alicejw-aws I am not able to work on this blog. I have updated the date. Is that something I can do.

**Comment by alicejw-aws** [comment]
Hi @navneet1v , thanks for the update! No problem, let's also update the Asana tracker with the new date it will be available for review. Is that Jan 15?

**Comment by pajuric** [comment]
Updating timeline to 4/18/23.

**Comment by pajuric** [comment]
@navneet1v - Do you still plan to write this blog, or are we able to close this one out?

**Comment by navneet1v** [comment]
I am closing this issue for now. Will create it if the blog is needed,
