### ISSUE TITLE
Add a blog post for a partner

### ISSUE THREAD

**Issue by BobWall23** [opensearch-project/project-website#1145]
IronCore Labs, an OpenSearch partner, would like to add a blog post on their Cloaked Search proxy, which encrypts sensitive data stored in OpenSearch but still allows search on it.

**What is the title of the blog post?**
OpenSearch Partner Highlight: Using Cloaked Search to Protect Your Data

**Who are the authors?**
Patrick Walsh

**What is the proposed posting date?**
Nov 11, 2022

**Comment by pajuric** [comment]
Hi Bob - We have reviewed the draft and approved it to publish with some very minor edits. If you have a chance to make the edits today, we can get it published ASAP.

**Comment by krisfreedain** [comment]
Thanks for this @BobWall23 - closing the issue out with https://github.com/opensearch-project/project-website/pull/1146 

blog is published: https://opensearch.org/blog/partners/2022/11/OpenSearch-Partner-Highlight-Using-Cloaked-Search/
