### ISSUE TITLE
[Website update] Hero banner carousel

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/project-website#1166]
**Describe the solution you'd like**
Place at the top of the front page to allow a rotating carousel of linked images (or text), highlighting blog posts, upcoming events, news, etc.

Enable the project to draw attention to new and interesting content pieces when the community visits the site

**Comment by krisfreedain** [comment]
meeting notes:

2022-1104 - Hannah - has the examples - will work with Patti to get to templates for blog posts, release anncmnt, events/comm meetings. 
2022-1025 - @nateynateynate - will start on code. [Hannah Uselman](https://quip-amazon.com/RaY9EADH8wm) will create a few examples. (Image / Hero banner @krisfreedain used before is based on [OpenSearchCon image in this post](https://opensearch.org/blog/community/2022/05/opensearchcon/)) Kris & Nate talk with the hero banner code example

Example dimensions: 1128x191

**Comment by krisfreedain** [comment]
@jhmcintyre , Patti , Hannah - working on final decisions on content wishlist with a vendor to develop templates. Meeting set for next week.

**Comment by Uselmh** [comment]
Blog Posts
Releases
Partner page
Community

**Comment by krisfreedain** [comment]
@pajuric - we should have image templates early next week.

**Comment by krisfreedain** [comment]
@nateynateynate will also look into making the carousel start on a random image rather the 1st - therefore changing the experience each time someone visits.

**Comment by krisfreedain** [comment]
@nateynateynate  currently working on this. 
@Uselmh  - working on images 
we'll have a max 3 to 5 in rotation

**Comment by krisfreedain** [comment]
Amazing work done by @nateynateynate! 

Complete with https://github.com/opensearch-project/project-website/pull/1301
