### ISSUE TITLE
[Website update] Social sharing previews - blogs, individual pages, community members

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/project-website#1169]
### Is your feature request related to a problem? Please describe.

Every time a page on our site is shared on twitter, the preview appears with the same description and image (the OpenSearch logo). We should be able to specify more of the presentational details on an as-needed basis.

There should also be default images for blog posts that don't have a featured image based on the category front matter.

### Describe the solution you'd like

Implement some jekyll logic in the header includes such that it will check the page for any defined twittercard frontmatter. If any is defined, honor it. Otherwise, use the default.

If a post doesn't have a featured image, use a default based on the category.
The content of the twittercard should be the first paragraph of content on the blog, or perhaps use the excerpt frontmatter if it exists.

Let's provide a few arrangements of defaults that we can pick between as-needed.

### Additional context

https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/abouts-cards

**Comment by krisfreedain** [comment]
11/4 Hannah has a mock up cards for general use. - will need to build this in a comment here on GH. 
Hannah finished GitHub training. Will begin the "self serve" process of creating a account. - @nateynateynate  will pick thru this and begin coding this in the blog template.

2022-1025 - this may require a 'featured image' for every blog post. Need to research that Jekyll can handle / have option for this. Hannah will work with Daryll/Nate/Kris on this one.

10/2022 Site default card to large image and we will make that unique.
Integrated into publishing process so we can make sure we provie the image URL to the twitter card.- Manual to start. More frontmatter into the top of the blog. Blog owners choose the image they want for the blog. 

action item:

-A Github issue to fix twitter cards.
-create default twitter card.

**Comment by krisfreedain** [comment]
@nateynateynate - this is WIP - will connect w/ him next week on status

**Comment by krisfreedain** [comment]
@nateynateynate will be working on this next
@Uselmh will create a default 800 x 418 (image size ratio) - for shares/blogs that do not have their images

**Comment by astephanus** [comment]
@krisfreedain @nateynateynate According to the Twitter documentation there is special behavior regarding the description field that we need to consider. It is not displayed on iOS and Android mobile apps, and for the Web it is truncated to only 3 lines for both timeline and for the expanded Tweet. FYI: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

**Comment by kaimmej** [comment]
### Current
This is the current image for our twitter cards [opensearch-twitter-card](https://opensearch.org/assets/opensearch-twitter-card.png) 

Should we use this as our default instead? 
[blog-hero-placeholder](https://opensearch.org/assets/img/blog-hero-placeholder.png)

Top 5 categories are the following: 
I suggest we make these 5 our starting point, and all other posts default to the blog-hero-placeholder image.
- technical-posts
- community
- releases
- partners
- features


All blogs were categorized and the list can be found here [google-sheet](https://docs.google.com/spreadsheets/d/1SQZ6UjaCYv0b34fRIkRHBdN2_YRfP5jpABPnoQ6d3Pk/edit?gid=1590938144#gid=1590938144)

**Comment by kaimmej** [comment]
This is being addressed in [PR 2970](https://github.com/opensearch-project/project-website/pull/2970)

## Issues:
twittercard metadata was not being pulled correctly and rendered into the html of our blog posts. When we went to share them, we were not including all of the information that twitter was expecting. The twitter sharing images looked wierd for 2 reasons: (1) we were applying the label "summary" instead of "summary image large". Twitter displays different cards depending on what we communicate in these meta tags. and (2) we were giving a small OpenSearch logo image, instead of an image at the correct 2:1 ratio.
Additionally, sharing to other sites, such as facebook or Linkedin was broken because we were providing a different image and that image was 404'ing. [og image](https://opensearch.org/assets/img/logo-high-resolution.png)

**Comment by nateynateynate** [comment]
Solved with #2987
