### ISSUE TITLE
[Website update] Partners page enhancement(s)

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/project-website#1171]
**Is your feature request related to a problem? Please describe.**
The current partners page is limited in it's functionality, providing only a link to each partner's homepage. https://opensearch.org/partners 

**Describe the solution you'd like**
Enhancements to the partner page needed. Expand information about each partner, what their area of expertise is, type of partner, links to site/social/blog/etc. Consideration; fold Community Projects page into new layout as a majority of them are run by partners. 

Also include benefits of becoming a partner, how to, etc.

**Comment by krisfreedain** [comment]
@pajuric will be working to build out messaging / what types of data we'll need on each partner page / what layers -- will go through ideation with @jhmcintyre -- this will allow us to move to next phase on this issue

**Comment by pajuric** [comment]
Messaging and big buckets for the partner page are being defined and content drafted. First round reviews are set for the content w/o 1/23/2023 with Daryll and James. Will also create a high-level doc with page framework to help with ideation while content is being finalized.

**Comment by krisfreedain** [comment]
Moving forward in Issue 
https://github.com/opensearch-project/project-website/issues/1345
and PR 
https://github.com/opensearch-project/project-website/pull/1403
