### ISSUE TITLE
Feedback Survey Link

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#1196]
**Is your feature request related to a problem? Please describe.**

We're hoping to collect some information from our users to improve the OpenSearch Project. Let's add a paragraph and a link to the top of the 'What's New' section on the far right column. 

**Describe the solution you'd like**

Just an entry in the feed list like the rest of them with perhaps some coloring to make it stand out. A short paragraph, and a link to take the survey.

**Comment by krisfreedain** [comment]
Closed with https://github.com/opensearch-project/project-website/pull/1201 - thanks again @nateynateynate
