### ISSUE TITLE
Fluent Bit 2.0 and OpenSearch

### ISSUE THREAD

**Issue by brijos** [opensearch-project/project-website#1232]
**Describe the blog post your would like to write**
New features released in Fluent Bit 2.0 which are specific to OpenSearch

**What is the title of the blog post?**
TBD

**Who are the authors?**
brijos, anurag_gup, likely one more new author from Calyptia

**What is the proposed posting date?**
Jan 2023

**Comment by pajuric** [comment]
Completed
