### ISSUE TITLE
[Blog] What's New - Lucene-based kNN 

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#1236]
**Describe the blog post your would like to write**
OpenSearch pioneered search engine k-nearest neighbor search (k-NN) in 2019, and developers have adopted it enthusiastically on sets of millions or even billions of vectors. OpenSearch 2.2 introduced a third way of calculating approximate k-NN based on the Lucene 9.0 implementation. 

**What is the title of the blog post?**
What's New - Lucene-based kNN (2.2.0) 

**Who are the authors?**
Stavros Macrakis

**What is the proposed posting date?**
2/24/2023

**Comment by krisfreedain** [comment]
@macrakis can you add your comments on this? I think we're waiting on your input on a draft
