### ISSUE TITLE
[BUG] docker-compose.yml needs to be separated for 1.x and 2.x+

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/project-website#1245]
Hi,

We change from `master` to `cluster_manager` in 2.x+, but not in 1.x due to it is a breaking change.
As you can see in the build repo, we separate this change into two docker compose files:
https://github.com/opensearch-project/opensearch-build/tree/main/docker/release/dockercomposefiles

In project website, it is pointing to the same `cluster.initial_cluster_manager_nodes` for both 1.x and 2.x, which mean 1.x will fail due to it is still using `cluster.initial_master_nodes`.

```
opensearch-node1         | java.lang.IllegalArgumentException: unknown setting [cluster.initial_cluster_manager_nodes] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```

Thanks.

**Comment by krisfreedain** [comment]
@dtaivpp @nateynateynate - can you give this one a look?

**Comment by bbarani** [comment]
Hi @dtaivpp @nateynateynate @krisfreedain Can you provide update on this issue?

**Comment by nateynateynate** [comment]
@krisfreedain - I'm going to assign this to myself if you don't mind. A quick edit to https://opensearch.org/downloads.html to refer to two different docker-compose files. One that refers to opensearch:1 and one that refers to opensearch:2. Just a parenthetical and link on step 2 should satisfy this.

**Comment by peterzhuamazon** [comment]
Same needs to be updated on the documentation website.

**Comment by nateynateynate** [comment]
I have made zero progress on this - I'm going to unassign myself and see if someone else wants to tackle it.

**Comment by peterzhuamazon** [comment]
The documentation side changes by @kolchfa-aws :
* https://github.com/opensearch-project/documentation-website/pull/4122/

**Comment by hdhalter** [comment]
@kolchfa-aws - can we transfer this to project-website since our part is done? Thanks.

**Comment by peterzhuamazon** [comment]
Working with @AMoo-Miki on this as part of the 2.12 release changes on docker-compose files due to admin:admin changes.
