### ISSUE TITLE
[Blog] OpenSearch Project 2022 Recap and What's Next

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#1262]
**Describe the blog post your would like to write**
This blog takes a look back at what the OpenSearch Project accomplished in 2022, and provides readers with some insight into what is to come for the project in 2023. 

**What is the title of the blog post?**
 OpenSearch Project 2022 Recap and What's Next

**Who are the authors?**
@dtaivpp 

**What is the proposed posting date?**
01/19/2023

**Comment by dtaivpp** [comment]
This is on schedule so far. Working on imagery and final copy now.
