### ISSUE TITLE
[BUG] Update the schedule to reflect 2023 schedule is not proposed

### ISSUE THREAD

**Issue by elfisher** [opensearch-project/project-website#1264]
**Describe the bug**
The 2023 schedule is no longer a proposed schedule.

**To Reproduce**
1. Go to https://opensearch.org/releases.html
2. Scroll down to "Proposed 2023 schedule"
3. It is now 2023 so this is no longer a proposed schedule

**Comment by seanneumann** [comment]
@AbhishekReddy1127 Can you handle this? Ping me if you need any clarifications.

**Comment by krisfreedain** [comment]
thanks @elfisher @seanneumann - would greatly appreciate the help @AbhishekReddy1127 - please reach out if you have questions.

**Comment by krisfreedain** [comment]
for the 2022 section, I propose we move that to the bottom under a heading of 'Release History' or similar. In my experience it can be helpful to keep track of prior releases.

**Comment by BSFishy** [comment]
Is the work for this issue just to change "Proposed 2023 schedule" to "2023"?

**Comment by krisfreedain** [comment]
Proposed layout - by headers/sections

Release Schedule
(the 2023 table moves up here)

Maintenance Policy
(stays as is)

Release History
(new header, 2022 table moves under here)

Change Log
(stays as is)

**Comment by krisfreedain** [comment]
completed with PR https://github.com/opensearch-project/project-website/pull/1268 - thanks @BSFishy!
