### ISSUE TITLE
[Blog] A benchmarking study on semantic search with OpenSearch

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opensearch-project/project-website#1270]
**Describe the blog post your would like to write**
A benchmarking study based on the recently launched (experimental) neural-search plugin, with latency/throughput comparison between different traffic/host configuration and etc.

**What is the title of the blog post?**
A benchmarking study on semantic search with OpenSearch

**Who are the authors?**
Sean Zheng, Zane Niu, Navneet Verma, Junshen Wu, Charlie Yang, Yaliang Wu, Vamshi Vijay

**What is the proposed posting date?**
02/06/2023 --> 03/27/2023

**Comment by pajuric** [comment]
@sean-zheng-amazon - Just checking-in to see if you have an update on the new publish date (approx) for the blog.

**Comment by sean-zheng-amazon** [comment]
We've reviewed the first version, are currently addressing comments and wrapping up, should be ready by next week. Changing the date to 03/27

**Comment by pajuric** [comment]
@sean-zheng-amazon - Thank you for the update.

**Comment by pajuric** [comment]
@sean-zheng-amazon - Checking in to see if you need anything week on this one? Please advise.

**Comment by pajuric** [comment]
Closing this out since there is an updated blog issue for this here: https://github.com/opensearch-project/project-website/issues/2413
