### ISSUE TITLE
[Blog] Semantic Search in OpenSearch

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#1316]
**Describe the blog post your would like to write**
There are aspects of relevance that cannot be measured by keyword similarity. Humans understand relevance in a far broader sense that involves semantics, contextual awareness and world knowledge. Naturally, we would like to build systems that can do the same. This blog focuses on how to build a search engine based on deep neural networks that can understand and answer natural language queries, just like a human - almost. 

**What is the title of the blog post?**
Semantic Search in OpenSearch

**Who are the authors?**
Milind Shyani

**What is the proposed posting date?**
Feb. 9, 2023

**Comment by MilindShyani** [comment]
Blog for Semantic

**Comment by pajuric** [comment]
Completed and published.
