### ISSUE TITLE
[Blog] OpenSearch Project Newsletter- Volume 1, Issue 1

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#1318]
**Describe the blog post your would like to write**
First monthly OpenSearch Project Newsletter that latest news, community happenings, events, product launches and to hear what’s new with our partners.

**What is the title of the blog post?**
OpenSearch Project Newsletter- Volume 1, Issue 1

**Who are the authors?**
@Uselmh, @jhmcintyre @pajuric 

**What is the proposed posting date?**
2/2/23

**Comment by krisfreedain** [comment]
done
https://github.com/opensearch-project/project-website/pull/1319
