### ISSUE TITLE
[Blog] Evolving Jaeger support to benefit the OpenSearch community

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#1325]
**Describe the blog post your would like to write**
The evolution of Jaeger support and how it benefits the OpenSearch community. Blog will coincide with the the launch of OpenSearch 2.6.0 on 2/28.

**What is the title of the blog post?**
(TBD) Evolving Jaeger support to benefit the OpenSearch community

**Who are the authors?**
Nitin Chandra

**What is the proposed posting date?**
3/15/23

**Comment by jkowall** [comment]
I'm pleased to contribute to this if you'd like since I’m very involved with jaeger. Just let me know.

**Comment by dtaivpp** [comment]
@jkowall sounds good to me! Thank you and let us know if you need any assistance

**Comment by jkowall** [comment]
Was there a co author on this one? Who can I coordinate with?

**Comment by pajuric** [comment]
@jkowall - Nitin Chandra would be the coauthor. I am happy to coordinate a call and I'll reach our to you offline to schedule.

**Comment by jkowall** [comment]
Sure that's fine, he can reach me on LI, Twitter or if you have my email that works for me.

**Comment by pajuric** [comment]
Blog draft is linked here: https://github.com/opensearch-project/observability/issues/1444
