### ISSUE TITLE
[Blog] What's New Reporting CLI

### ISSUE THREAD

**Issue by brijos** [opensearch-project/project-website#1334]
**Describe the blog post your would like to write**
A blog post which talks to what Reporting CLI is, who is Reporting CLI built for, what are some examples, and where can I find out more information?

**What is the title of the blog post?**
What’s new: Reporting CLI with OpenSearch

**Who are the authors?**
@alicejw-aws

**What is the proposed posting date?**
2/16

**Comment by alicejw-aws** [comment]
Thanks @brijos ! I'll check with the SMEs and find out what we want to highlight about the Reporting CLI.
You can use the Reporting CLI if you want to:
-- automate report generation with AWS Lambda functions, or cron 
-- send reports to large groups via email lists
I'll find out more use case examples too.

**Comment by alicejw-aws** [comment]
Update: Started draft based from the new blog "What is" template. Will set time with @brijos , @rupal-bq, and @anirudha to get the real world examples to describe.

**Comment by alicejw-aws** [comment]
Update: Draft has been tech reviewed by 3 SMEs and is now approved for editiorial review. Asana request is updated.

**Comment by alicejw-aws** [comment]
PR is merged, ok to close ticket.
