### ISSUE TITLE
Display reporting cli on downloads page

### ISSUE THREAD

**Issue by rupal-bq** [opensearch-project/project-website#1336]
**Is your feature request related to a problem? Please describe.**
We are [releasing](https://github.com/opensearch-project/opensearch-build/issues/3112) [opensearch-reporting-cli ](https://github.com/opensearch-project/reporting-cli)and want to add this to downloads page so users can find the artifact easily.
After release, url for artifact will be https://artifacts.opensearch.org/reporting-cli/opensearch-reporting-cli-1.0.0.tgz

**Describe the solution you'd like**
- Option to download reporting cli from downloads page
- Add reporting cli artifact to https://opensearch.org/artifacts

**Describe alternatives you've considered**

**Additional context**

**Comment by krisfreedain** [comment]
@rupal-bq  A couple questions to assist with what is added to the page to support this
- Title
- Description
- Platform(s)
- Package(s) 

(example section for opensearch-cli) 
![Screen Shot 2023-02-07 at 5 42 06 PM](https://user-images.githubusercontent.com/4873623/217407031-638adc02-bff0-4575-8a3b-2058435d4a21.png)

@seanneumann  - would you be able to have someone assist? thank you

**Comment by zhongnansu** [comment]
@krisfreedain I'll work on updating the website

**Comment by krisfreedain** [comment]
thank you @zhongnansu!

**Comment by dtaivpp** [comment]
Actually @zhongnansu after talking with @rupal-bq and @anirudha we are going to go ahead and close this issue. We agreed that referring people to install via NPM via the docs page is the best method going forward. We will still have the artifact on artifacts hub and documentation page will mention that is a method available to install.

**Comment by rupal-bq** [comment]
Can we at least add the artifact in https://opensearch.org/artifacts?
