### ISSUE TITLE
Partner Page Meta Capture

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#1345]
The OpenSearch Project is collecting the following information from partners to develop a Partner Selector Guide as well as to create individual partner pages that enable potential customers to drill down and learn more about your business. 

- ** What is your organization's name?
- ** Brief description of your business and what it does **(50 words or less)**.
- Name of your relevant product(s) or service for this audience **(50 words or less)**.
- Logo (if it needs to be updated).
- ** Type of business (e.g., MSP, CSP, ISV, product/technology, professional services organization, other). 
- ** Home/main office location or address. 
-  ** What regions do you serve (e.g., NAM, EMEA, APAC, LATAM, Worldwide)?
- How can people contact you (email and phone).
- ** What OpenSearch technologies do you specialize in (e.g., search, analytics, observability, security, or other)? Keep the list brief. 
- ** What industries do you specialize in (e.g. business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology)? If all, state All.  
- Attach an additional 1-2 images you’d like to provide that showcase your business (product, technology, offices, and etc). 
- Add links to your last 3 blogs or pieces of content that are relevant for the OpenSearch Project audience. 

If you have questions or would like more information, please reach out to @pajuric

**Comment by krisfreedain** [comment]
Thanks @pajuric - we'll translate these into meta fields for the new partner pages - and will need to determine which fields we enable drill-down on within a menu system.

**Comment by krisfreedain** [comment]
Meta fields in our current partner pages:

Example:
---
name: Calyptia
logo: '/assets/media/partners/calyptia.png'
link: 'https://calyptia.com'
---

Net-new fields we will need:
---
description: 50 words or less
business-type: 
region:
contact (? expand on link field? We'll need to talk though this)
opensearch-tech: 
industries: 


Once the fields in the template have expanded, we need to work on page layout. 

Outcome of this new page should be a partner-specific URL. In this example we would have a url of:
opensearch.org/partners/calyptia 


@pajuric - please add any additional notes

**Comment by pajuric** [comment]
@krisfreedain - I edited the original issue to include two additional questions. In regards to your last comment, the only addition to the meta capture would be "main office location" so we can put a pin in where their physical HQ is located. 

Are we able to provide a drop down with predefined selections for: business_type, region, opensearch-tech, and industries?

**Comment by pajuric** [comment]
[Partner Wireframe v2.pdf](https://github.com/opensearch-project/project-website/files/10808696/Partner.Wireframe.v2.pdf)

**Comment by kolchfa-aws** [comment]
Max content width of the main panel for the doc site is 1080px

**Comment by pajuric** [comment]
Adding update wireframe based upon feedback. 
[Partner Wireframe v3_02_22_23.pdf](https://github.com/opensearch-project/project-website/files/10808884/Partner.Wireframe.v3_02_22_23.pdf)

**Comment by krisfreedain** [comment]
Per yesterday's meeting, I’ve created a [new Issue template](https://github.com/opensearch-project/project-website/issues/new/choose) on our project website repo called ‘[Partner page information](https://github.com/opensearch-project/project-website/issues/new?assignees=&labels=enhancement%2C+untriaged&template=partner_information.md&title=)’

@pajuric , as we discussed earlier, go ahead and have your first partner test it out:
-	I recommend they start here: https://github.com/opensearch-project/project-website/issues/new/choose 
-	Partner page information
-	Fill out all the fields
This will allow the whole experience to be tested. 

Once we confirm it works, go ahead and start sending this out to all partners to collect the info while Aaron builds out our new pages!

**Comment by astephanus** [comment]
PLease asign this to me.

**Comment by pajuric** [comment]
@astephanus - I will provide a spreadsheet with the resources data for each of the partners once the content is provided.

**Comment by astephanus** [comment]
> @astephanus - I will provide a spreadsheet with the resources data for each of the partners once the content is provided.

Awesome.

**Comment by astephanus** [comment]
@pajuric The information for "Name of your relevant product(s) or service for the OpenSearch audience" is not included in the wireframe, and I have just noticed that I haven't statisfied any of that in my current implementation. I simply overlooked its inclusion in this issue. I see that the information is included in https://github.com/opensearch-project/project-website/issues/1392. How do we want to inclulde this information on the partner page? It would be easy to add it to the left panel as a sub list, but it somehow feels more important, and I wonder if it's something we might want to feature more prominently perhaps beneath the Description?

**Comment by astephanus** [comment]
@pajuric I have another question. How do we want to deal with Resource links to content that do not have any sort of a hero image or similar from which to extrapolate a thumbnail for the Resource (blog/news/event/etc). For example in #1392 Only this item https://opensearch.org/blog/fluentbit20-and-opensearch/ has any sort of an image to extrapolate. Do we want the Partner to drive the recommendation? Do we want to look at the Twitter Card, or Open Graph meta data in the header? Those might not actually be unique though. Thoughts?

**Comment by krisfreedain** [comment]
WIP via https://github.com/opensearch-project/project-website/pull/1403

**Comment by krisfreedain** [comment]
@pajuric did we get to normalize the incoming data on the new partner pages yet?

**Comment by kaimmej** [comment]
### What is the current state? 
I am unclear of where this issue currently is - Do we need to add more to the new partner issue? 

---

The changes being asked on this issue#1345 were merged into main on Jun 14, 2023 with commit [f4918ea](https://github.com/opensearch-project/project-website/pull/1689)

However on that pull request [PR-1403](https://github.com/opensearch-project/project-website/pull/1403), AStefonis mentions that this was only a partial implementation? 

> https://github.com/opensearch-project/project-website/issues/1345 - partial resolution as there is still the need to add new data for partners.

What still needs to be done here? Looking at the [new-partner-page-information](https://github.com/opensearch-project/project-website/issues/new/choose), it seems like all of the requested information is present. Am I missing something?

**Comment by nateynateynate** [comment]
Completed by #3082
