### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/project-website#1354]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by pajuric** [comment]
@dblock @wbeckler - checking status here.

**Comment by wbeckler** [comment]
The next moves are:
-  a maintainer in the project-website repo adds a CODEOWNERS file with the list of maintainers that is in the MAINTAINERS.md. 
- Adjust the permissions so that those with maintainer access to this repo matches the list

**Comment by krisfreedain** [comment]
@dblock @wbeckler - I will work on this

**Comment by krisfreedain** [comment]
https://github.com/opensearch-project/project-website/blob/main/MAINTAINERS.md looks good.

**Comment by dblock** [comment]
![Screenshot 2023-04-13 at 11 03 53 AM](https://user-images.githubusercontent.com/542335/231802284-2aa2e597-b31d-4cd1-b654-954792c3079c.png)

Repo permissions are incorrect. Please work with @bbarani's team to adjust.

- only admin team should be admin
- individuals from maintainers should each have maintain level access

**Comment by bbarani** [comment]
Fixed the permissions. Need to move the CODEOWNERS file to .github/CODEOWNERS.

**Comment by dblock** [comment]
Verified, thx.

<img width="786" alt="Screenshot 2023-05-10 at 5 41 52 PM" src="https://github.com/opensearch-project/project-website/assets/542335/ec2ab637-3aa8-44f0-8945-b3c0ad4eb582">
