### ISSUE TITLE
Introducing OpenSearch 2.6

### ISSUE THREAD

**Issue by jhmcintyre** [opensearch-project/project-website#1369]
**Describe the blog post your would like to write**
Introductory blog post providing an overview of OpenSearch 2.6.0

**What is the title of the blog post?**
Introducing OpenSearch 2.6

**Who are the authors?**
Who will be listed as the authors of this blog post
James McIntyre

**What is the proposed posting date?**
Provide the date which you wish this post to go live
February 28

**Comment by krisfreedain** [comment]
https://github.com/opensearch-project/project-website/pull/1386
