### ISSUE TITLE
[Blog] Partner Highlight: Using OpenSearch to set up a hybrid system that uses text and vector search

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#1377]
**Describe the blog post your would like to write**
Summary of a blog written by Noam Schwartz of Searchium.ai titled,“Text search vs. Vector search: Better together?"

**What is the title of the blog post?**
Partner Highlight: Using OpenSearch to set up a hybrid system that uses text and vector search

**Who are the authors?**
Patti Juric (summary) of Noam Schwartz's blog

**What is the proposed posting date?**
2/24/2023

**Comment by pajuric** [comment]
@krisfreedain  - we're good to publish. Meta is incoming.

**Comment by krisfreedain** [comment]
https://opensearch.org/blog/OpenSearch-Partner-Highlight-Searchium-text-vs-vector/

Done!
