### ISSUE TITLE
Calyptia

### ISSUE THREAD

**Issue by erikbledsoe** [opensearch-project/project-website#1392]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Calyptia

**Brief description of your business and what it does (50 words or less)**
As the creators and maintainers of the open source Fluent Bit project, Calyptia is dedicated to providing vendor-neutral products and services that enhance observability practices. 

**Name of your relevant product(s) or service for the OpenSearch audience**

- Fluent Bit — A CNCF-Graduated project with billions of downloads, Fluent Bit is a vendor-neutral telemetry agent for logs, metrics, and traces. It supports OpenTelemetry and Prometheus Metrics. 
- Calyptia Core  — Our enterprise product, Calyptia Core provides a click-and-drag approach to telemetry pipeline management and configuration with powerful in-stream processing, enabling organizations to reduce their observability costs by sending non-essential data to lower-cost backends. 
- Calyptia for Fluent Bit   — A Long Term Support (LTS) edition of Fluent Bit.

**What OpenSearch technologies do you specialize in**
Observability pipelines

**Type of business**
ISV

**Home/main office location or address**
2261 Market Street #4121
San Francisco, CA 94114

**How can people contact you (email and phone)**
hello@calyptia.com

**Regions you serve**
Worldwide 

**Industry specialization**
energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology

**Logo**
![Calyptia_Bird (1)](https://user-images.githubusercontent.com/19668696/222195139-d4ee40fd-166e-4d4e-ab14-77684548b444.png)

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
Add links to your last three blogs that are relevant for the OpenSearch Project audience.
[Calyptia and OpenSearch Partner to Build First-Party Connectors to Fluent Bit and Fluentd](https://calyptia.com/2022/01/20/calyptia-and-opensearch-partner-to-build-first-party-connectors-to-fluent-bit-and-fluentd/)
[Fluent Bit 2.0 and OpenSearch](https://opensearch.org/blog/fluentbit20-and-opensearch/)
[Getting started with Fluent Bit and OpenSearch](https://opensearch.org/blog/getting-started-with-fluent-bit-and-opensearch/)

**Comment by astephanus** [comment]
Please add me @pajuric
