### ISSUE TITLE
Keylime Interactive Usability Studies

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#1401]
**Describe the blog post your would like to write**
We recently hired Keylime Interactive to help us create a baseline usability study for our Admin and Dashboard users. In this blog post, I would like to write about the initiative, provide some background on Keylime, what a usability study is, and how this can benefit community members. Additionally, I would like to request community members to participate in this study.

**What is the title of the blog post?**
Keylime Interactive Usability Studies

**Who are the authors?**
Who will be listed as the authors of this blog post
Dr. Aparna Sundar

**What is the proposed posting date?**
Provide the date which you wish this post to go live
March 10th as we need to finalize recruitment for the Admin usability study by the 19th

**Comment by pajuric** [comment]
Published to the forum here: https://forum.opensearch.org/t/looking-for-opensearch-usability-study-candidates/13045
