### ISSUE TITLE
The OpenSearch Extensibility Technical Roadmap

### ISSUE THREAD

**Issue by dblock** [opensearch-project/project-website#1408]
**Describe the blog post your would like to write**

A core reason one may choose the OpenSearch Project (OpenSearch, OpenSearch Dashboards and DataPrepper) is for the wide range of use cases they can address with its features (e.g., search, log analytics, Geospatial, and document store). We aim to make OpenSearch Project the preferred platform for developers by creating a vibrant and deeply integrated ecosystem of projects, features, content packs, integrations, and tools that can be quickly found, installed securely, combined to solve problems, and monetized by many participants.

The existing mechanism to extend OpenSearch and OpenSearch Dashboards is a plugin framework. We've started a journey of evolving plugins into a new concept called extensions. In this blog post I will provide an update on our progress and outline a long term vision for extensibility, link to ongoing work, and offer some longer term ideas.

**What is the title of the blog post?**

The OpenSearch Extensibility Technical Roadmap

**Who are the authors?**
@dblock

**What is the proposed posting date?**
2023-03-15

**Comment by pajuric** [comment]
@dblock - checking on the status of this blog and seeing if you have an update on when you will have a draft for review or to publish?

**Comment by dblock** [comment]
https://github.com/opensearch-project/project-website/pull/1455

**Comment by dblock** [comment]
Published on https://opensearch.org/blog/technical-roadmap-opensearch-extensibility/
