### ISSUE TITLE
[Blog] ML Commons Admin UI

### ISSUE THREAD

**Issue by wanglam** [opensearch-project/project-website#1409]
**Describe the blog post your would like to write**
The ML-Commons admin UI is an intuitive and powerful interface for monitoring the responsing status of your machine learning models across various ML nodes. We are going to write this blog to discuss features and technical challenges.

**What is the title of the blog post?**
ML Commons Admin UI

**Who are the authors?**
wonglam, yych

**What is the proposed posting date?**
23th, March

**Comment by Naarcha-AWS** [comment]
@wanglam: Because we haven't seen a first draft yet, and we're adding additional and impactful functionality in 2.7, are you comfortable pushing the date of publication till closer to 2.7? 

Additionally, as the writer assigned to help, is there anything I can do to help craft that first draft?

**Comment by wanglam** [comment]
Hi @Naarcha-AWS sorry for late submit the first draft version. I've write one draft version, this content is still under team reviewing. We will submit to you the first draft version in few days. We can appropriately postpone the publishing time of the blog, and we want to publish it ASAP.

**Comment by pajuric** [comment]
@wanglam  - Checking in on the draft and publish date for this blog since it was scheduled to go today. Can you please provided a status update here or via Asana.

**Comment by wanglam** [comment]
@pajuric Sure. We've send the draft version and  author information to @Naarcha-AWS. We can postpone the posting date a little bit.

**Comment by pajuric** [comment]
@wanglam - Confirming the new target date to have this live is 3/30?
