### ISSUE TITLE
[Barefoot Coders] Partner Information

### ISSUE THREAD

**Issue by Jberlinsky** [opensearch-project/project-website#1411]
**Organization name**
Barefoot Coders

**Brief description of your business and what it does (50 words or less)**
Barefoot Coders is a boutique software and technical infrastructure development studio, helping organizations scale through cloud-native solutions.

**Name of your relevant product(s) or service for the OpenSearch audience**
Our comprehensive cloud architecture, engineering, and support practice offers organizations of all sizes a one-stop shop for establishing a foundation for, migrating to, managing, and optimizing within public cloud environments. Organizations that require comprehensive search, logging, analytics and observability will benefit from our domain expertise with OpenSearch in AWS.

**What OpenSearch technologies do you specialize in**
Search & Log Management

**Type of business**
Professional Services Organization

**Home/main office location or address**
New York City: 240 Kent Ave. Ste B19, Brooklyn, NY 11249
Portland, OR: 830 NE Holladay St, Portland OR 97232

**How can people contact you (email and phone)**
Email: hello@barefootcoders.com
Phone: +1 855 833 2777

**Regions you serve**
North America

**Industry specialization**
N/A - Industry & vertical agnostic

**Logo**
![Barefoot Coders - Blue@2x](https://user-images.githubusercontent.com/16839/223818545-7693bdc0-a045-488b-a53c-6afad1030ac0.png)

**Additional image**
We're working on this -- is there a timeline that we need this by?

**Links**
https://www.barefootcoders.com/ -- we're working to build our blog presence later this year.

**Comment by pajuric** [comment]
@Jberlinsky - Thank you for submitting the info.
