### ISSUE TITLE
Pureinsights Partner Information

### ISSUE THREAD

**Issue by GGillenPITC** [opensearch-project/project-website#1412]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Pureinsights Technology Corporation

**Brief description of your business and what it does (50 words or less)**
Pureinsights has deep expertise building search applications with conventional search engines. The company helps customers go "Beyond Search", using Knowledge Graphs, Machine Learning, and Natural Language Processing to build enterprise search applications that better understand user intent and deliver answers users want. "Just make it work like Google."

**Name of your relevant product(s) or service for the OpenSearch audience**
Consulting services, managed services, and the Pureinsights Discovery Platform which embeds OpenSearch as the search engine.

**What OpenSearch technologies do you specialize in**
Search and Analytics

**Type of business**
Systems Integrator and Technology Services Provider

**Home/main office location or address**
205 Van Buren St, Suite 120, Herndon VA 20170

**How can people contact you (email and phone)**
info@pureinsights.com

**Regions you serve**
North, Central and South America, Europe.

**Industry specialization**
consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, software and technology.

**Logo**
Please upload a company logo

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
https://pureinsights.com/blog/2023/search-relevancy-scoring-dashboard-demo/
https://pureinsights.com/blog/2023/pdp-demo-implementing-google-like-search-for-the-eu-publications-office-2/
https://pureinsights.com/blog/2023/7-tech-trends-in-ai-and-search-for-2023/

![PureInsights-Logo](https://user-images.githubusercontent.com/99985338/223844539-f534cdcc-d22e-48de-a83d-8cbcfcba68bb.png)
![PureInsights-Logo](https://user-images.githubusercontent.com/99985338/223844570-58e9c939-f222-4845-ad5e-20ca073fcc5e.svg)
![KO 2023](https://user-images.githubusercontent.com/99985338/223845117-0ca25e6c-e945-4c89-902e-62ee0c583d4a.jpg)

**Comment by pajuric** [comment]
@GGillenPITC - Thank you, Graham, for submitting the info.

**Comment by astephanus** [comment]
@pajuric Would you like to assign this to me so I can add the data?
