### ISSUE TITLE
[initMAX s.r.o.] partner information

### ISSUE THREAD

**Issue by hermanekt** [opensearch-project/project-website#1413]
**Organization name**
initMAX s.r.o.

**Brief description of your business and what it does (50 words or less)**
Company initMAX is your partner for advanced IT monitoring

**Name of your relevant product(s) or service for the OpenSearch audience**
Zabbix, automation, identity, Wazuh & log management, PostgreSQL, DevOps infrastructure form the secure and stable foundation of the most successful companies.

**What OpenSearch technologies do you specialize in**
Log Management & Wazuh & Searching

**Type of business**
Professional Services Organization and Software developers

**Home/main office location or address**
Czech Republic
Plynární 1617/10
Praha 170 00

**How can people contact you (email and phone)**
Email: [info@initmax.com](mailto:info@initmax.com)
Phone: +420 800 244 442

**Regions you serve**
Worldwide

**Industry specialization**
Retail and Automotive

**Logo**
![initMAX_DIGITAL_horizontal_natmavepozadi](https://user-images.githubusercontent.com/10741768/223849408-c7b2c5d2-4e10-4589-9ede-385fd559fa7d.svg)
![initMAX_DIGITAL_horizontal_nasvetlepozadi](https://user-images.githubusercontent.com/10741768/223849315-880a55cb-27c3-4e1b-b641-f8a478d181df.svg)
![initMAX_DIGITAL_vertical_nasvetlepozadi](https://user-images.githubusercontent.com/10741768/223849767-7b2043b4-fe7a-43b2-83cc-321fbee6e3d5.svg)
![initMAX_DIGITAL_vertical_natmavepozadi](https://user-images.githubusercontent.com/10741768/223849603-66113e64-a3c3-4851-8e98-765d42597be2.svg)

**Additional image**
<img width="960" alt="initMAX-services" src="https://user-images.githubusercontent.com/10741768/223850657-7973af67-df9e-47fd-9cb8-83d370e5d18d.png">

**Links**
https://www.initmax.cz/blog/ -- we're already working to build our blog a wiki presetation in EN soon. Now we have only Czech version and some small articles in EN wiki is almost ready in cz language.

If you need any additional information, please let me know via this ticket.

Tom

**Comment by pajuric** [comment]
@hermanekt  - Thank you for providing the detailed information.

**Comment by astephanus** [comment]
@pajuric Would you like to assign this to me so I can add the data?
