### ISSUE TITLE
[Cloud Scale] partner information

### ISSUE THREAD

**Issue by nandita-cloudscaleinc** [opensearch-project/project-website#1414]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
CLOUD SCALE INNOVATION PRIVATE LIMITED

**Brief description of your business and what it does (50 words or less)**
Cloud Scale® is on a mission to simplify the development, deployment, and scaling of complex applications and to bring the full power of multi-cloud to developers and enterprises, everywhere.

**Name of your relevant product(s) or service for the OpenSearch audience**
Consulting and managed services, Cloud Scale Service Mesh Platform which leverages OpenSearch as the end-to-end observability tool.

**What OpenSearch technologies do you specialize in**
search, analytics, observability, security

**Type of business**
MSP, Technology Solutions and Services Provider

**Home/main office location or address**
Chandigarh, India 

**How can people contact you (email and phone)**
contact@cloudscaleinc.com

**Regions you serve**
North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia
Worldwide

**Industry specialization**
business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, retail, software and technology

**Logo**
![Cloud-Scale Logo](https://user-images.githubusercontent.com/105474264/223995242-b5e515b5-b58f-4a95-8320-b85975e3c365.png)

**Additional image**
<a href="https://cloudscaleinc.com/digital-transformation/">
<img width="1117" alt="cloudscale-digital transformation" src="https://user-images.githubusercontent.com/105474264/223996598-e267971c-0ccb-4b23-b2d0-824060db458f.png">
</a>

**Links**
https://cloudscaleinc.com/topics/cloud-computing/simplified-multi-cloud-by-cloudscale-experts/
https://cloudscaleinc.com/topics/tech-articles/cloud-native-security-and-compliance/

**Comment by pajuric** [comment]
@nandita-cloudscaleinc  - Thank you for the information.

**Comment by astephanus** [comment]
@pajuric Would you like to assign this to me so I can add the data?
