### ISSUE TITLE
DigitalPebble partner information

### ISSUE THREAD

**Issue by jnioche** [opensearch-project/project-website#1415]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
DigitalPebble Ltd

**Brief description of your business and what it does (50 words or less)**

DigitalPebble's unique expertise covers all aspects of a document’s life cycle, from web-wide crawling and collection, content analysis, filtering and categorization to indexing. 
DigitalPebble can help your organisation by advising on best practice and identifying suitable resources, designing scalable solutions as well as implementing them.

**Name of your relevant product(s) or service for the OpenSearch audience**
We are the authors of StormCrawler, a popular open-source web crawler which can  use OpenSearch as a back-end. We also provide consulting services on search related technologies, including OpenSearch. 

**What OpenSearch technologies do you specialize in**
Is there an area of the project where your business specializes?
We specialise in search, analytics and observability.

**Type of business**
(e.g., MSP, CSP, ISV, product/technology, services organization, other). If other, please define.
This will inform the community how they can expect to use your product(s) and services.

Consultancy

**Home/main office location or address**
Bristol, UK

**How can people contact you (email and phone)**
email : contact@digitalpebble.com

**Regions you serve**
(e.g.,North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia)
What regions of the world do you serve?

Worldwide

**Industry specialization**
(e.g. business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology)? Add all that apply.

Our clients operate in various industries,

**Logo**
Please upload a company logo

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
[StormCrawler](http://stormcrawler.net)
[URLFrontier](http://urlfrontier.net)
[OpenSearch community meetup](https://forum.opensearch.org/t/opensearch-community-meeting-2023-0214/11894)

**Comment by jnioche** [comment]
![image](https://user-images.githubusercontent.com/218319/224110259-6c9587df-6aae-45aa-940e-c01d90503a0c.png)
![image](https://user-images.githubusercontent.com/218319/224110291-7351d47f-49be-4ba7-85a8-32ebabc668f1.png)

**Comment by pajuric** [comment]
@jnioche - Thank you for submitting the requested info.

**Comment by astephanus** [comment]
@pajuric Would you like to assign this to me so I can add the data?
