### ISSUE TITLE
Oracle partner information

### ISSUE THREAD

**Issue by gherbon** [opensearch-project/project-website#1422]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Oracle Corporation

**Brief description of your business and what it does (50 words or less)**
Our mission is to help people see data in new ways, discover insights, unlock endless possibilities.

**Name of your relevant product(s) or service for the OpenSearch audience**
A clear and concise description of your product(s) and/or services offered to the OpenSearch community.
Oracle Cloud Infrastructure (OCI) Search with OpenSearch is a managed open source service that makes it easy for you to ingest, search, visualize, and analyze your data.

**What OpenSearch technologies do you specialize in**
Is there an area of the project where your business specializes?
N/A

**Type of business**
Oracle’s public cloud is delivered by networks of globally distributed cloud regions that provide secure, high-performance, local environments, organized into separate, secure cloud realms. Organizations can move, build, and run all workloads and cloud applications on Oracle Cloud Infrastructure (OCI) while complying with regional data regulations.

**Home/main office location or address**
2300 Oracle Way, Austin, TX 78741

**How can people contact you (email and phone)**
grant.herbon@oracle.com

**Regions you serve**
(e.g.,North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia)
What regions of the world do you serve?
Worldwide
https://www.oracle.com/cloud/public-cloud-regions/

**Industry specialization**
All - business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology.

**Logo**
Please upload a company logo
![oraclelogo](https://user-images.githubusercontent.com/1143293/224391662-2723845f-825a-4ac4-96ab-89a84457bb78.png)

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)
![rc10-oci-opensearch](https://user-images.githubusercontent.com/1143293/224391185-25a89b2e-2acd-4893-b8d2-404519de4f58.png)

**Links**
Add links to your last three blogs that are relevant for the OpenSearch Project audience.
https://blogs.oracle.com/cloud-infrastructure/post/opensearch-23-upgrade-today
https://blogs.oracle.com/cloud-infrastructure/post/announcing-availability-of-oci-search-service-with-opensearch

**Comment by pajuric** [comment]
@gherbon - Thank you for your submission, Grant!

**Comment by astephanus** [comment]
@pajuric Would you like to assign this to me so I can add the data?
