### ISSUE TITLE
Opster partner information

### ISSUE THREAD

**Issue by segalziv** [opensearch-project/project-website#1425]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**

Opster

**Brief description of your business and what it does (50 words or less)**

Opster provides optimization and management tools that streamline the daily operations of OpenSearch. Opster's products and services optimize search performance while reducing costs, saving users both time and money. Opster also offers 24/7 proactive support from industry experts who take charge of your entire search operation.

**Name of your relevant product(s) or service for the OpenSearch audience**

**Opster AutoOps** - covers all aspects of OpenSearch management, offering constant cluster maintenance and proactive prevention of issues. Enterprise packages also include 24/7 proactive support by industry experts.

AutoOps diagnoses issues in OpenSearch based on hundreds of metrics in real-time. AutoOps optimizes search and indexing performance, ensures high availability, guarantees continuous peak performance, and significantly reduces operational and hardware costs. 

AutoOps can be connected to self-hosted clusters as well as to managed services like Amazon OpensSearch Service.

AutoOps provides a wide range of advanced optimization capabilities, including:
- Data & shard structure optimization
- Template & index mapping optimization
- Continuous & real-time root cause analysis
- Automated prevention & resolution of issues
- Misconfiguration detection
- Cost monitoring & improved resource utilization
- Automated capacity planning
- Automated performance optimization

**Opster Search Gateway** - provides deep visibility into searches and improves search performance. The Search Gateway is an on-premise, lightweight, and low latency proxy server that analyzes search queries run against an OpenSearch cluster. The Search Gateway provides deep visibility and drill-down ability for searches that negatively impact the performance of the cluster. The Search Gateway enables prevention of damaging search queries, proactively and automatically protecting the cluster performance based on your requirements. 

**Opster Management Console (OMC)** - free - makes it easy to orchestrate, manage and monitor OpenSearch on any Kubernetes environment. The OMC enables users to deploy multiple clusters, configure node roles, scale cluster resources & more from a single interface – for free. Whether you’re managing your own Kubernetes cluster or going the hosted route, you can deploy the Opster Management Console and benefit from its abilities on all cloud environments.

**OpenSearch Kubernetes Operator** - OSS - simplifies spinning up and scaling OpenSearch clusters, optimizing configuration, upgrading versions, security and more. The OpenSearch Kubernetes Operator is licensed Apache V2. Whether you’re managing your own K8s cluster or going the hosted route, you can deploy the OpenSearch Operator and benefit from its abilities on all cloud environments.

**What OpenSearch technologies do you specialize in**

Opster’s products and services cover all OpenSearch technologies with an emphasis on search and indexing performance, resource utilization, and observability.

**Type of business**

ISV, Product/technology, and services organization

**Home/main office location or address**

HQ in Ramat Gan, Israel, with offices all around the world.

**How can people contact you (email and phone)**

Opster can be contacted at:
info@opster.com
https://opster.com/form/contact/ 

**Regions you serve**

Opster’s products and services are available globally, covering all regions: North America, South America, Europe, Middle East, Africa, Asia Pacific, and Australia.

**Industry specialization**

Software and technology, business services, consumer services, Cyber, and e-commerce. 

**Logo**

Opster logo can get downloaded here:
https://opster.com/wp-content/uploads/2023/03/Logo-Vertical-high-quality@2x.png

**Additional image**
Image of AutoOps is downloadable here:
https://opster.com/wp-content/uploads/2022/11/AutoOps-open-dashboard-modified-_1_-1.webp

**Links**
Some of Opster's blogs which are relevant for the OpenSearch Project audience:

https://opster.com/guides/opensearch/opensearch-basics/migrate-from-elasticsearch-to-opensearch/ 
https://opster.com/guides/opensearch/opensearch-basics/install-opensearch-kubernetes-helm-charts/ 
https://opster.com/guides/opensearch/opensearch-capacity-planning/how-to-reduce-opensearch-costs/ 
https://opster.com/guides/opensearch/opensearch-data-architecture/elasticsearch-ilm-vs-opensearch-ism-policy/

**Comment by pajuric** [comment]
@segalziv - Thank you for the additional info!
