### ISSUE TITLE
Sease partner information

### ISSUE THREAD

**Issue by alessandrobenedetti** [opensearch-project/project-website#1426]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Sease Ltd.

**Brief description of your business and what it does (50 words or less)**
Sease mission is to make research in Information Retrieval more accessible to an industry audience, transforming the best research ideas into real-world products.
Our focus is to provide R&D projects guidance and implementation, consulting services and training, using open source software such as Apache Lucene/Solr, Elasticsearch, OpenSearch, and Vespa.

**Name of your relevant product(s) or service for the OpenSearch audience**
We offer training, consulting, design and development of search solutions using OpenSearch.
We have dedicated pieces of training to explore and learn how to improve the relevance of your search results and integrate neural search techniques using OpenSearch.
We are Apache Lucene committers and have a solid understanding of OpenSearch internals.

**What OpenSearch technologies do you specialize in**
We focus on the search capabilities of OpenSearch with a particular attention to the machine learning integrations and neural search (vector-based search).

**Type of business**
Sease is a services organization.
We also offer a set of products to enhance your search (such as search quality evaluation tools).

**Home/main office location or address**
International House, 776-778 Barking Road
BARKING
London
E13 9PJ

**How can people contact you (email and phone)**
info@sease.io

**Regions you serve**
We are based in Europe but we generally serve North America, South America, Europe, Middle East, Africa, Asia Pacific and Australia.

**Industry specialization**
software and technology

**Logo**
![SEASE-PHRASE-gradient-24-21](https://user-images.githubusercontent.com/513195/224740242-79421132-071c-43be-b1f1-23eecddd4492.png)

**Additional image**
![SEASE-FAVICON-gradient-24](https://user-images.githubusercontent.com/513195/224740376-3932e18d-c5e6-472b-89e9-4824c39a5c5f.png)

**Links**
https://sease.io/2022/12/opensearch-neural-search-plugin-tutorial.html

**Comment by pajuric** [comment]
@alessandrobenedetti - Thank you for the additional information.
