### ISSUE TITLE
Hidora 

### ISSUE THREAD

**Issue by matthieu-robin** [opensearch-project/project-website#1427]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Hidora

**Brief description of your business and what it does (50 words or less)**
Hidora is a Swiss-based Managed Cloud Company that enables you to rapidly build and scale applications using Java, PHP, Ruby, Node.js, or Python. Their Platform-as-a-Service automates all complex system administration tasks, freeing you to focus solely on coding without worrying about hosting. With flexible billing, an intuitive interface, data security, and a 24/7/365 support team, Hidora provides everything you need for business success.

**Name of your relevant product(s) or service for the OpenSearch audience**
Hidora is a cloud hosting provider that offers a range of services to the OpenSearch community. Our core product offerings include scalable and reliable cloud infrastructure, managed databases, automated backups, and advanced monitoring and management tools to ensure optimal performance for OpenSearch clusters.

We also offer professional services to help customers optimize their OpenSearch environments, including performance tuning, security audits, and consulting services. Our team of experienced professionals provides expert guidance and support to ensure that our customers' OpenSearch clusters are running smoothly and efficiently.

At Hidora, we understand that deploying and managing OpenSearch clusters can be complex and time-consuming. That's why we offer a user-friendly platform and comprehensive support to make the process as simple as possible. We work closely with our customers to understand their unique needs and provide customized solutions to help them achieve their goals.

Whether you are a small startup or a large enterprise, Hidora has the expertise and resources to provide you with reliable and scalable cloud hosting solutions for your OpenSearch environments. Trust us to be your partner in optimizing and managing your OpenSearch clusters.

**What OpenSearch technologies do you specialize in**
We specialize in observability with OpenSearch, providing comprehensive monitoring and management tools to ensure optimal performance of your clusters.

**Type of business**
We work with end-customers, IT consulting firms, and system integrators, and we also provide on-premise integration services as an integrator ourselves.

**Home/main office location or address**
Geneva, Switzerland

**How can people contact you (email and phone)**
contact@hidora.io and 00 41 22 552 14 14

**Regions you serve**
Europe

**Industry specialization**
Business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology

**Logo**
![logo_hidora_1280-800 (1)](https://user-images.githubusercontent.com/10330979/224740873-41761bca-762a-4014-9b93-f21775bb92a5.png)

**Additional image**
<img width="651" alt="opensearch" src="https://user-images.githubusercontent.com/10330979/224741091-ac3951fa-ff17-4f5f-ae2b-ce8c03c06e6c.png">

**Links**
https://hidora.io/en/ressources/opensearch-le-secret-dune-meilleure-observabilite/
https://hidora.io/produits/hebergement-opensearch-manage/

**Comment by pajuric** [comment]
@matthieu-robin - Thank you for providing the info.
