### ISSUE TITLE
OpenSearch Community Forum - Forge Studio LLC Persona Research

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#1433]
**Describe the blog post your would like to write**
This post is similar to https://forum.opensearch.org/t/looking-for-opensearch-usability-study-candidates/13045 and is to request forum members to participate in Forge's survey

**What is the title of the blog post?**
OpenSearch Community Forum - Forge Studio LLC Persona Research

**Who are the authors?**
Aparna Sundar

**What is the proposed posting date?**
April 17th (one week later is fine)

**Comment by pajuric** [comment]
@apasun - Please update the content availability/tentative publish date.

**Comment by kgcreative** [comment]
@pajuric - Can we publish this week? https://quip-amazon.com/913CAsaIkCHV/03-OpenSearch-Community-Forum-Forge-Studio-LLC-Persona-Research
