### ISSUE TITLE
OpenSearch Wants to talk to Search Users

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#1435]
**Describe the blog post your would like to write**
The Search team wants to talk to Search users, very specifically Relevance Engineers and Search Engineers. We are describing the users in this blog and requesting them to participate in the study

**What is the title of the blog post?**
OpenSearch Wants to talk to Search Users

**Who are the authors?**
Aparna Sundar, Stavros Macrakis, Mark Cohen and Laura Pavlov

**What is the proposed posting date?**
3/15/2023

**Comment by pajuric** [comment]
Blog for posting in forum @krisfreedain
