### ISSUE TITLE
[maxcluster] partner information

### ISSUE THREAD

**Issue by dmonkey4224** [opensearch-project/project-website#1439]
**Organization name**
maxcluster GmbH

**Brief description of your business and what it does (50 words or less)**
maxcluster operates scalable, fail-safe and high-performance managed web clusters for e-commerce businesses. This includes 24/7/365 support by trained Linux administrators and a tech stack designed for the continuous operation of shop systems such as Magento or Shopware. Applications can be set up via the administration interface using pre-configured presets.

**Name of your relevant product(s) or service for the OpenSearch audience**
Managed e-commerce hosting
High traffic hosting
24/7/365 Support
Proactive monitoring of server load
Comprehensive performance and security scans

**What OpenSearch technologies do you specialize in**
With OpenSearch in a Managed Hosting package, customers of maxcluster can rely on the usual performance of their search function, but also secure many time-saving and convenient services and functions. maxcluster provides a pre-installed and pre-configured OpenSearch server on all clusters so that the first documents can be indexed within seconds.

**Type of business**
MSP

**Home/main office location or address**
Lise-Meitner-Str. 1b
33104 Paderborn
Germany

**How can people contact you (email and phone)**
[beratung@maxcluster.de](mailto:beratung@maxcluster.de) / +49 5251 4141 350

**Regions you serve**
Europe

**Industry specialization**
business services, software and technology

**Logo**
![maxcluster-logo_schwarz-rot_2021](https://user-images.githubusercontent.com/83065401/224991476-d372f402-921d-47cd-9b03-089880153fa7.svg)

**Additional image**
![DSC01290](https://user-images.githubusercontent.com/83065401/224991737-4bc52f1f-6378-49d6-8c6d-46ee27b4e3e3.JPG)
![DSC00797](https://user-images.githubusercontent.com/83065401/224991779-649cce47-4956-48cc-89aa-b981321c872d.jpg)

**Links**
https://maxcluster.de/en/knowledge-base/managedcenter/faq-zu-opensearch
https://maxcluster.de/en/blog/akeneo-pim-hosting-advantages-online-shops
https://maxcluster.de/en/blog/open-source-software-e-commerce-hosting

**Comment by pajuric** [comment]
@dmonkey4224 - Thank you for providing your company's information.
