### ISSUE TITLE
Bonsai partner information

### ISSUE THREAD

**Issue by coreyhaines31** [opensearch-project/project-website#1440]
**Name**
Bonsai

**Description**
The managed OpenSearch platform that provides the support of a search engineering team, but at a fraction of the cost.

**Name of your relevant product(s) or service for the OpenSearch audience**
Fully managed Elasticsearch, OpenSearch, & SolrCloud for mission-critical search engines
Make changes and improvements to search without being afraid to break something or have to rewrite from scratch.
- Performant and reliable search clusters at any scale
- Best-in-class search experience for your users
- Deploy in your own AWS or GCP account
- Instant insights into search performance
- Let us handle delicate upgrades for you

In-house search expertise at your service
Search works seamlessly through team turnover, even when the original engineer who set it up leaves.
- We take responsibility for every one of your clusters
- Meet even the most rigorous compliance standards
- On-demand support from expert engineers
- An advisory partner you can trust
- Instant access to our team

Focus on search relevance—not fixing bugs or downtime

**What OpenSearch technologies do you specialize in**
Search

**Type of business**
MSP

**Home/main office location or address**
2009 South 1st Street
Suite 100
Austin, TX 78704

**How can people contact you (email and phone)**
team@bonsai.io

**Regions you serve**
Global

**Industry specialization**
Education, financial services, healthcare, media and entertainment, non-profit, retail, software and technology.

**Logo**
[JPEG](https://uploads-ssl.webflow.com/63c81e4decde60c281417feb/6410bed83d54ea8623563617_bonsai-horizontal-green-dark.jpeg)
[PNG](https://uploads-ssl.webflow.com/63c81e4decde60c281417feb/6410bed8446268693dea9d18_bonsai-horizontal-green-dark%20(1).png)
[SVG](https://uploads-ssl.webflow.com/63c81e4decde60c281417feb/6410bed853b80d614c056c2d_bonsai-horizontal-green-dark.svg)

**Additional image**
[Integrations](https://global-uploads.webflow.com/63c81e4decde60c281417feb/63c81e4decde6046a3418101_Integrate%20illustration.webp)

**Links**
[Welcome to OpenSearch](https://bonsai.io/blog/welcome-to-opensearch)
[Up and Running with OpenSearch](https://bonsai.io/blog/up-and-running-with-opensearch)
[Migrating from Elasticsearch to OpenSearch](https://bonsai.io/blog/migrating-from-elasticsearch-to-opensearch)

**Comment by pajuric** [comment]
@coreyhaines31 - Thanks, Corey, for the information.
