### ISSUE TITLE
Searchium.ai partner information

### ISSUE THREAD

**Issue by noamschwartz** [opensearch-project/project-website#1442]
**Organization name**
Searchium.ai 

**Brief description of your business and what it does (50 words or less)**
Searchium.ai is a SaaS platform that optimizes neural search applications. 

Based on in-memory computing built specifically for search, we give you a significant advantage, easy-to-integrate neural search that scales to billions without sacrificing speed or accuracy. 

**Name of your relevant product(s) or service for the OpenSearch audience**
 The Searchium OpenSearch plugin enables you to connect remotely to a hardware accelerator for low latency searching and infrastructure cost reduction. 

**What OpenSearch technologies do you specialize in**
Search

**Type of business**
Product/technology 

**Home/main office location or address**
18 Raul Wallenberg, Tel Aviv, Israel

**How can people contact you (email and phone)**
yvaknin@gsitechnology.com
devopsil@gsitechnology.com 
social@gsitechnology.com

**Regions you serve**
Searchium.ai's products and services are available globally, covering all regions. (North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia)

**Industry specialization**
Software and technology

**Logo**
![searchiumai](https://user-images.githubusercontent.com/46248427/225263340-e8b95096-e4d5-4b86-8cec-5800d6d3af5a.png)

**Links**
https://searchium.ai 
https://betterprogramming.pub/tired-of-troubleshooting-idle-search-resources-use-opensearch-benchmark-for-performance-tuning-d4277c9f724
https://towardsdatascience.com/bolster-opensearch-performance-with-5-simple-steps-ca7d21234f6b
https://towardsdatascience.com/text-search-vs-vector-search-better-together-3bd48eb6132a
https://medium.com/gsi-technology/the-apu-novel-hardware-for-accelerated-similarity-search-beaef9b19b97
https://medium.com/gsi-technology/semantic-vector-search-taking-the-leap-from-keyword-search-18855e96854a
https://towardsdatascience.com/speeding-up-bert-search-in-elasticsearch-750f1f34f455
https://github.com/Searchium-ai

**Comment by pajuric** [comment]
@noamschwartz - Thanks, Noam, for proving the information.
