### ISSUE TITLE
Dattell partner information

### ISSUE THREAD

**Issue by barryhatfield** [opensearch-project/project-website#1445]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Dattell

**Brief description of your business and what it does (50 words or less)**
Dattell offers consulting support and managed services for OpenSearch, Elasticsearch, Kafka, and Pulsar.  We support implementations in our clients’ environments, on-prem or cloud (AWS, GCP, Azure). 

All of our team members are senior level DevOps, IT, or programming professionals with 10+ years experience running data infrastructure for complex use cases.

**Name of your relevant product(s) or service for the OpenSearch audience**
Managed Opensearch - We provide enterprise level managed OpenSearch in your environment.  You will work with a consistent OpenSearch expert who gets to know your team, use case, and implementation.  This OpenSearch engineer will be available to you like an extension of your team on Slack/Teams/etc., in meetings, by phone, and email.  They will focus on preventative maintenance, optimization, monitoring, training, and any other technical assistance needed.  Your dedicated engineer will also be the first to respond 24x7 to production-level issues.  And we have our larger team of OpenSearch engineers available for additional support. We guarantee a response time of 15 minutes for production level issues, 24x7x365.

Consulting Services for OpenSearch - We provide you with a consistent OpenSearch expert who gets to know your team, use case, and implementation.  This OpenSearch engineer will be available to you during work hours like an extension of your team on Slack/Teams/etc., in meetings, by phone, and email.  They will focus on preventative maintenance, optimization, monitoring, training, and any other technical assistance needed.  We guarantee a response time of 3 business hours for all issues/inquiries, and we have an average response time of 20 minutes. 

**What OpenSearch technologies do you specialize in**
We specialize in support of open source, free license software.  That includes OpenSearch in all of its various implementations including: search, logging and monitoring, analytics, observability, security, e-commerce, machine learning, vector search, and content management.
In addition, we support ancillary open source, free license software such as Apache Kafka, and Apache Pulsar.

**Type of business**
MSP and services organization

**Home/main office location or address**
12636 High Bluff Dr, San Diego, CA 92130

**How can people contact you (email and phone)**
support@dattell.com
(619) 786-0813

**Regions you serve**
North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia

**Industry specialization**
Financial Services, Healthcare, Software & Technology, Media, Public Sector, Consumer Services, Business Services, Energy & Utilities, Internet of Things, Fintech, Healthtech, Saas, Defense, Biotech, Medtech, High Tech, Energy & Utilities

**Logo**
Please upload a company logo
![dattell logo high res](https://user-images.githubusercontent.com/5238796/225459455-91972a99-35aa-4679-837f-d533afc5b9fa.png)

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)
<img width="810" alt="dattell additional image" src="https://user-images.githubusercontent.com/5238796/225459458-0e4cb614-68a2-4b3f-abf7-496ddc343505.png">

**Links**
https://dattell.com/data-architecture-blog/enterprise-managed-opensearch/
https://dattell.com/data-architecture-blog/planning-a-successful-migration-to-opensearch/
https://dattell.com/data-architecture-blog/how-to-query-opensearch-with-boolean-queries/

**Comment by pajuric** [comment]
@barryhatfield - Thank you for providing the info for the new page.
