### ISSUE TITLE
Metarank partner information

### ISSUE THREAD

**Issue by vgoloviznin** [opensearch-project/project-website#1447]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Metarank Labs Co.

**Brief description of your business and what it does (50 words or less)**
Metarank Labs Co. provides integration and ongoing support for companies that use open source personalized ranking and recommendations service Metarank.

**Name of your relevant product(s) or service for the OpenSearch audience**
Metarank is an open source ppersonalized ranking and recommendations service. You don't need to be an expert in machine learning or data science to enhance your search results with personalization that is based on your user activities and recommendation widgets to improve your business metrics. YAML configuration and an easy to integrate JSON API will get you up and running within minutes.

**What OpenSearch technologies do you specialize in**
search, recommendations, personalization

**Type of business**
product/technology, services

**Home/main office location or address**
N/A

**How can people contact you (email and phone)**
seva@metarank.ai

**Regions you serve**
Worldwide

**Industry specialization**
business services

**Logo**
Please upload a company logo

**Additional image**
-

**Links**
https://blog.metarank.ai/learn-to-rank-with-opensearch-and-metarank-3557fa70f8e8
https://blog.metarank.ai/search-results-diversification-with-metarank-b19e1eeeb237
https://blog.metarank.ai/personalized-ranking-api-with-docker-d73b52e4cedb
Add links to your last three blogs that are relevant for the OpenSearch Project audience.

**Comment by vgoloviznin** [comment]
![logo_512](https://user-images.githubusercontent.com/4601358/225690464-af0ebee1-cf3d-4b05-b271-c5e8585b4625.png)

**Comment by pajuric** [comment]
@vgoloviznin - Thank you for adding your company information.
