### ISSUE TITLE
Instaclustr partner information

### ISSUE THREAD

**Issue by abunday** [opensearch-project/project-website#1451]
**Organization name** 

Instaclustr, now part of Spot by NetApp 

**Brief description of your business and what it does (50 words or less)** 

Instaclustr helps organizations deliver applications at scale by operating and supporting their data infrastructure through its SaaS platform for open source technologies, whether on-prem or in their cloud of choice. 

In addition to managed platforms, Instaclustr also offers 24x7 support services, consulting and training for numerous open source technologies.   

**Name of your relevant product(s) or service for the OpenSearch audience** 

Instaclustr provides a fully managed and hosted service for OpenSearch on your cloud provider of choice under the Apache 2.0 License. 

**What OpenSearch technologies do you specialize in** 

- Fully managed and hosted OpenSearch service 
- Configure through the Instaclustr SaaS platform, Instaclustr API or Terraform 
- 24x7 Expert support 
- SOC 2, PCI Private Network and PrivateLink enabled 
- Built-in monitoring 
- 99.999% SLA 
- Run in your cloud provider account or ours 

**Type of business** 

Managed Service Provider   

**Home/main office location or address** 

Canberra, Australia and San Jose, California, US 

**How can people contact you (email and phone)** 

Support@instaclustr.com 

**Regions you serve** 

Worldwide  

**Industry specialization** 

All industries  

**Logo** 

Please see logo attached. 
PNG: 
![Instaclustr_Spot_NetApp_Favicon_512x512_RGB_lt](https://user-images.githubusercontent.com/127374624/225776535-78ea8a96-bcec-4087-895b-0692f2079c7a.png)
  
**Links** 

Add links to your last three blogs that are relevant for the OpenSearch Project audience. 

https://www.instaclustr.com/blog/opensearch-feature-update/ 

https://www.instaclustr.com/blog/opensearch-2-now-in-preview-release/ 

https://www.instaclustr.com/blog/instaclustr-updates-nodes-types-for-opensearch-offering/

**Comment by pajuric** [comment]
@abunday - Thank you for your submission.
