### ISSUE TITLE
[BUG] Correction to existing blog

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/project-website#1452]
**Describe the bug**
A correction to an existing blog needs to be made

**To Reproduce**
1. Go to this blog: ['k-nn'](https://opensearch.org/blog/Building-k-Nearest-Neighbor-(k-NN)-Similarity-Search-Engine-with-Elasticsearch/)
2. Look for the line:  The knn_vector field supports vectors up to 10,000 dimensions. 
3. It should be 16,000 dimensions

**Expected behavior**
See https://github.com/opensearch-project/documentation-website/pull/3515
We are updating it on the documentation side.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Version: [e.g. 22]
 - Browsers: [e.g. Chrome, Safari]
 - Browser Version: [e.g 93.0.4521.12]

**Additional context**

**Comment by pajuric** [comment]
@hdhalter - are we good to close this issue?

**Comment by hdhalter** [comment]
Was the blog updated? We only updated the documentation.

**Comment by dtaivpp** [comment]
Resolved in #1509
