### ISSUE TITLE
Launch Highlight: VisBuilder

### ISSUE THREAD

**Issue by vagimeli** [opensearch-project/project-website#1459]
**Describe the blog post your would like to write**
Announcement of that VisBuilder is no longer experimental and is production-ready. Brief overview of what you can do with VisBuilder, how it works, and examples.

**What is the title of the blog post?**
Launch Highlight: VisBuilder

**Who are the authors?**
@ashwin-pc 

**What is the proposed posting date?**
Release 2.7

**Comment by pajuric** [comment]
@ashwin-pc - Please provide an update so the team know when to plan to review and publish the blog.

**Comment by ashwin-pc** [comment]
@pajuric This is delayed until at least 2.10 for now.

**Comment by pajuric** [comment]
@ashwin-pc - Any update on this now that we're on 2.11?

**Comment by ashwin-pc** [comment]
This will likely go out as a part of Data Explorer in 2.12. Will update this issue once I confirm that with @dagneyb and @ananzh. cc: @wbeckler
