### ISSUE TITLE
OpenSource Connections partner information

### ISSUE THREAD

**Issue by flaxsearch** [opensearch-project/project-website#1462]
**Organization name**
OpenSource Connections

**Brief description of your business and what it does (50 words or less)**
OpenSource Connections are leading specialists in search relevance, focused on open source technologies including OpenSearch. We help your tune your search engine to deliver the right results to delight your users. We wrote the Manning book Relevant Search, host the Haystack search conference and run Relevance Slack, a 3500-person community. 

**Name of your relevant product(s) or service for the OpenSearch audience**
Think Like a Relevance Engineer Training for OpenSearch 
OpenSearch consulting on search relevance
Free Quepid tool for search tuning is compatible with OpenSearch

**What OpenSearch technologies do you specialize in**
Search relevance

**Type of business**
Services organisation, consultancy & training

**Home/main office location or address**
Charlottesville, Virginia, USA & Berlin, Germany

**How can people contact you (email and phone)**
hello@opensourceconnections.com
US (434) 466-1467
UK +44 (08700) 118334

**Regions you serve**
North America, Europe, others on application

**Industry specialization**
Business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology

**Logo**
Please upload a company logo
![OpenSource Connections](https://user-images.githubusercontent.com/4929380/227173918-55d232e0-963e-4ea1-91f9-340cc3994c0e.png)

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
https://opensourceconnections.com/blog/2022/10/03/opensearchcon-2022/
https://opensourceconnections.com/blog/2023/03/22/building-vector-search-in-chorus-a-technical-deep-dive/
https://opensourceconnections.com/blog/2022/09/20/opensearch-comes-of-age/

**Comment by pajuric** [comment]
@flaxsearch - Thank you for updating your partner info.
