### ISSUE TITLE
Bitergia partner information

### ISSUE THREAD

**Issue by emiliogaleanog** [opensearch-project/project-website#1464]
**Organization name**
Bitergia

**Brief description of your business and what it does (50 words or less)**
Bitergia helps companies improve the ROI of their software development projects by providing tools and knowledge to improve decision making. iIts core platform is 100% open source. The Bitergia team has 15+ years experience in research focused on collaborative software development methodologies and software development quality models. 

**Name of your relevant product(s) or service for the OpenSearch audience**
- [Bitergia Analytics Platform:(https://bitergia.com/bitergia-analytics/) Our centralized source for metrics and data about the software development projects that matter to you
- [GrimoireLab](https://chaoss.github.io/grimoirelab/): GrimoireLab is a set of tools to retrieve, organize, analyze, and visualize data coming from software development repositories. 

**What OpenSearch technologies do you specialize in**

- Analytics
- Observability

**Type of business**
Product/technology and services organization

**Home/main office location or address**
Madrid, Spain - Remote

**How can people contact you (email and phone)**
info@bitergia.com

**Regions you serve**
We are a global company, available to serve any customer around the world

**Industry specialization**
Software and technology

**Logo**
![bitergia_logo_text](https://user-images.githubusercontent.com/100841981/227252653-17907db2-3a9a-49fe-8806-eb512cb09401.svg)

**Additional image**
![engagement](https://user-images.githubusercontent.com/100841981/227252884-44ecd062-e1f4-496a-81fb-81043210c17e.jpg)
![community-growth](https://user-images.githubusercontent.com/100841981/227252890-ffeef1c0-7263-46c0-ba65-8a6bc941821d.jpg)
![efficiency](https://user-images.githubusercontent.com/100841981/227252891-979b043a-39c1-4436-9899-180f7731e96c.jpg)
![overview](https://user-images.githubusercontent.com/100841981/227252893-4bfdecea-a3ca-4172-84fb-c7d2fdd35888.jpg)

**Links**
- [The first release of Bitergia Analytics Platform based on OpenSearch.](https://blog.bitergia.com/2022/05/18/the-first-release-of-bitergia-analytics-platform-based-on-opensearch/)
- [Identify community contributors with this new feature that will save you time](https://blog.bitergia.com/2022/12/26/identify-community-contributors-with-this-new-feature-that-will-save-you-time/)
- [How to run SQL queries on the Bitergia Analytics Platform](https://blog.bitergia.com/2022/07/06/how-to-run-sql-queries-on-the-bitergia-analytics-platform/)

**Comment by pajuric** [comment]
@emiliogaleanog  - Thank you for updating your partner info.
