### ISSUE TITLE
GSI Technology Partner Information

### ISSUE THREAD

**Issue by GSIT3ch** [opensearch-project/project-website#1467]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
GSI Technology, Inc.

**Brief description of your business and what it does (50 words or less)**
GSI Technology offers the Gemini® APU, a massively parallel compute in-memory processor for big data similarity search. This innovative technology is offered both as an on-premises or SaaS solution. GSI currently holds over 50 patents for our associative computing technology.

**Name of your relevant product(s) or service for the OpenSearch audience**
GSI’s OpenSearch neural search plugin, based on the Gemini® APU, allows you to extend your current OpenSearch software investment with a production-grade neural search solution that searches billions of items in milliseconds, with high recall. There’s no need to learn a new software program or new APIs, saving you valuable time and resources and enables rapid deployment.
GSI’s neural search acceleration is offered in both on-premises and SaaS deployments.

**What OpenSearch technologies do you specialize in**
k-NN, Approximate Nearest Neighbor (ANN), and Multi-modal Search acceleration for lower latency, higher accuracy, and lower power, with economical very large database support for ANN

**Type of business**
Product/Technology and Services Organization

**Home/main office location or address**
1213 Elko Drive
Sunnyvale, CA  94089

**How can people contact you (email and phone)**
opensearch@gsitechnology.com

**Regions you serve**
North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia

**Industry specialization**
Software and Technology 
Supporting various industries (business services, IOT, financial services, healthcare, retail), including Aerospace & Defense

**Logo**
![GSIT-logo](https://user-images.githubusercontent.com/126887685/227566379-d8652202-5adf-440e-8e58-61af7e059840.png)

**Additional image**
![GSIT-Opensearch-Graphic-1](https://user-images.githubusercontent.com/126887685/227566027-d9370a59-b8e2-45bf-9b3d-9951d6b2a6f1.jpg)

![GSIT-Opensearch-Graphic-2](https://user-images.githubusercontent.com/126887685/227566048-08282ea7-e6e6-4645-8038-875aff919dad.jpg)

**Links**
https://www.gsitechnology.com/Mulimodal-and-Mulilingual-Vector-Search-with-Hardware-Acceleration
https://www.gsitechnology.com/Role-of-Hardware-in-Energy-Efficient-Vector-Search
https://www.gsitechnology.com/content/Vector-Databases-Made-Easy

**Comment by pajuric** [comment]
@GSIT3ch - Thank you for the updated information.
