### ISSUE TITLE
Eliatra

### ISSUE THREAD

**Issue by jochen-kressin** [opensearch-project/project-website#1471]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Eliatra

**Brief description of your business and what it does (50 words or less)**
Eliatra provides Enterprise Solutions for OpenSearch, including support with guaranteed SLAs, professional services, and custom development. Our Eliatra Suite plugins for OpenSearch and Dashboards make it easy to set up and run OpenSearch for Mission-critical systems.

**Name of your relevant product(s) or service for the OpenSearch audience**
Eliatra Suite

**What OpenSearch technologies do you specialize in**
Is there an area of the project where your business specializes?
We specialize in Security and Alerting and are your trusted partner for planning, implementing, and running OpenSearch projects. We have extensive knowledge in migrating clusters from the Elastic Stack to OpenSearch.

**Type of business**
(e.g., MSP, CSP, ISV, product/technology, services organization, other). If other, please define.
We are a product and services company.

**Home/main office location or address**
77 Lower Camden Street
Dublin, D02 XE80, Ireland

**How can people contact you (email and phone)**
info@eliatra.com
https://eliatra.com/contact/

**Regions you serve**
(e.g.,North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia)
What regions of the world do you serve?
Worldwide

**Industry specialization**
(e.g. business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology)? Add all that apply.
All verticals

**Logo**
Please upload a company logo

![logo-background-green@2x](https://user-images.githubusercontent.com/126353411/228227900-de42abc2-e2cc-4e47-ad0a-b6ed3f0afa4c.png)

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

![logo-wordmark-background-green@2x](https://user-images.githubusercontent.com/126353411/228227973-04d88d3e-4c89-41d8-b908-a69edc553a14.png)

**Links**
[Add links to your last three blogs that are relevant for the OpenSearch Project audience.]

* [Eliatra Suite](https://eliatra.com/blog/eliatra-suite-for-opensearch-is-here/)
* [Migrating from X-Pack to OpenSearch](https://eliatra.com/blog/from-x-pack-to-opensearch-part-1-tls-setup/)
* [Using OpenSearch on Kubernetes](https://eliatra.com/blog/opensearch-kubernetes-helm/)

**Comment by pajuric** [comment]
@jochen-kressin - Thank you, Jochen, for contributing the information.
