### ISSUE TITLE
deepset partner information

### ISSUE THREAD

**Issue by aantti** [opensearch-project/project-website#1481]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
deepset

**Brief description of your business and what it does (50 words or less)**
deepset is the company behind Haystack NLP and deepset Cloud enterprise ML/NLP platform. Started in 2018 by Milos Rusic, Malte Pietsch and Timo Möller, deepset has enabled many enterprises and public sector organizations to build innovative NLP-driven search solutions. deepset is backed by leading VC firms, and former founders of well-known machine learning and commercial open source companies

**Name of your relevant product(s) or service for the OpenSearch audience**
Our flagship open source project is Haystack — an NLP framework to interact with your data using Transformer models and LLMs (GPT-4, ChatGPT and alike). Haystack offers production-ready tools to quickly build question answering, semantic search, text generation applications, and more. We also have an enterprise ML/NLP platform to build NLP-driven products — deepset Cloud.

**What OpenSearch technologies do you specialize in**
Developers can use Haystack with OpenSearch as a scalable 'DocumentStore' — leveraging OpenSearch capabilities for keyword- and vector-based search. OpenSearch is also part of the deepset Cloud's data storage infrastructure.

**Type of business**
ISV, SaaS, product/technology, and services organization.

**Home/main office location or address**
We have offices in Berlin, Germany and New York, USA.

**How can people contact you (email and phone)**
Best to use the website form, but also 'engage at' for the email. (The domain part is deepset.ai)

**Regions you serve**
Worldwide, with the focus on North America and Europe.

**Industry specialization**
Our technology and products are used horizontally by companies of all sizes across many verticals. NLP has become quite pervasive, but we see primarily financial industry, legal, healthcare and manufacturing amongst the verticals that rapidly adopt new NLP-driven products.

**Logo**
![deepset-signet-colored](https://user-images.githubusercontent.com/56412611/229181994-3f785134-5c5c-4580-b4ef-84afcdb18ad7.svg)

**Additional image**
![haystack-logo-colored](https://user-images.githubusercontent.com/56412611/229182127-fa6dd8fd-377f-492d-8ef5-2c3d92372ce6.png)

**Links**
https://www.deepset.ai/
https://www.deepset.ai/blog
https://haystack.deepset.ai/

**Comment by pajuric** [comment]
@aantti - Thank you for providing the information. We'll get working on the page.
