### ISSUE TITLE
Seacom partner information

### ISSUE THREAD

**Issue by anteos** [opensearch-project/project-website#1482]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Seacom srl sb

**Brief description of your business and what it does (50 words or less)**
Seacom has been working in Information Technology since 1999, offering professional services to enterprise-level companies and public administrations on Open Source software. Our main offerings are email and collaboration, data management architectures, cybersecurity, and Cloud Native infrastructures.
Seacom has been main Elastic's partner in Italy since 2013, gaining strong product experience, and certifications in developing enterprise-level projects.

**Name of your relevant product(s) or service for the OpenSearch audience**
Seacom has developed LogOs, an OpenSearch-based solution that ensures, starting with log analysis, a comprehensive monitoring system for security and compliance management.

Seacom services leverage OpenSearch with the goal of optimizing IT architectures from the perspectives of log search and management, resource indexing, system observability, and security.

We have a deep knowledge of search challenges in documents, social network data, e-commerce content, etc.

Our experience in data management has given us the ability to develop custom connectors that can integrate OpenSearch technology with other BI solutions and visualization tools.

**What OpenSearch technologies do you specialize in**
Ordered by relevance and specialization:
Observability
Security
Search
Analytics
NLP
SNA

**Type of business**
Consultancy
Support
Product

**Home/main office location or address**
Via Gramsci 5 
56021 NAvacchio (PI), Italy

**How can people contact you (email and phone)**
info@seacom.it
+390500984020

**Regions you serve**
We are based in Italy, but we serve customers across Europe, Middle East and Africa

**Industry specialization**
(e.g. business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology)? Add all that apply.

**Logo**
![seacom_logo_PNG](https://user-images.githubusercontent.com/2715377/229167265-a040edac-71ab-4d82-8fc7-6d118e5258cf.png)

**Additional image**
<img width="724" alt="Screenshot 2023-03-31 alle 17 56 42" src="https://user-images.githubusercontent.com/2715377/229170667-3d9ec6d0-0d00-43c1-a5fa-c4ad1a4a45d5.png">
<img width="724" alt="Screenshot 2023-03-31 alle 17 56 24" src="https://user-images.githubusercontent.com/2715377/229170671-fcbd89dd-958a-4928-8027-1acad15e99ac.png">

**Links**
https://www.seacom.it/novita-opensearch-2-4-0/
https://www.seacom.it/prevenire-le-vulnerabilita-in-ambiente-zimbra-con-logos/
https://www.seacom.it/data-visualization-per-il-business-limportanza-di-una-soluzione-completa-per-la-reportistica/

**Comment by pajuric** [comment]
@anteos - Thank you for the info, Stefano.
