### ISSUE TITLE
Graylog Partner Information

### ISSUE THREAD

**Issue by spradlink** [opensearch-project/project-website#1500]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Graylog

**Brief description of your business and what it does (50 words or less)**
Graylog is a SIEM and log management solution that offers robust, cost-effective ways to protect your organization. Using AI/ML, security analytics, and intelligent alerting, Graylog enables you to stay ahead of threats and  addresses the needs of IT Ops teams, making it easy to normalize, visualize, and analyze log data from any source. 

**Name of your relevant product(s) or service for the OpenSearch audience**
Graylog Security

**What OpenSearch technologies do you specialize in**
Security & Analytics

**Type of business**
Software vendor, available in both SaaS and on-prem/self-managed

**Home/main office location or address**
Houston, TX

**How can people contact you (email and phone)**
info@graylog.com

**Regions you serve**
Global with offices in US, Canada, UK, and Germany

**Industry specialization**
Graylog Security is applicable to all industries

**Logo**
Please upload a company logo

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
Add links to your last three blogs that are relevant for the OpenSearch Project audience.

1. https://www.graylog.org/features/anomaly-detection-ml-ueba/
2. https://www.graylog.org/post/centralized-log-management-for-access-monitoring/
3. https://www.graylog.org/post/graylog-to-add-support-for-opensearch/

![Graylog Dashboard Account-Detail](https://user-images.githubusercontent.com/45244475/229634602-52cab591-d8de-40f8-b6c8-4d1a7eae3ff2.png)
![Graylog Diagram](https://user-images.githubusercontent.com/45244475/229634605-ad0f6af2-44eb-47a2-8333-33f5d2e78ea3.png)
[Round Graylog Logo Icons.zip](https://github.com/opensearch-project/project-website/files/11142777/Round.Graylog.Logo.Icons.zip)

**Comment by pajuric** [comment]
@spradlink - Thank you, Kimber. I appreciate it.
