### ISSUE TITLE
[BUG] Please remove link checker from the build process

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/project-website#1501]
**Describe the bug**
Please remove Check Link (added during this PR https://github.com/opensearch-project/project-website/pull/1470) from the build process completely. It reports false positives every time it runs.  

**To Reproduce**
see https://github.com/opensearch-project/project-website/issues/1478 as an example of how many false positives

**Additional context**
Would like to see a similar - separate - report run through cron on a weekly basis - but with a reference to what file the link is contained in so it is actionable by the project-website team to go research and clean up where needed.

**Comment by krisfreedain** [comment]
This would be helpful @dblock - thanks

**Comment by dblock** [comment]
I believe I fixed these in https://github.com/opensearch-project/project-website/pull/1492. Can we please merge that before removing it?

**Comment by dblock** [comment]
Updated to run on a daily cron and on demand.

Producing a report in the GitHub issue is difficult, but the update in #1492 property reports where the broken links are in all cases.

**Comment by dtaivpp** [comment]
Merged and looks good!
