### ISSUE TITLE
[DOC] Hyperlinks on blog not easily visible to eye.

### ISSUE THREAD

**Issue by monu-aws** [opensearch-project/project-website#1502]
**What do you want to do?**
 
- [ ✅ ] Request a change to existing documentation
- [ ] Add new documentation
- [ ] Report a technical problem with the documentation
- [ ] Other 

The hyper links on the blog are not at all easily visible as the only difference is the underline. This makes going through the doc and missing links very easy.

A better visual difference would allow for better user experience.
Example : https://opensearch.org/blog/semantic-science-benchmarks/
 

**What other resources are available?** Provide links to related issues, POCs, steps for testing, etc.

**Comment by dtaivpp** [comment]
I'm open to this. I think we've kept them a bit discreet to ensure they dont take away from the articles but they could have a bit higher contrast. Maybe an alternative would be to have a higher contrast theme from the site that people could toggle kinda like a dark mode.

**Comment by monu-aws** [comment]
Yeah, currently its very easy to miss important hyperlinks.

**Comment by monu-aws** [comment]
This is also an issue on the main website https://opensearch.org/

**Comment by dtaivpp** [comment]
Okay I present 3 options. Which are you all in favor of:

Current for reference: 
<img width="847" alt="Screenshot 2023-04-06 at 3 59 23 PM" src="https://user-images.githubusercontent.com/17506770/230482501-773580f6-337e-431d-b2a1-a0901c9fdaa9.png">
1️⃣
<img width="830" alt="Screenshot 2023-04-06 at 3 58 24 PM" src="https://user-images.githubusercontent.com/17506770/230482515-2f3d3e38-030b-4a10-9b1d-e1fbcee34a56.png">
2️⃣
<img width="846" alt="Screenshot 2023-04-06 at 4 02 09 PM" src="https://user-images.githubusercontent.com/17506770/230482530-252f8db4-5b6b-48ff-aee9-321279aa8ddb.png">

**Comment by nateynateynate** [comment]
@dtaivpp - I actually don't see a difference between the options. Did you paste the same thing on accident?

**Comment by dtaivpp** [comment]
Actually I was looking over them and it seems like the difference is just so minuscule maybe it doesn't matter. Do the new hyperlinks look better?

**Comment by monu-aws** [comment]
#0055A6 is the color currently used on the website for hyperlinks. 1️⃣ looks better.

**Comment by dtaivpp** [comment]
@monu-aws I agree I think. Going to PR it and if people end up not liking it they will come back here and let us know. 😆

**Comment by monu-aws** [comment]
Thank you very much @dtaivpp
One more minor comment, if the link is visited the color remains to be the old one.

**Comment by dtaivpp** [comment]
@monu-aws I feel like that's an expected color for a link you've visited already. I'm open to other opinions though.
