### ISSUE TITLE
[BUG] Fira Code font missing

### ISSUE THREAD

**Issue by shyim** [opensearch-project/project-website#1517]
**Describe the bug**
Fira Code font is not there and the requests are failing and makes the website feeling slow

**To Reproduce**
1. Go to https://opensearch.org/blog/technical-roadmap-opensearch-extensibility/
2. Open network tab

**Expected behavior**
Fonts are loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/6224096/230666841-b8b02e40-7c36-4ef8-91ba-3f7d7ac213af.png)

**Host/Environment (please complete the following information):**
 - OS: Windows
 - Version: 11
 - Browsers: Chrome
 - Browser Version: 114.0.5696.0

**Additional context**

**Comment by nateynateynate** [comment]
Thanks @shyim ! I think we in general try to use the open source OpenSans font. Interesting that we're still trying to use FiraMono. I suspect some kind of regression.

**Comment by nateynateynate** [comment]
I think we've managed to solve this one @shyim. Thanks!
