### ISSUE TITLE
[Website update] Students page

### ISSUE THREAD

**Issue by rednaksi91** [opensearch-project/project-website#1518]
**Is your feature request related to a problem? Please describe.**
On March 1st, the College Contributor Initiative (CCI) was successfully launched. As of 4/7/23 there are 153 PRs created by College contributors, and yet there is no information about the program on the project website. This is resulting in lost opportunity to inform more college contributors about CCI.

**Describe the solution you'd like**
We need a page on the project website that provides consolidated information about CCI (what it is; how to join; what is the benefit for students).

**Comment by pajuric** [comment]
As far as naming this section, we should consider creating a section called "Educational Resources" or something along those lines. That way we're able to build out this section over time.
