### ISSUE TITLE
[Blog] Flat Object in OpenSearch

### ISSUE THREAD

**Issue by mingshl** [opensearch-project/project-website#1525]
**Describe the blog post your would like to write**
we are introducing  a new field type in OpenSearch: flat object. 

**What is the title of the blog post?**
Flat_Object field type in OpenSearch

**Who are the authors?**
Mingshi Liu

**What is the proposed posting date?**
6/13/23

**Comment by nateynateynate** [comment]
A great idea! I've never quite understood the topic myself!

**Comment by pajuric** [comment]
@mingshl - Please provide an update re this blog and when it will be ready for review and publication.

**Comment by pajuric** [comment]
Writer is indicating 2-3 weeks. Please confirm.

**Comment by mingshl** [comment]
working with a use case 

> @mingshl - Please provide an update re this blog and when it will be ready for review and publication.

ready for review
