### ISSUE TITLE
Blog post: Improving JSON parsing performance in opensearch-java

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/project-website#1527]
**Describe the blog post your would like to write**

This post will explain the process of the author discovering, diagnosing and fixing a performance issue in the opensearch-java client.

**What is the title of the blog post?**

Improving JSON parsing performance in opensearch-java

**Who are the authors?**

Benoit is the sole author

**What is the proposed posting date?**
As soon as there is space

**Comment by dblock** [comment]
@wbeckler This is related to https://github.com/opensearch-project/opensearch-java/pull/293 - @chibenwa are you still writing it? PR?

**Comment by pajuric** [comment]
@dblock  and @wbeckler - Are you able to work with Benoit to finalize the edits on this blog?

**Comment by wbeckler** [comment]
Benoit has asked me to go through the latest suggestions and modify the PR accordingly. I will do that review on Monday, and if all goes well, it can go out same week or whatever works for the blog team.
