### ISSUE TITLE
Aiven partner information

### ISSUE THREAD

**Issue by mattstratton** [opensearch-project/project-website#1530]
**Organization name**
Aiven

**Brief description of your business and what it does (50 words or less)**
Aiven provides managed open source data technologies, such as PostgreSQL®, Apache Kafka® and OpenSearch®, on all major clouds. 

**Name of your relevant product(s) or service for the OpenSearch audience**
Aiven for OpenSearch®

**What OpenSearch technologies do you specialize in**
OpenSearch as a fully managed service, with a rich set of advanced plugins and dashboards to visualize your data – easily deployed in the cloud of your choice.

**Type of business**
Managed service provider

**Home/main office location or address**
Aiven Oy
Antinkatu 1, 6th floor, 00100
Helsinki, Finland

**How can people contact you (email and phone)**
https://aiven.io/contact

**Regions you serve**
North America, South America, Europe, Middle East, Africa, Asia Pacific, and Australia

**Industry specialization**
Managed OpenSearch®

**Logo**
![aiven-logo](https://user-images.githubusercontent.com/1280666/232574504-e9a047ed-ac2e-48c1-b433-c1d4931a68c1.png)

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
https://aiven.io/blog/opensearch-dinner-party
https://aiven.io/blog/introduction-to-opensearch
https://aiven.io/blog/opensearch-fireside-chat

**Comment by pajuric** [comment]
@mattstratton - Thank you for contribution. We'll get your partner page built.
