### ISSUE TITLE
Suggestion: mention Apache 2.0 in website page footers

### ISSUE THREAD

**Issue by macrakis** [opensearch-project/project-website#1534]
Currently, pages on the project look like this:

> © 2023 OpenSearch contributors. OpenSearch is a registered trademark of Amazon Web Services.
 
> © 2005-2021 Django Software Foundation and individual contributors. Django is a registered trademark of the Django Software Foundation.
> This website was forked from the BSD-licensed djangoproject.com originally designed by Threespot & andrevv.
> We ♡ Django and the Django community. If you need a high-level Python framework, check it out.

I suggest that we include a license statement along with the copyrights, something like “released under the Apache 2.0 license”. We mention the djangoproject license but not the licenses for this page.

Do we really need the "We ♡ Django" line? It sounds sorta hokey and I don't believe it's required.

**Comment by kaimmej** [comment]
Should we be mentioning Django's license? 
That we mention Django's license is confusing to me. I suggest we swap the Django license text for the Apache 2.0 license text.

**Comment by smacrakis** [comment]
I agree it's confusing, and I don't think it's either legally required or "good practice". The Django license applies to the web technology serving the site.

**Comment by nateynateynate** [comment]
Solved by #3157
