### ISSUE TITLE
KubeCon Conference OpenSearch Observability days

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/project-website#1544]
**Describe the blog post your would like to write**
A conclusive overview on the KubCon Conference in Amsterdam with an emphasis on OpenSearch Observability solution,
The latest news about the convergence of OTEL & ECS protocol and how it generates a new vision for a unified Observability 
Recent features in Observability including Schema, fluent-bit, integrations & jaeger traces ingestion

**What is the title of the blog post?**
KubCon 2023 OpenSearch Observability highlight 

**Who are the authors?**
Lior Perry 
Derek Ho
Simeon Widdis

**What is the proposed posting date?**
early may

**Comment by nateynateynate** [comment]
@YANG-DB - Any interesting in pursuing this one still?

**Comment by YANG-DB** [comment]
I think this is under review - the post was sent to reviews earlier this week and awaiting comments

**Comment by pajuric** [comment]
Revised outline due w/o 6/12/23

**Comment by pajuric** [comment]
Not completed
