### ISSUE TITLE
Tracetest partner information

### ISSUE THREAD

**Issue by adnanrahic** [opensearch-project/project-website#1549]
**Organization name**
Tracetest (part of the Kubeshop accelerator)

**Brief description of your business and what it does (50 words or less)**
An open-source testing tool that enables testing your distributed system with distributed traces.
No more writing test scripts or mocks. Instead, test against real data.
Get a 10x reduction in test creation time, and a 20x reduction in troubleshooting time.

**Name of your relevant product(s) or service for the OpenSearch audience**
Tracetest

**What OpenSearch technologies do you specialize in**
Observability & Testing

**Type of business**
Open-source product

**Home/main office location or address**
Remote

**How can people contact you (email and phone)**
ken@kubeshop.io or adnan@kubeshop.io

**Regions you serve**
Global

**Industry specialization**
Software and technology

**Logo**
![Tracetest_logo_stacked_color-for-light-bgnd](https://user-images.githubusercontent.com/15029531/235141472-e1742551-ffb0-446a-a6ab-f3dae90da543.png)

**Additional image**
![demo tracetest io_test_mnOkKCLVR_run_39_test](https://user-images.githubusercontent.com/15029531/235141776-2115c579-bf66-4f36-8151-34bfcd4429e6.png)

**Links**
- [github/kubeshop/tracetest](https://github.com/kubeshop/tracetest)
- [Observability and Trace-based Testing in AWS](https://tracetest.io/blog/observability-trace-based-testing-aws-serverless-opensearch-tracetest)
- [Enabling Tracetest to Work Directly with OpenSearch](https://tracetest.io/blog/tracetest-opensearch-integration)
- [Sample Node.js App with OpenSearch, OpenTelemetry and Tracetest](https://docs.tracetest.io/examples-tutorials/recipes/running-tracetest-with-opensearch)
- [Configure Tracetest to Use OpenSearch as a Trace Data Store](https://docs.tracetest.io/configuration/connecting-to-data-stores/opensearch)

**Comment by adnanrahic** [comment]
Hi @pajuric! Thanks for giving us a nudge at KubeCon Europe to jump on updating the partner info. If I missed some info you need, please let me know.

cc @kdhamric

**Comment by pajuric** [comment]
@adnanrahic - Thank you for your submission. We'll get on developing your page.

**Comment by adnanrahic** [comment]
I see the page is live!
https://opensearch.org/partners/tracetest.html

Thanks a lot for the quick turnaround @pajuric ! 😄 

Should we close this issue?

**Comment by nateynateynate** [comment]
Yes, sorry about the three week delay. You're indeed live! 

Closing, re: #1554
