### ISSUE TITLE
[Public Key Changes] Adding reminder text on key verification page about the annual key renewal

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/project-website#1562]
Hi,

Per this issue: 
* https://github.com/opensearch-project/opensearch-build/issues/2136

We have created a new public key for the year.

Last year we add these text on this page: https://opensearch.org/verify-signatures.html

`Note: On 2022-05-11, the existing public key expired. If used, you will see “gpg: Note: This key has expired!” as noted in Issue 2040. Please download the new key which we have extended to 2023-05-12.`

We want to add the same for the year. Or just tweak the text as this new key can verify all the previous signatures and also enabled SHA512 hash to support RHEL9 + servers on RPM installations.

We plan to update the key on 2023-05-11 and the new key will expire on 2024-05-12.

Thanks.

**Comment by krisfreedain** [comment]
https://opensearch.org/verify-signatures.html now updated via https://github.com/opensearch-project/project-website/pull/1567 

@peterzhuamazon has pushed out new key as well. Closing.
