### ISSUE TITLE
[blog]Demystifying Anomaly Detection

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#1571]
**Describe the blog post your would like to write**

This will be a recap and narrative format of the session I'll be giving at OSSNA. It's good material, no reason we can't share it here.

**What is the title of the blog post?**

"Demystifying Anomaly Detection"

**Who are the authors?**
nateboot

**What is the proposed posting date?**

2023-05-06

**Comment by pajuric** [comment]
@nateynateynate  - Please provide an update and new publish date if you plan to move this forward.

**Comment by pajuric** [comment]
I am going to close this one out.
