### ISSUE TITLE
[Blog] OpenSearch Project Newsletter Volume 1, Issue 4

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#1572]
**Describe the blog post your would like to write**
Monthly OpenSearch Project newsletter

**What is the title of the blog post?**
OpenSearch Project Newsletter Volume 1, Issue 4

**Who are the authors?**
@pajuric @jhmcintyre 

**What is the proposed posting date?**
5/20/23

**Comment by krisfreedain** [comment]
closed with https://github.com/opensearch-project/project-website/pull/1679
