### ISSUE TITLE
[Release] Data Prepper 2.3.0 release

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/project-website#1585]
Data Prepper will release 2.3.0 on Jun 06, 2023.

We will need support on:

- [ ] Downloads page update on website
- [ ] Slack announcement
- [ ] Forum announcement
- [ ] Social media announcements

**Comment by dlvenable** [comment]
We have rescheduled the release date to Jun 06, 2023.

**Comment by krisfreedain** [comment]
Thanks for the heads-up @dlvenable 
I've added myself, @nateynateynate, & @dtaivpp as assignee's to keep this on our radar
