### ISSUE TITLE
Improved durability in OpenSearch with Remote Store

### ISSUE THREAD

**Issue by nandi-github** [opensearch-project/project-website#1587]
**Describe the blog post your would like to write**
A clear and concise description of what subject the blog post will cover.

**What is the title of the blog post?**
Improved durability in OpenSearch with Remote Store

**Who are the authors?**
Who will be listed as the authors of this blog post
Satish Nandi, Sachin Kale

**What is the proposed posting date?**
Provide the date which you wish this post to go live

We like to get this blog at the time of 2.8 release or immediately after.

**Comment by pajuric** [comment]
@nandi-github - please provide update on when you think this will be ready for publishing.

**Comment by nandi-github** [comment]
The feature release is moved to 2.9. So we will align with the 2.9 dates.

**Comment by pajuric** [comment]
@rohin - Please confirm that this blog is on track for 8/30, as Satish has asked that I transfer it over to you.

**Comment by pajuric** [comment]
@rohin - Checking on the status here and when you will have a draft. Please advise.

**Comment by pajuric** [comment]
Closing this out.
