### ISSUE TITLE
Upgrade FAQ to include renaming of kibana.yml to opensearch_dashboards.yml

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/project-website#161]
Update the FAQ for upgrading to OpenSearch to include migrating their config name from kibana.yml --> opensearch_dashboards.yml [[potentially here](https://opensearch.org/faq/#q3.1)].

For OpenSearch Dashboards, we went through a renaming strategy that replaced kibana.yml to [opensearch_dashboards.yml](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/config/opensearch_dashboards.yml). Without renaming their config, a customer's application might not function the way they expect or if they only have kibana.yml then the application may not start at all.

I recommend that customer's create a backup copy of their config and then rename kibana.yml to opensearch_dashboards.yml. They should be safe to keep all the config keys the same even though we deprecate the original name. It will just show a warning about the deprecated key and what the new key should be, but will still accept and apply the values.

The instructions could simply be:
> Please create a backup of your kibana.yml file and rename the file to opensearch_dashboards.yml. Warning: some configurations have been deprecated but will still be applied.

**Comment by dblock** [comment]
We really want to have docs for this and avoid duplicating content. How about pointing that FAQ to the said docs? @aetter where would that be?

**Comment by tmarkley** [comment]
@kavilla do we have a list of the configurations that have been deprecated, and are we documenting that explicitly?

I think we should have this ready for v1.0.0. Does the Dashboards team need to add these details to our release notes (this can be a link to avoid duplication) as well as the website?

**Comment by stockholmux** [comment]
My 2 cents here: Keep the FAQ high level - if we need to throw a link to the documentation for nitty-gritty then we can do that.

**Comment by tmarkley** [comment]
@stockholmux I think that makes sense. We discussed creating an `UPGRADING.md` file in the Dashboards repo that we could link to from the FAQ, release notes, etc. Are there better alternatives anyone else was considering?

**Comment by aetter** [comment]
Best option is in this section: https://docs-beta.opensearch.org/upgrade-to/, which will likely be https://opensearch.org/docs/upgrade-to/ post-launch.

I'll add a page and tag everyone here for review. Do we have a macOS test build available? I can fire up a WorkSpace or something, but obviously local testing is more convenient.

**Comment by stockholmux** [comment]
It looks like we're taking care of this on the docs website only.

@aetter @tmarkley @kavilla @dblock - thoughts?

**Comment by aetter** [comment]
@stockholmux Yep, as far as I know, this is done and can be closed out here. https://opensearch.org/docs/upgrade-to/dashboards-upgrade-to/

Side note: I don't like the notion of renaming kibana.yml and didn't recommend it; if you want to start using the security plugin, you need to merge kibana.yml and opensearch_dashboards.yml, and it's not like copying and pasting one into the other is significantly harder than renaming and moving.

**Comment by stockholmux** [comment]
OK. I'm going to close this out. If anyone disagrees, reopen. 

@aetter The you don't like the idea of a _renamed_ `kibana.yml` or the _renaming_ `kibana.yml` to `opensearch_dashboards.yml`?
