### ISSUE TITLE
OpenSearch Hadoop Connector Blog

### ISSUE THREAD

**Issue by mnkugler** [opensearch-project/project-website#1621]
**Describe the blog post your would like to write**
The details behind the release of OpenSearch Hadoop Connector with SigV4 and how to use it 

**What is the title of the blog post?**
Release of OpenSearch Hadoop Connector

**Who are the authors?**
Vamsi, Nick

**What is the proposed posting date?**
June 2

**Comment by pajuric** [comment]
Closing this out. Please reopen if this plans to go forward.
