### ISSUE TITLE
There is a typo in the blog post

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#1622]
**Describe the bug**
On this site, there is a typo
https://opensearch.org/blog/q1-survey-results/
The sentence should read: Users identified with four roles in OpenSearch and the extra four roles in the sentence needs to be remove

**To Reproduce**

**Expected behavior**
The typo needs to be fixed

**Plugins**
Please list all plugins currently enabled.

**Screenshots**
!
![image (2)](https://github.com/opensearch-project/project-website/assets/83674419/b4667597-040c-46be-8222-1e0ae8fee61c)

**Host/Environment (please complete the following information):**
 - Version: [e.g. 22]
 - Browsers: [e.g. Chrome, Safari]
 - Browser Version: [e.g 93.0.4521.12]

**Additional context**

**Comment by nateynateynate** [comment]
Solved with PR #1629
