### ISSUE TITLE
06 Take Part in the Q2 Quarterly Survey 

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#1634]
**Describe the blog post your would like to write**
We want to encourage users to take part in the quarterly survey and we are offering a mug in appreciation of their time

**What is the title of the blog post?**
Take Part in the Q2 Quarterly Survey

**Who are the authors?**
Aparna Sundar

**What is the proposed posting date?**
5/30/2023

**Comment by krisfreedain** [comment]
@apasun - this is the forum post, isn't it?
