### ISSUE TITLE
Tool for monitoring and alerting on OpenSearch logs

### ISSUE THREAD

**Issue by radu-gheorghe** [opensearch-project/project-website#1697]
[**Link**](https://sematext.com/docs/integration/opensearch-logs/)

**Description**
[Sematext Cloud](https://sematext.com/cloud/) can now parse and visualize OpenSearch logs out of the box, as well as metrics. Besides the typical operational use, this feature makes for an easy migration to OpenSearch (most commonly, from Elasticsearch).

**Original Publish Date**
2023-06-14

**Are you the author?**
No, it's a collegue of mine, @cpipilas. I did the integration. We're all excited to be OpenSearch partners over here!

**Comment by krisfreedain** [comment]
@radu-gheorghe - thank you! Is this for inclusion in the next newsletter?

**Comment by radu-gheorghe** [comment]
You're welcome. Yes, that was the aim.

**Comment by pajuric** [comment]
@radu-gheorghe - Added to our newsletter scheduled to go out the week of 7/24.

**Comment by radu-gheorghe** [comment]
Thanks so much, @pajuric!

**Comment by otisg** [comment]
@pajuric if this was included then maybe this can be closed now.  Hvala.
