### ISSUE TITLE
[Blog] Search Pipelines

### ISSUE THREAD

**Issue by macohen** [opensearch-project/project-website#1715]
**Describe the blog post you would like to write**
A walkthrough of Search Pipelines, the search processors that exist, how you can build your own, and what we see coming for Search Pipelines in the future. 

**What is the title of the blog post?**
TBD

**Who are the authors?**
msfroh@ kolchfa@

**What is the proposed posting date?**
2023-07-31

**Comment by pajuric** [comment]
@msfroh  Checking in and seeing if this is still on tap to go out in the next week?

**Comment by pajuric** [comment]
@msfroh @macohen - Is there any update on when the content will be ready for review for this blog?

**Comment by msfroh** [comment]
Probably not until the end of September at this rate.

**Comment by pajuric** [comment]
@msfroh - Looking for an update on the draft and when it might be ready for review.

**Comment by msfroh** [comment]
> @msfroh - Looking for an update on the draft and when it might be ready for review.

Still no progress. I've been busy with other work. It's still on my backlog to be picked up.

**Comment by pajuric** [comment]
@msfroh - Checking to see if you still plan to go forward with this blog?
