### ISSUE TITLE
Publish JDBC driver 1.3.0 on the website

### ISSUE THREAD

**Issue by GumpacG** [opensearch-project/project-website#1721]
**Is your feature request related to a problem? Please describe.**
An up to date download link is required for Tableau submission to be included on Tableau's gallery. A JDBC v1.3.0 has been released however only 1.1.0.1 is on the[ website](https://opensearch.org/downloads.html#:~:text=Download-,JDBC%20Driver,-The%20Java%20Database).

**Describe the solution you'd like**
The download link should point to https://artifacts.opensearch.org/opensearch-clients/jdbc/opensearch-sql-jdbc-1.3.0.0-shadow.jar.

**Additional context**
Release issue: https://github.com/opensearch-project/opensearch-build/issues/3614

**Comment by wbeckler** [comment]
The link is now 1.4. Closing.
