### ISSUE TITLE
Canonical in Partner Page

### ISSUE THREAD

**Issue by michtabirao** [opensearch-project/project-website#1725]
**Organization name**
Canonical

**Brief description of your business and what it does (50 words or less)**
Canonical is the publisher of Ubuntu, the OS for most public cloud workloads as well as the emerging categories of smart gateways, self-driving cars and advanced robots. Canonical provides enterprise security, support and services to commercial users of Ubuntu. 

On the data solutions front, Canonical provides consulting, support, security and managed services for data technologies, such as PostgreSQL®, MySQL®, Apache Kafka®, Apache Spark®, MongoDB®, Redis® and OpenSearch®, on any cloud.

Established in 2004, Canonical is a privately held company.

**Name of your relevant product(s) or service for the OpenSearch audience**
At Canonical, we love open source projects. So we started projects  for OpenSearch – ready for community usage, contribution and support:

- Charmed OpenSearch® Snap
The Snap is an easy to use and secure OpenSearch® software package that can be used in any Linux environment.

- Charmed OpenSearch® OCI image
An OCI image with advanced security and trust features.

- Charmed OpenSearch®  IAAS Operator
The Charmed OpenSearch Infrastructure as a Service (IAAS) operator is used for automating the deployment, management, and orchestration of OpenSearch clusters on any Infrastructure as a Service (IaaS) cloud – including private clouds.

**What OpenSearch technologies do you specialize in**
Canonical provides OpenSearch® consulting, support and security maintenance. 

**Type of business**
- Product/ technology 
- Professional services 

**Home/main office location or address**
4th Floor,
201 Borough High Street
London SE1 1JA
United Kingdom

**How can people contact you (email and phone)**
Americas +1 737 204 0291
Rest of World +44 203 656 5291
[Contact Form](https://ubuntu.com/data/opensearch#get-in-touch)

**Regions you serve**
Global

**Industry specialization**
Canonical provides OpenSearch® consulting, support, and security maintenance.

**Logo**
[Canonical logo](https://opensearch.org/assets/media/partners/canonical.png)

**Links**
https://snapcraft.io/opensearch 
https://charmhub.io/opensearch 
https://ubuntu.com/data/opensearch 
https://github.com/canonical/opensearch-operator 
https://github.com/canonical/charmed-opensearch-rock
https://github.com/canonical/opensearch-snap

**Comment by pajuric** [comment]
@michtabirao - Thank you for submitting the information, Michelle.

**Comment by pajuric** [comment]
@astephanus - New page to create.

**Comment by astephanus** [comment]
@pajuric I will create it.

**Comment by krisfreedain** [comment]
closed with https://github.com/opensearch-project/project-website/pull/1736 - thank you @michtabirao & @astephanus
