### ISSUE TITLE
Tech deep dive on vector search

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#1728]

**Comment by pajuric** [comment]
@vamshin - Please update the blog issue, as it is missing key info. I converted it to this repository, but it appears it may have been opened elsewhere?

**Comment by pajuric** [comment]
@vamshin - Is it fair to assume that this is the same blog and it was published on the AWS side of the house here: https://aws.amazon.com/blogs/big-data/amazon-opensearch-services-vector-database-capabilities-explained/.

**Comment by vamshin** [comment]
@pajuric thats right. Can we create like a parter blog?

**Comment by pajuric** [comment]
Closing this blog. Please reopen if you decided to move this forward at some point.

**Comment by pajuric** [comment]
Closing this out
