### ISSUE TITLE
Updates and Corrections Needed in FAQs

### ISSUE THREAD

**Issue by ahopp** [opensearch-project/project-website#173]
There are some updates needed in the FAQs. 

- [x] In FAQ 1.19, "How do I contribute functionality and get it on the public roadmap?", the proposal template link is dead.
- [x] In FAQ 1.10, the compatibility documentation link should go to this [link](https://docs-beta.opensearch.org/clients/agents-and-ingestion-tools/index/#compatibility-matrices).
- [x] In FAQ 3.23 and 3.25, there is a typo: "please open **and** issue in OpenSearch."
- [x] In FAQ 1.1, there is a typo: "OpenSearch includes OpenSearch (derived from Elasticsearch 7.10.2) and OpenSearch Dashboards (derived from Kibana 7.1**0.2).OpenSearch** is the new home for the plugins and advanced features distributed with Open Distro for Elasticsearch."
- [x] FAQ 1.6 should probably link to the updated partners page. 

Lastly, FAQ 1.4 ("Is OpenSearch suitable for production use?") should be updated to reflect GA once released.

**Comment by stockholmux** [comment]
1.4 is still pending until GA is actually launched.

**Comment by elfisher** [comment]
makes sense. Can we link this to the 1.0 announcement PR since it is related?

**Comment by stockholmux** [comment]
We can close this now! :insert party emoji:
