### ISSUE TITLE
Telicent Partner Info

### ISSUE THREAD

**Issue by jnioche** [opensearch-project/project-website#1734]
**Organization name**
Telicent Ltd

**Brief description of your business and what it does (50 words or less)**

Telicent is a software start-up building a super-secure platform to enable rapid innovation and digital transformation. Our CORE platform is open source, and lets you innovate with your own data in a secure way - try out new tools, new ideas, new start-ups. Safely. 

**Name of your relevant product(s) or service for the OpenSearch audience**

We will progressively be offering our CORE platform as open-source. The search element of it is provided by OpenSearch.
We also wrote an [open source plugin for OpenSearch to facilitate the use of Synonyms](https://github.com/Telicent-io/telicent-opensearch), this is available to all in the community.

**What OpenSearch technologies do you specialize in**

We specialise in search, observability and security.

**Type of business**
Telicent is an Independent Software Vendor 

**Home/main office location or address**
London, UK

**How can people contact you (email and phone)**
opensource@telicent.io

**Regions you serve**
Worldwide

**Industry specialization**
Energy and utilities, financial services, healthcare, public sector, non-profit, software and technology

**Logo**
<img width="100" alt="telicent" src="https://github.com/opensearch-project/project-website/assets/218319/f68f83ba-f0fa-4b92-9e36-2b4f55f0ef99">

**Additional image**

**Links**
https://github.com/Telicent-io/telicent-opensearch
https://telicent.io

**Comment by krisfreedain** [comment]
Thanks @jnioche - live on the site now https://github.com/opensearch-project/project-website/pull/1737
