### ISSUE TITLE
Update OpenSearchCon CFP Blog Post

### ISSUE THREAD

**Issue by dimwetoth** [opensearch-project/project-website#1738]
**Describe the blog post your would like to write**
We need to edit the existing CFP blog post for OpenSearchCon here: [https://opensearch.org/blog/call-for-presentations-bring-your-ideas-to-opensearchcon-2023](https://opensearch.org/blog/call-for-presentations-bring-your-ideas-to-opensearchcon-2023)

**What is the title of the blog post?**
OpenSearchCon 2023: CFP is Now Closed

**Who are the authors?**
No change in authors

**What is the proposed posting date?**
Don't change the publish date

**What is the text change needed?**
Please leave the image at the bottom.  Replace the entire rest of the body copy with the following:

### The Call for Presentations window for OpenSearchCon 2023 is now closed.

There were more submissions than expected, and our panelists have a lot of great ideas to look through. Our community-led judges are busy scoring, sorting and categorizing the submissions and will be in touch with all of you within the next couple of weeks with results.

If you end up getting a speaking slot, we look forward to working with you at the conference. If you don’t, you’ll be put on a wait list for cancellations and other presenting opportunities. 

Thanks to the entire community for showing such enthusiasm in our core topics of search, analytics, generative AI, and open-source citizenship! You can stay on top of the latest conference news by visiting our [OpenSearchCon Website](https://opensearchcon2023.splashthat.com/) - and remember to register for the conference if you haven’t already.

We'll see you in Seattle in September!

**Comment by krisfreedain** [comment]
@nateynateynate can you check this out? thanks
