### ISSUE TITLE
Update OpenSearchCon Blog post with correct CFP information

### ISSUE THREAD

**Issue by dimwetoth** [opensearch-project/project-website#1744]
**Describe the blog post your would like to write**
This will be an update to the existing OpenSearchCon blog post here: 

**What is the title of the blog post?**
No change in Title

**Who are the authors?**
No author changes required

**What is the proposed posting date?**
Please leave the original posting date intact

**What are the required corrections to this blog post?**

1. Please remove the following paragraph:
The Call for Papers is still open as well but only until the end of the day on June 16. If you have a story you’d like to share, submit your talk NOW on the [Call for Presentations](https://airtable.com/shrVZLtXJ2d1cI6pT) site - time is of the essence!

Easy.

**Comment by krisfreedain** [comment]
@nateynateynate can you check this one out? thanks

**Comment by nateynateynate** [comment]
Resolved. Closing. Forgive my tardiness.
