### ISSUE TITLE
OpenSearch talks to Community Contributors in HayStack and Berlin Buzzwords to Create a Persona Framework for Search

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#1745]
**Describe the blog post your would like to write**
The topic of the blog are OpenSearch personas and how we talked to the community to help establish a framework for Search Personas

**What is the title of the blog post?**
OpenSearch talks to Community Contributors in HayStack and Berlin Buzzwords to Create a Persona Framework for Search

**Who are the authors?**
Aparna Sundar 

**What is the proposed posting date?**
July 21st

**Comment by hdhalter** [comment]
Closing since this blog is published.
