### ISSUE TITLE
Logit.io Partner Information

### ISSUE THREAD

**Issue by Ebennetteng** [opensearch-project/project-website#1750]
Logit.io partner information
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Logit.io Ltd**
Please let us know the exact business name

**Logit.io offers a comprehensive observability and data analysis solution that enables businesses to enhance their cloud observability. By providing users with a unified and reliable data analysis solution, the platform facilitates scalability.**
A clear and concise description of your business.

**Hosted OpenSearch, SIEM as a Service and Prometheus as a Service**
A clear and concise description of your product(s) and/or services offered to the OpenSearch community.

**Observability, Security**
Is there an area of the project where your business specializes?
(e.g., search, analytics, observability, security, or other)

**SaaS Platform and Managed Services**
(e.g., MSP, CSP, ISV, product/technology, services organization, other). If other, please define.
This will inform the community how they can expect to use your product(s) and services.

**76 Manchester Road, Denton, Manchester, United Kingdom, M34 3PS**
Home/main office location or address (if applicable)

**sales@logit.io**
email/phone (if applicable)

**North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia**
(e.g., North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia)
What regions of the world do you serve?

**Public sector and government, manufacturing, telecoms, financial services, logistics, retail, e-commerce, media and entertainment, healthcare.**
(e.g. business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology)? Add all that apply.

**[Logo](https://logowik.com/content/uploads/images/logitio5656.jpg)**
Please upload a company logo

**[Additional image](https://logit.io/images/solution-pages/kiboverview.png)**
Attach any additional image you would like to provide that showcases your business (product, technology, offices)

**[Links](https://logit.io/blog/post/opensearch-dashboard-examples/)(https://logit.io/blog/post/aws-elasticsearch-vs-opensearch/)(https://logit.io/blog/post/data-visualisation-tools/)**
Add links to your last three blogs that are relevant for the OpenSearch Project audience.

**Comment by krisfreedain** [comment]
thanks @Ebennetteng 
new partner page to build out @astephanus
