### ISSUE TITLE
Improving Partner Profile

### ISSUE THREAD

**Issue by KenLedyard** [opensearch-project/project-website#1764]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Please let us know the exact business name
•	Improving

**Brief description of your business and what it does (50 words or less)**
A clear and concise description of your business.
•	Improving revolutionizes the digital landscape, providing cutting-edge IT consulting, dynamic software development, and comprehensive agile training globally. Our trailblazing solutions empower our clients to conquer tactical and strategic goals, propelling them to unparalleled success in a relentlessly competitive and ever-evolving market. Join us on the journey to unprecedented heights.

**Name of your relevant product(s) or service for the OpenSearch audience**
A clear and concise description of your product(s) and/or services offered to the OpenSearch community.
•	Improving is the leading IT consulting and software engineering company in North America. We help enterprises and organizations solve their most complex technology challenges through modern software development, technology consulting, agile training, and team augmentation services. Whether your business needs to understand the impact of a new initiative, deploy a new application, or partner with a trusted firm that can assimilate into your team, Improving is here to help! We are dedicated to educating and supporting your business each step of the way.

**What OpenSearch technologies do you specialize in**
Is there an area of the project where your business specializes?
(e.g., search, analytics, observability, security, or other)
•	Analytics, Observability

**Type of business**
(e.g., MSP, CSP, ISV, product/technology, services organization, other). If other, please define.
This will inform the community how they can expect to use your product(s) and services.
•	System Integrator, Professional Services, CSP, ISV, Training 
![Improving-Logo (1)](https://github.com/opensearch-project/project-webs
[Improving Image.pdf](https://github.com/opensearch-project/project-website/files/12004753/Improving.Image.pdf)
ite/assets/136840584/ab8d6efe-54e4-4b60-a010-0ac247335d06)

**Home/main office location or address**
Home/main office location or address (if applicable)
•	Headquarters:
•	Improving – 5445 Legacy Drive Suite 100 Plano, TX 75024
•	Additional Office Locations – (US, Canada, Mexico) [Our Locations | Improving](https://improving.com/company/locations/)

**How can people contact you (email and phone)**
email / phone (if applicable)
•	Kyle Porter email: [Kyle.Porter@improving.com](mailto:Kyle.Porter@improving.com)  - phone: 604-441-7318

**Regions you serve**
(e.g.,North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia)
What regions of the world do you serve?
•	North America

**Industry specialization**
(e.g. business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology)? Add all that apply.
•	All

**Logo**
Please upload a company logo
(attached)

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)
(attached)

**Links**
Add links to your last three blogs that are relevant for the OpenSearch Project audience.
•	__Note that none of these specifically reference Improving, but we did all of them:__
•	[ttps://opensearch.org/blog/sql-search-relevance-selective-aggregation-and-window-functions-in-OpenSearch/](https://opensearch.org/blog/sql-search-relevance-selective-aggregation-and-window-functions-in-OpenSearch/)
•	https://www.linkedin.com/posts/ianirudha_opensearch-otel-observability-activity-7069920836727574529-0GgC/?utm_source=share&utm_medium=member_desktop
•	https://opensearch.org/blog/feature-deep-dive-opensearch-sql-basic-queries/

**Comment by pajuric** [comment]
@KenLedyard - Thank you for adding your page content.

**Comment by pajuric** [comment]
@astephanus - page content is ready for you.

**Comment by astephanus** [comment]
@pajuric I'm on it.

**Comment by astephanus** [comment]
@pajuric FYI there is a malformation in the Issue description here:

> ![Improving-Logo (1)](https://github.com/opensearch-project/project-webs
[Improving Image.pdf](https://github.com/opensearch-project/project-website/files/12004753/Improving.Image.pdf)
ite/assets/136840584/ab8d6efe-54e4-4b60-a010-0ac247335d06)

This made it difficult, but not impossible to suss out the logo and the product image. Somehow the Markdown "[Improving Image.pdf](https://github.com/opensearch-project/project-website/files/12004753/Improving.Image.pdf)" got inserted into the URL for the logo. The correct text that will allow for identifying / locating both is:
`![Improving-Logo (1)](https://github.com/opensearch-project/project-website/assets/136840584/ab8d6efe-54e4-4b60-a010-0ac247335d06)`
And
`[Improving Image.pdf](https://github.com/opensearch-project/project-website/files/12004753/Improving.Image.pdf)`

I do not have permissions to modify the issue itself or I would make the change.
