### ISSUE TITLE
OpenSearch Speed Improvements

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/project-website#1824]
**Describe the blog post your would like to write**
There have been several speed-oriented improvements for OpenSearch in the past three releases. This blog post will summarize what the improvements are, where the most impact has been, how to take advantage of the improvements, and what might be coming next

**What is the title of the blog post?**
OpenSearch Speed Improvements

**Who are the authors?**
Monica Kugler, Bill Beckler, Prabhakar Sithanandam

**What is the proposed posting date?**
August 25, 2023

**Comment by pajuric** [comment]
Thanks for the contribution, @wbeckler
