### ISSUE TITLE
Spot by NetApp

### ISSUE THREAD

**Issue by spunredd-netapp** [opensearch-project/project-website#1835]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Spot by NetApp

**Brief description of your business and what it does (50 words or less)**
Spot by NetApp helps companies get the most out of their cloud investments. Our CloudOps portfolio helps customers securely and reliably deploy, operate and scale applications and infrastructure in the cloud.

**Name of your relevant product(s) or service for the OpenSearch audience**
Spot by NetApp provides a fully managed and hosted service for OpenSearch on your cloud provider of choice under the Apache 2.0 License. Spot also encompass Infrastructure optimization, Management of Cloud Costs, Managed Service for Open Source distributed data platforms,  and Infrastructure Security.

**What OpenSearch technologies do you specialize in**
Is there an area of the project where your business specializes?
Fully managed and hosted OpenSearch service, Configure through the Spot SaaS platform, Spot API or Terraform, 24x7 Expert support, SOC 2, PCI Private Network and PrivateLink enabled, Built-in monitoring, 99.999% SLA, Run in your cloud provider account or ours

**Type of business**
(e.g., MSP, CSP, ISV, product/technology, services organization, other). If other, please define.
A combination of MSP, Product, and Services.

**Home/main office location or address**
3060 Olsen Drive
San Jose, CA 95128

**How can people contact you (email and phone)**
email / phone (if applicable)
Phone: +1 408 822 6000
Email: info@spot.io
https://spot.io/contact/

**Regions you serve**
(e.g.,North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia)
What regions of the world do you serve?
North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia

**Industry specialization**
(e.g. business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology)? Add all that apply.
software and technology

**Logo**
Please upload a company logo
/assets/media/partners/spot/spot.png

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
Add links to your last three blogs that are relevant for the OpenSearch Project audience.
https://www.instaclustr.com/blog/opensearch-feature-update/
https://www.instaclustr.com/blog/opensearch-2-now-in-preview-release/
https://www.instaclustr.com/blog/instaclustr-updates-nodes-types-for-opensearch-offering/

**Comment by pajuric** [comment]
@spunredd-netapp - Thank you for creating your partner page.

**Comment by pajuric** [comment]
@astephanus

**Comment by astephanus** [comment]
> @astephanus

I am on it

**Comment by krisfreedain** [comment]
Done! thanks all
