### ISSUE TITLE
Dashboard usability study

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#1839]
**Describe the blog post your would like to write**
Keylime Interactive conducted a usability study with dashboard users in Q1/2 of 2023. We would like to share insights of findings in a blog and also initiate GitHub issues to motivate ongoing dashboards improvements. This blog helps share findings. 

**What is the title of the blog post?**

OpenSearch Dashboards: A Snapshot of the Current Usability and Inclusivity Index 

**Who are the authors?**
Aparna Sundar snd Ashwin PC

**What is the proposed posting date?**
August 11th

**Comment by pajuric** [comment]
Is there an updated target send date for this one, @apasun?

**Comment by apasun** [comment]
@vagimeli -can you update the publication date to "9/6/2023" https://opensearch.org/blog/dashboards-usability-snapshot/
