### ISSUE TITLE
[BUG] Page with old info needs taken down

### ISSUE THREAD

**Issue by dimwetoth** [opensearch-project/project-website#1840]
**Describe the bug**
There is an out of date page that we should just take down.

**To Reproduce**
Go to this page: [(https://opensearch.org/OpenSearchCon2023.html)]

**Additional context**
We have a conference site now, and there is no reason for this page to steal search juice from the conference site.

**Comment by krisfreedain** [comment]
@dimwetoth would it be better to update it with all the relevant links? It's just a 'save the date' currently - maybe links to the registration page, and hotel page so more people find them?

**Comment by krisfreedain** [comment]
Didn't hear back so I've updated the site with correct dates and links over to registration and hotel booking. Closing for now but feel free to reopen if further discussion needed.
