### ISSUE TITLE
Lucene Byte Sized Vector

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/project-website#1853]
**Describe the blog post your would like to write**
This post will focus on a new feature that we have introduced in the OpenSearch 2.9.0 which is the Lucene Byte Sized Vector. Using this feature, users can index and query documents as k-NN byte vectors (vectors of type k-NN vector field type within the byte range [-128 to 127]) using Lucene engine. When compared to the float vectors, byte vectors helps to optimize the memory and storage used. Also, improves the indexing throughput and reduces the query latencies without losing much precision on the recall.

For the users to use this feature, they need to provide the vectors within the byte range. To convert a float vector to byte vector without losing much recall, these vectors needs to be quantized using a good quantization technique suitable for the data that we are using. So, in this post we will also mention the significance of it to get a good recall. Also, we will compare and discuss the benchmarking results obtained for some of the datasets using both float and byte vectors.

**What is the title of the blog post?**
Byte Quantized Vectors in Lucene

**Who are the authors?**
Naveen Tatikonda, Vamshi Vijay Nakkirtha, Stavros Macrakis, Tal Wagner

**What is the proposed posting date?**
08/31/2023

**Comment by pajuric** [comment]
@naveentatikonda - Just checking to see if this is "in progress" and when you might have a draft for the tech writers to review.

**Comment by naveentatikonda** [comment]
@pajuric I prepared a draft version of it and it is under review by my internal team. Once it is done, we can get it reviewed by tech writers. Will update you once it is ready for review. Thanks!

**Comment by naveentatikonda** [comment]
@pajuric I shared the link to quip doc in Asana thread. Please review it
