### ISSUE TITLE
ElastiFlow

### ISSUE THREAD

**Issue by dllayman** [opensearch-project/project-website#1864]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Please let us know the exact business name - **ElastiFlow Inc.**

**Brief description of your business and what it does (50 words or less)**
A clear and concise description of your business. - **Network Performance and Security Analytics for Open Data Platforms.  The most complete network observability solution for use with modern data platforms providing unprecedented insights at any scale.**

**Name of your relevant product(s) or service for the OpenSearch audience**
A clear and concise description of your product(s) and/or services offered to the OpenSearch community. - **Unified Flow Collector - NetFlow solution for scalable flow record processing leveraging open data platforms and Unified SNMP Collector - SNMP telemetry solution for seamless device monitoring, minimal bandwidth impact, with dynamic response to changes leveraging open data platforms.**

**What OpenSearch technologies do you specialize in**
Is there an area of the project where your business specializes?
(e.g., search, analytics, observability, security, or other) - **Analytics, Observability, and Security**

**Type of business**
(e.g., MSP, CSP, ISV, product/technology, services organization, other). If other, please define.
This will inform the community how they can expect to use your product(s) and services. **Product/Technology**

**Home/main office location or address**
Home/main office location or address (if applicable) ElastiFlow Inc. Oakland, California USA

**How can people contact you (email and phone)**
email / phone (if applicable) **info@elastiflow.com**

**Regions you serve**
(e.g.,North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia)
What regions of the world do you serve? - **North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia**

**Industry specialization**
(e.g. business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology)? Add all that apply. - **business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology**

**Logo**
Please upload a company logo - 
![logo-name-inline-black-text](https://github.com/opensearch-project/project-website/assets/141955900/51257591-7a1e-4da4-9db1-9ed745855e03)

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
Add links to your last three blogs that are relevant for the OpenSearch Project audience.
https://www.elastiflow.com/blog/posts/detecting-tcp-flag-based-attacks-with-elastiflow

**Comment by pajuric** [comment]
@astephanus - New partner page

**Comment by astephanus** [comment]
> @astephanus - New partner page

I am on it.

**Comment by krisfreedain** [comment]
Done! Thanks all
