### ISSUE TITLE
[Blog] Improved Hybrid Search relevancy with Normalized score combination 

### ISSUE THREAD

**Issue by vamshin** [opensearch-project/project-website#1872]
**Describe the blog post your would like to write**
Hybrid Search with Normalized score combination feature makes the existing hybrid search approach more performant by combining scores lexical score(BM25) and vector score on different scales. More details in RFC https://github.com/opensearch-project/neural-search/issues/126

**What is the title of the blog post?**
Hybrid Search with Normalized score combination 

**Who are the authors?**
Who will be listed as the authors of this blog post
TBD

**What is the proposed posting date?**
Provide the date which you wish this post to go live

**Comment by pajuric** [comment]
Hi @vamshin - For the publishing timeframe, it's really up to you in regards to when you can provide a draft for editorial review. Once I have that date, I can create a work-back schedule for tech review, editorial, and then publishing.

**Comment by pajuric** [comment]
@vamshin Checking in to see how the blog writing is going and if you have a draft that is ready for review.

**Comment by vamshin** [comment]
@navneet1v is working on blog with Martin. Navneet please update the thread with the progress.
