### ISSUE TITLE
[BUG] Speaker record update - Jim Battenberg

### ISSUE THREAD

**Issue by dimwetoth** [opensearch-project/project-website#1879]
**Describe the bug**
Jim Battenberg's last name is spelled "Battenburg" in the speaker front-matter on our website. Also, there is no speaker picture (he hasn't provided yet but will soon), so let's tackle both of these in one record update.

**To Reproduce**
Go to Jim Battenburg's speaker profile, and notice that it should be spelled "Battenberg"
Note that there's no speaker picture up there

**Expected behavior**
Speaker name spelled correctly and picture displays.

**Comment by krisfreedain** [comment]
Spelling error is resolved. Still waiting on image.

**Comment by Dantochi** [comment]
I think the image has been added already... https://opensearch.org/events/opensearchcon/speakers/jim-battenberg.html
