### ISSUE TITLE
OpenSearchCon 2023 - Get a sneak peek inside

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#1884]
**Describe the blog post your would like to write**
Provides updates on everything we have planned for OpenSearchCon 2023. 

**What is the title of the blog post?**
OpenSearchCon 2023

**Who are the authors?**
@jhmcintyre @krisfreedain 

**What is the proposed posting date?**
August 23, 2023

**Comment by krisfreedain** [comment]
thanks @pajuric

**Comment by krisfreedain** [comment]
Reviewed and through editorial process - will create a PR and get this published

**Comment by krisfreedain** [comment]
resolved / published in https://github.com/opensearch-project/project-website/pull/1909
