### ISSUE TITLE
Importance of Accessibility in Visualizations

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#1906]
**Describe the blog post your would like to write**
This blog articulates accessibility considerations that can benefit our community, when it comes to visualizations. We had a free audit conducted for dashboards, and this blog will share what we found, how OpenSearch and our community can improve to address accessibility 

**What is the title of the blog post?**
Importance of Accessibility in Visualizations

**Who are the authors?**
apasun

**What is the proposed posting date?**
November 17th

**Comment by pajuric** [comment]
Adjusting the dates for this to early January.

**Comment by pajuric** [comment]
@apasun - please update blog date once you are back in the office.
