### ISSUE TITLE
Integrations for OpenSearch

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/project-website#1913]
**Describe the blog post your would like to write**
The integration initiative was envisioned as a simple, elegant and powerful way to allow users to view,  query and project their data.

The existing way that users could configure their dashboards, for example is to undergo the following process every time:

* Explore their index content and extract the structure - mapping file
* Assemble the index pattern based on this mapping 
* Create visualization for different parts of the mapping fields
* Compose the entire dashboard from these visualization
* Save the dashboard and allow export for other users to utilize (expecting the mapping to be the same)

The repeated bootstrap required for every single index is a log, error-prone and consuming process that requires some degree of knowledge both of the data and of the OpenSearch API.

At OpenSearch we are supporting many different type of use cases for a large variety of users:
 - Search related domain use cases - E-commerce products search for example
 - Observability monitoring and provisioning - Trace / Metrics analytics
 - Security Monitoring and Threats Analysis 

All these use cases are accompanied by a very strong and matured community that has contributed many resources and Knowledge to these domain.

One important concept of such contributions are the domain schema used by the data signal collected for such events (security /  observability).

**What is the title of the blog post?**
Integrations for OpenSearch

**Who are the authors?**
Lior Perry

**What is the proposed posting date?**
As early as possible

**Comment by pajuric** [comment]
Closing this since it's now dated.
