### ISSUE TITLE
[Blog] Optimize OpenSearch Refresh Interval

### ISSUE THREAD

**Issue by ev2900** [opensearch-project/project-website#1922]
**Describe the blog post your would like to write**

Adjusting the refresh interval of an OpenSearch index can improve indexing performance. This blog would be a clear and concise post explaining and demonstrating

* What is an refresh and refresh interval
* How does refresh frequency affect indexing performance 
* How to adjust the refresh interval for an index

I already have some of the material created for this blog post at [OpenSearch_Refresh_Interval](https://github.com/ev2900/OpenSearch_Refresh_Interval). Including a YouTube video - https://www.youtube.com/watch?v=8uyemEfgcY8&t=3s

I want to turn this into a OpenSearch blog post so it is easier for people to find this information.

**What is the title of the blog post?**

Optimize OpenSearch index refresh interval

**Who are the authors?**

[Christopher Sharkey](https://github.com/ev2900), [Samit Kumbhani](https://github.com/awssamit)
 

**What is the proposed posting date?**

September 13 but I am flexible on date. It shouldn't take me long write the post

**Comment by pajuric** [comment]
@ev2900 - Just checking in on the draft to see how it's coming. If you could provide an update here, I'd appreciate it.

**Comment by ev2900** [comment]
Hi @pajuric I wasn't sure if this idea was approved or now. It sounds like it is! 

I'll start the draft today. I should have it done in a few days.

**Comment by ev2900** [comment]
[Samit](https://github.com/awssamit) and I drafted the blog post in this [Google document](https://docs.google.com/document/d/1zpqX41kqtA6qoFQS0r66gs_2-mUgsu0epyrYBrfWpyU/edit?usp=sharing)

The share settings are configured so any one can comment. Please comment with any changes we should make. If anyone needs edit access you can request access.

**Comment by ev2900** [comment]
@pajuric just wanted to check in. [Samit](https://github.com/awssamit) and I finished the draft of the blog post in this [Google document](https://docs.google.com/document/d/1zpqX41kqtA6qoFQS0r66gs_2-mUgsu0epyrYBrfWpyU/edit?usp=sharing)

Please let me know if you want to do a technical review of the draft or if I should proceed directly to a pull request

**Comment by ev2900** [comment]
Pull request with the blog post content - [Content for Blog Post - Optimize OpenSearch Refresh Interval](https://github.com/opensearch-project/project-website/pull/2397)

**Comment by ev2900** [comment]
The blog post is live at - https://opensearch.org/blog/optimize-refresh-interval/ 

I am closing out this issue
