### ISSUE TITLE
CrafterCMS

### ISSUE THREAD

**Issue by russdanner** [opensearch-project/project-website#1923]
**Organization name**
CrafterCMS 

**Brief description of your business and what it does (50 words or less)**
CrafterCMS is the primary maintainer of the open source CrafterCMS project and sells commercial support, hosting, training, and consulting services for the CrafterCMS platform.

**Name of your relevant product(s) or service for the OpenSearch audience**
CrafterCMS is an open source Git-based headless CMS for enterprise-scale websites, portals, and apps that prioritizes ease of use for authors and composability, integration, scalability, performance, and security for developers and operations. 

CrafterCMS is natively integrated with OpenSeach. OpenSearch is leveraged to support content authoring and management activities and to support high-performance dynamic/query-driven content delivery, search, recommendation and personalization use cases.

**What OpenSearch technologies do you specialize in**
Is there an area of the project where your business specializes?
Search

**Type of business**
(e.g., MSP, CSP, ISV, product/technology, services organization, other). If other, please define.
product/technology

**Home/main office location or address**
7918 Jones Branch Drive
4th Floor
McLean, VA 22102
USA

**How can people contact you (email and phone)**
email / phone (if applicable)

Phone: +1.703.570.5185
Email: info@craftercms.com

**Regions you serve**
North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia

**Industry specialization**
hospitality, business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology

**Logo**
Please upload a company logo
![craftercms-logo-aws-mp-color-on-white](https://github.com/opensearch-project/project-website/assets/169432/c894a69b-c40c-4127-a7fe-0ba7fe549f0b)

**Additional image**
[Attach any additional image you would like to provide that showcase your business (product, technology, offices)
](https://docs.craftercms.org/en/4.1/by-role/author/index.html)

**Links**
https://craftercms.com
https://craftercms.org
https://docs.craftercms.org/

**Comment by pajuric** [comment]
Thank you, @russdanner. 

@astephanus - Ping

**Comment by pajuric** [comment]
@russdanner - Do you happen to have a square version or your logo that we could use for our main partner page here: [https://opensearch.org/partners](url). We can use the one your provided for the partner profile page, but for the main partner page, a square format is preferred and we didn't want to alter it without checking with you first.
