### ISSUE TITLE
Security testing updates

### ISSUE THREAD

**Issue by davidlago** [opensearch-project/project-website#1929]
**Describe the blog post your would like to write**
Blogpost updating on the latest security testing exercises

**What is the title of the blog post?**

**Who are the authors?**
@davidlago 

**What is the proposed posting date?**
TBD

**Comment by dimwetoth** [comment]
Publication date on this was supposed to be 6am on September 18, please move forward urgently as a partner blog is linking to this one.

**Comment by krisfreedain** [comment]
https://github.com/opensearch-project/project-website/pull/2005
on it's way out

**Comment by dimwetoth** [comment]
TY @krisfreedain for the quick turnaround.  Sorry for the miss.

**Comment by krisfreedain** [comment]
https://opensearch.org/blog/opensearch-security-a-testament-to-our-commitment/
