### ISSUE TITLE
Coralogix partner profile

### ISSUE THREAD

**Issue by oded-dd** [opensearch-project/project-website#1935]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Coralogix

**Brief description of your business and what it does (50 words or less)**
Harmonious, Full-Stack Observability at Scale
As data volumes continue to grow, traditional monitoring approaches can no longer ensure observability for modern systems. Coralogix uses a unique data streaming analytics pipeline – called [Streama©](https://coralogix.com/how-it-works/) – to analyze all observability data in real-time and provide long-term trend analysis without indexing.

**Name of your relevant product(s) or service for the OpenSearch audience**
Coralogix SaaS Platform

**What OpenSearch technologies do you specialize in**
Search, Analytics, Observability, Security

**Type of business**
SaaS Platform and Managed Services

**Home/main office location or address**

**How can people contact you (email and phone)**

**Regions you serve**
North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia

**Industry specialization**
Software and technology

**Logo**
<img width="428" alt="Coralogix-Green-Vertical" src="https://github.com/opensearch-project/project-website/assets/26864774/7cc8947c-9b8b-4063-abcb-c83db1a12fa7">

**Comment by pajuric** [comment]
@oded-dd - Thank you for creating your partner profile page. 

@astephanus - Ping

**Comment by krisfreedain** [comment]
Done! thanks all
