### ISSUE TITLE
Receive mentorship from Amazon engineers and accelerate your career in Tech

### ISSUE THREAD

**Issue by rednaksi91** [opensearch-project/project-website#1949]
**Describe the blog post your would like to write**
A clear and concise description of what subject the blog post will cover.
The blog post will share all the necessary information about the upcoming Open Source Contributor Initiative (expansion of the College Contributor Initiative). It will also contain an application form to allow interested individuals to apply.

**What is the title of the blog post?**
Receive mentorship from Amazon engineers and accelerate your career in Tech

**Who are the authors?**
Iskander Rakhmanberdiyev
SDM, OpenSearch Dashboard Visualizations team

**What is the proposed posting date?**
We need the blog post published as soon as possible. The latest publishing date is 9/5

**Comment by krisfreedain** [comment]
published via https://github.com/opensearch-project/project-website/pull/1666
