### ISSUE TITLE
Adding integration catalog web-page to OpenSearch Website

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/project-website#1958]
**Describe the blog post your would like to write**
OpenSearch just released the [integration feature](https://github.com/opensearch-project/opensearch-catalog/tree/main/docs/integrations) and it will be very nice to have the catalog page displayed in the website 

In similar to other existing tool (https://calyptia.com/integrations) that have the integration concept we also need to reflect this within our own webpage
![screenshot ](https://github.com/opensearch-project/project-website/assets/48943349/9039641e-da36-4a4a-9f6f-059ec3625466)
---
The next [page](https://htmlpreview.github.io/?https://github.com/opensearch-project/opensearch-catalog/blob/main/integrations/observability/catalog.html) is auto create from our Observability catalog and needs to be added to our website 

**What is the title of the web-page **
OpenSearch Integration catalog

**What is the proposed posting date?**
Add this page to the website ASAP

**Comment by dtaivpp** [comment]
We can probably leverage the partners/extended partner pages to make something similar for integrations.

**Comment by krisfreedain** [comment]
Agree - I could see that working well.

**Comment by juliechan01** [comment]
I don't know if this has been assigned yet but am willing to work on it if it hasn't been assigned yet.

**Comment by YANG-DB** [comment]
moved to the documentation repo https://github.com/opensearch-project/documentation-website/pull/7324
