### ISSUE TITLE
Efficient Filters in Vector Search

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/project-website#1963]
**Describe the blog post your would like to write**
I am planning to write a blog regarding different filters we have for the Dense Vector Field in OpenSearch. The blog will provide details around different types of filters, their usecase and benchmarks to help customer understand the performance and accuracy of these filters.

Current K-NN docs: https://opensearch.org/docs/latest/search-plugins/knn/filter-search-knn/

**What is the title of the blog post?**
Efficient Filters in Vector Search (Subject to change)

**Who are the authors?**
@navneet1v 

**What is the proposed posting date?**
9/28

**Comment by pajuric** [comment]
@navneet1v - checkin on this blog and when you will have a draft ready for review. Please provide an update.

**Comment by navneet1v** [comment]
Hi,
the blog draft is ready for review. Please let me know the next steps.
