### ISSUE TITLE
[Blog post] Use OpenSearch Benchmark with randomized query terms

### ISSUE THREAD

**Issue by Jon-AtAWS** [opensearch-project/project-website#1965]
**Describe the blog post your would like to write**
One limitation of OpenSearch Benchmark is that when you run a search operation, the query itself is hard-coded. If you want to randomize your query workload across a set of possible search terms, there's no out of the box way to do that. In this post, you'll use data from [BoardgameGeek.com](https://boardgamegeek.com/) (BGG) to create a custom Opensearch Benchmark workload. You'll then create two, line-per-query files and use those files to create randomized terms for querying OpenSearch. 

**What is the title of the blog post?**
Use OpenSearch Benchmark with randomized query terms

**Who are the authors?**
Jon Handler

**What is the proposed posting date?**
As soon as it's ready

**Comment by nateynateynate** [comment]
I think this has been published. Closing for housekeeping. 

https://opensearch.org/blog/use-opensearch-benchmark-with-randomized-query-terms/
