### ISSUE TITLE
Blog Post on IP2Geo processor

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/project-website#1971]
**Describe the blog post your would like to write**
How to add country of incoming requests based on IP address using IP2Geo processor

**What is the title of the blog post?**
New real time IP to Geo processor for OpenSearch

**Who are the authors?**
Who will be listed as the authors of this blog post
Heemin Kim, Junqiu Lei, Satish Nandi, Vamshi Vijay Nakkirtha

**What is the proposed posting date?**
9/22

**Comment by nandi-github** [comment]
Added comments. I will approve once the comments are addressed.

**Comment by pajuric** [comment]
@krisfreedain - Blog is GTG. Let's publish.

**Comment by nateynateynate** [comment]
Looks like this one has been satisfied. https://opensearch.org/blog/use-opensearch-benchmark-with-randomized-query-terms/
