### ISSUE TITLE
Typo on Downloads page

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/project-website#201]
Under the first section [Try OpenSearch with Docker Compose](https://opensearch.org/downloads.html#docker-compose) there is a typo: 

> 3. Have a nice coffee while everything is downloading and startup up

This should read

> 3. Have a nice coffee while everything is downloading and **starting** up

**Comment by dblock** [comment]
Did you make a PR yet? ;)

**Comment by tmarkley** [comment]
Haven't had a chance to pull down the repo yet, but yes I can this afternoon :)
