### ISSUE TITLE
Fix Get Started documentation

### ISSUE THREAD

**Issue by setiah** [opensearch-project/project-website#222]
The `Get Started` instructions for setting up a docker based OpenSearch cluster does not work as mentioned. These instructions are missing some pre-requisite settings for linux and Mac, which make docker setup fail. This creates confusion and bad Getting started experience for users. 

Fix is suggested here - https://github.com/opensearch-project/OpenSearch/issues/978

**Comment by stockholmux** [comment]
fixed by #250
