### ISSUE TITLE
Sematext - October OpenSearch Online Training

### ISSUE THREAD

**Issue by AncaCoanda** [opensearch-project/project-website#2272]
Sign up for our upcoming October OpenSearch Online Training - Sematext
Live, Instructor-led OpenSearch Online Training
Strengthen your skills to master OpenSearch faster. Join our online classes covering from beginner to advanced level.

**OpenSearch Training Overview**: https://sematext.com/training/opensearch/
**OpenSearch Training Classes:**
- Intro to OpenSearch: https://sematext.com/training/opensearch/intro-opensearch/
- OpenSearch Operations: https://sematext.com/training/opensearch/opensearch-operations/
- OpenSearch for Product Searches: https://sematext.com/training/opensearch/opensearch-for-product-searches/

**Description**
Our hands-on OpenSearch classes cover all the fundamentals, from CRUD operations to analysis as well as advanced concepts: whether it's tweaking your data layout and relevance for E-commerce applications or it's tuning your cluster for handling petabytes.

**The author**
Sematext

**Comment by AncaCoanda** [comment]
**What is the proposed posting date?**
09/29 or earlier

**Comment by otisg** [comment]
@pajuric When is the next newsletter getting published?

**Comment by radu-gheorghe** [comment]
While October is behind us, the links in the description are still valid, we're planning to have a new batch of classes in May 2024: https://sematext.com/training/opensearch/

**Comment by pajuric** [comment]
@radu-gheorghe - I am going to close this for now, but we are in the process of restarting our newsletter. So please be sure to share these and consider listing your trainings on our events calendar for promotion. Directions on how to submit are here: https://opensearch.org/events/calendar/2024/june/
