### ISSUE TITLE
Add Search Functionality to the Main Website. 

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/project-website#229]
The documentation website currently has the [search functionality](https://github.com/opensearch-project/documentation-website/blob/main/_config.yml#L98) enabled. This functionality gives the user the flexibility to search for any topic on the website. The topics on the main website include latest blogposts, getting started sections, faqs etc. 

In addition to the enabling the search, we might need UI mocks ups for the placement of the search bar on the main page. Reference in the [documentation website](https://github.com/opensearch-project/documentation-website/blob/main/_layouts/default.html#L106).

**Comment by stockholmux** [comment]
Thanks for the call out @aditjind. The documentation search functionality is a hold over from porting the Open Distro documentation site. It runs in the front-end and, as that gets versioned, will likely be more and more problematic. There is only so much one can expect javascript to do as far as a search engine from the browser (note: I speak from experience - I have made the grave mistake in previous projects).

It's also a bummer that OpenSearch.org doesn't use, uh, OpenSearch for it's site search. Additionally, it'd be useful to have a unified site and documentation search - I think users would expect to be able to find the term 'foo' in either a blog post or a doc page.

So, I think that's the direction we should take this, but it's not a short-term solution.

**Comment by stockholmux** [comment]
Closed by #1219
