### ISSUE TITLE
[BUG] Featured Blog Post Excerpt is Malformed

### ISSUE THREAD

**Issue by astephanus** [opensearch-project/project-website#2308]
**Describe the bug**
The homepage featured blog post excerpt will not be properly styled depending on how it is authored.

**To Reproduce**
1. Go to https://opensearch.org/
2. Scroll down to the Featured Blog posts hero.
3. The featured blog post preview with excerpt will use more vertical space that it is designed (at least with the current blog post of https://opensearch.org/blog/remote-backed-storage/). 

**Expected behavior**
The preview should fit within its bounding box, and the excerpt text should be line-clamped at 5 maximum lines with an ellipsis if necessary.

**Comment by ReinGrad** [comment]
* Adding overflow: hidden and text-overflow: ellipsis to the excerpt container to enforce line clamping
* Adjusting line heights or margins to condense vertical space
* Modifying excerpt generation logic to truncate at a certain character count

**Comment by astephanus** [comment]
@ReinGrad This was already solved a week ago in PR https://github.com/opensearch-project/project-website/pull/2309. I've left the issue open as the PR has yet to be reviewed and merged.

**Comment by astephanus** [comment]
Resolved in PR https://github.com/opensearch-project/project-website/pull/2309.
