### ISSUE TITLE
OpenSearchCon 2023 post-event blog

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#2327]
**Describe the blog post your would like to write**
The blog recaps OpenSearchCon 2023 and provides an OV of event specifics. 

**What is the title of the blog post?**
OpenSearchCon 2023 post-event blog

**Who are the authors?**
Marketing @jhmcintyre 

**What is the proposed posting date?**
10/6/23

**Comment by krisfreedain** [comment]
thanks @pajuric for letting me know it's approved. 
Put this together https://github.com/opensearch-project/project-website/pull/2328 - we'll get it published today

**Comment by pajuric** [comment]
Are you good with me closing out this blog issue since the blog is now live?

**Comment by jhmcintyre** [comment]
Yes, thank you.

**Comment by pajuric** [comment]
Closing this out.
