### ISSUE TITLE
[Enhancement] OpenSearchCon session page to include YouTube videos

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/project-website#2332]
**Is your feature request related to a problem? Please describe.**
Now that we are through OpenSearchCon, the recordings of each session are being processed. Each session will be uploaded to our YouTube channel. We would like to offer a way to embed the video files in each of their corresponding session pages.

**Describe the solution you'd like**
On each session page, we should be able to insert the YouTube embed code in the section below the description, but above the speaker(s) section - see: 

<img width="1459" alt="Screenshot 2023-10-06 at 9 58 22 AM" src="https://github.com/opensearch-project/project-website/assets/4873623/423efb92-1706-4c15-a26c-cb9b8cf30948">

**Comment by maezieLoo** [comment]
To keep the video above the fold, let's embed it above the description content like so: 
<img width="895" alt="Screenshot 2023-10-09 at 2 41 13 PM" src="https://github.com/opensearch-project/project-website/assets/146998352/80366dab-77e0-47e2-9b2c-2fa14953b12a">

**Comment by wbeckler** [comment]
This looks like it happened. E.g., https://opensearch.org/events/opensearchcon/2023/north-america/sessions/18-months-of-operating-opensearch-at-scale.html
