### ISSUE TITLE
OpenSearch 2.11.0 is available for Download

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#2351]
**Describe the blog post your would like to write**
Announcing the release of OpenSearch 2.11.0 while providing an overview of the new features. 

**What is the title of the blog post?**
OpenSearch 2.11.0 is available for Download

**Who are the authors?**
@jhmcintyre 

**What is the proposed posting date?**
10/16 or 10/17
Provide the date which you wish this post to go live

**Comment by krisfreedain** [comment]
Done! 
https://opensearch.org/blog/get-started-opensearch-2-11/
