### ISSUE TITLE
Cohere Partner Page Information 

### ISSUE THREAD

**Issue by mahjongmen** [opensearch-project/project-website#2357]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Cohere

**Brief description of your business and what it does (50 words or less)**
Cohere is the leading AI platform for enterprise. Its world-class AI is uniquely suited to the needs of business, unlocking unprecedented ease-of-use, accessibility, and data privacy. Cohere’s platform is cloud-agnostic, accessible through API as a managed service, and can be deployed on virtual private cloud (VPC) or on premise.

**Name of your relevant product(s) or service for the OpenSearch audience**
Connectors for third-party ML platforms in the form of an embedding model and a reranker model

**What OpenSearch technologies do you specialize in**
Search (Information Retrieval and Reranking)

**Type of business**

Product/Technology (Machine Learning Platform)

**Home/main office location or address**
171 John Street, Toronto, Ontario

**How can people contact you (email and phone)**
team@cohere.ai

**Regions you serve**

Global

**Industry specialization**

business service, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, software and technology

**Logo**
![Cohere-Logo-Color-RGB](https://github.com/opensearch-project/project-website/assets/15052030/a482f527-e664-40b9-bc34-4836835bf986)

**Additional image**

**Links**
[Semantic Search with Open Search and Cohere: A Comprehensive Demo](https://txt.cohere.com/semantic-search-open-search-demo/)
[Using LLMs for Search with Dense Retrieval and Reranking](https://txt.cohere.com/using-llms-for-search/)
[Rerank Product Announcement](https://txt.cohere.com/rerank/)

**Comment by pajuric** [comment]
@mahjongmen - Thank you, Elliott, for your submission.
