### ISSUE TITLE
[Blog] How to create custom Threat Detection Rules in Security Analytics

### ISSUE THREAD

**Issue by xeniatup** [opensearch-project/project-website#2383]
**Describe the blog post your would like to write**
Security Analytics (plugin) simplifies and increases the efficiency of the security operations by leveraging its threat detection engine, which comes with a collection of pre-packaged detection rules. Additionally, you can create new detection rules to customize the threat detection to your specific needs.

**What is the title of the blog post?**
Threat hunting with custom rules and filters

**Who are the authors?**
Xenia Tupitsyna, Sandesh Kumar, Jimish Shah

**What is the proposed posting date?**
TBD

**Comment by pajuric** [comment]
@xeniatup - Thank you for the blog submission. Do you have a target date for this, even if it's a month out? It will help me calendar the blog and make sure it keeps moving.

**Comment by xeniatup** [comment]
@pajuric I'm at the second round of feedback for the blog. I think we can safely plan for mid-November.

**Comment by pajuric** [comment]
Closing this out
