### ISSUE TITLE
Trust in Open Source Software

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#2387]
**Describe the blog post your would like to write**
We are sharing results of Q3 quarterly survey that was hosted on OpenSearch.org website

**What is the title of the blog post?**
Trust in Open Source Software

**Who are the authors?**
Aparna Sundar and Kris Freedain

**What is the proposed posting date?**
October 31st

**Comment by pajuric** [comment]
@apasun - I'm checking on the draft for this and when you think it might be readyfor review?

**Comment by krisfreedain** [comment]
@pajuric @apasun - it's on me - I need to add to it still - will likely have time to work on it tomorrow
