### ISSUE TITLE
CrafterCMS Partner Request

### ISSUE THREAD

**Issue by russdanner** [opensearch-project/project-website#2391]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
CrafterCMS

**Brief description of your business and what it does (50 words or less)**
CrafterCMS is an open source, Git-based headless CMS for the enterprise. Crafter Software dba CrafterCMS sells support and services for CrafterCMS
 
**Name of your relevant product(s) or service for the OpenSearch audience**
CrafterCMS

**What OpenSearch technologies do you specialize in**
Is there an area of the project where your business specializes?
Search

**Type of business**
Product/Technology

**Home/main office location or address**
7918 Jones Branch Drive 4th Floor McLean, VA 22102 USA

**How can people contact you (email and phone)**
info@craftercms.com, +1.703.570.5185

**Regions you serve**
North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia

What regions of the world do you serve?

**Industry specialization**
business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology

**Logo**
Please upload a company logo

![Craftercms-logo](https://github.com/opensearch-project/project-website/assets/169432/849ebcd2-7548-409e-925a-a8f9ccee3586)

![craftercms](https://github.com/opensearch-project/project-website/assets/169432/6ddda3ee-9a84-4970-bb93-9527ecdcf26b)

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
Add links to your last three blogs that are relevant for the OpenSearch Project audience.
https://craftercms.com

**Comment by pajuric** [comment]
Thank you for the partner page info @russdanner.

**Comment by pajuric** [comment]
@astephanus

**Comment by astephanus** [comment]
@pajuric This is completed in [PR #2394](https://github.com/opensearch-project/project-website/pull/2394), and can be closed.

**Comment by nateynateynate** [comment]
Looks like we're not doing a very good job keeping ttrack of these. Let's get this issue closed out. Thanks @astephanus !
