### ISSUE TITLE
[Blog] Semantic Search at scale with OpenSearch: Options and Benchmark

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opensearch-project/project-website#2413]
**Describe the blog post your would like to write**
We enabled ML connectors for semantic search with OS 2.9. So now users have multiple options setting up semantic search for their OS clusters. We'd like to publish a blog post to illustrate different options and compare their performance, helping users to pick up the right options for their need.

**What is the title of the blog post?**

Semantic Search at scale with OpenSearch: Options and Benchmark

**Who are the authors?**
Sean Zheng, Zan Niu

**What is the proposed posting date?**
Nov 20th, 2023

**Comment by pajuric** [comment]
@sean-zheng-amazon - I am going to close the original blog issue for this blog, and go with this one since the focus has expanded. The original is here: https://github.com/opensearch-project/project-website/issues/1270 and I am going to close it.
