### ISSUE TITLE
Linuxfabrik GmbH

### ISSUE THREAD

**Issue by markuslf** [opensearch-project/project-website#2434]
**Organization name**
Linuxfabrik GmbH

**Brief description of your business and what it does (50 words or less)**
Linuxfabrik is your partner for Linux and Open Sourc. We help companies with all aspects of Linux and Open Source software, from consulting to secure operation and maintenance. As part of our service and support models, we can help you with almost any Linux and Open Source need, including OpenSearch.

**Name of your relevant product(s) or service for the OpenSearch audience**
Linux, Ansible, Elasticsearch, Graylog, OpenSearch

**What OpenSearch technologies do you specialize in**
Alerting, Analytics, Authentication, Log Analytics, Log Management, Observability, Optimizations, Search, Security

**Type of business**
Services organization

**Home/main office location or address**
Linuxfabrik GmbH
Witikonerstrasse 15
8032 Zürich
Switzerland

**How can people contact you (email and phone)**
info@linuxfabrik.ch

**Regions you serve**
Europe (DACH)

**Industry specialization**
All

**Comment by krisfreedain** [comment]
thanks for the info and follow up @markuslf 
cc @pajuric

**Comment by pajuric** [comment]
@krisfreedain - will do.

**Comment by pajuric** [comment]
@astephanus - Ping, you're it.

**Comment by krisfreedain** [comment]
@pajuric @astephanus ?? 

page is live: https://opensearch.org/partners/linuxfabrik.html
