### ISSUE TITLE
Add page to generate passwords

### ISSUE THREAD

**Issue by sandervandegeijn** [opensearch-project/project-website#246]
When you deploy docker containers or kubernetes containers the current process is cumbersome. You first to spin it up, then you can use the hash.sh / hash.bat scripts to generate some passwords (masking the passwords is also a hassle because you don't know what you pasted in the console).

A page on the website where you can put in the password and get the appropriate hash back would be nice.

**Comment by elfisher** [comment]
Do you have an example site in mind that you could share? I'm trying to better understand the request. Thanks!

**Comment by stockholmux** [comment]
@ict-one-nl I'd love to know more - as @elfisher notes, it'd be good to see another project doing something similar.

**Comment by ict-one-nl** [comment]
I don't have an example site, but it's quite simple: provide the functionality the hash.sh / hash.bat provides: have an input field for the plain text password(s) and generate (preferably client side) the corresponding hash(es) so that it can be copy/pasted into the security configs.

**Comment by stockholmux** [comment]
I like the idea and generally the idea website-driven configurators. I'm going to put it on the roadmap but I think this should be part of a larger effort on configuration.

**Comment by ict-one-nl** [comment]
Great thanks, if you guys to spar about ideas, np.
