### ISSUE TITLE
Macos artifacts for opensear cli

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/project-website#254]
Shall we include macos pkg artifacts link for opensearch cli?

**Comment by elfisher** [comment]
That makes sense. Are these built and hosted already and just need to be linked to from the website?

**Comment by stockholmux** [comment]
I created the stubs for these a while back - can you make any updates as needed and send a PR @VijayanB? It's basically YAML.

Looks like the `artifact_url` and `signature` will need to be updated. Additionally, the filename will need to have the initial `_` removed from the file name to unhide it from Jekyll.

If we aren't doing an arm64 version, we can just delete the arm64 version for the time being?

https://github.com/opensearch-project/project-website/blob/main/_artifacts/opensearch-cli/_opensearch-cli-1.0.0-macos-x64.markdown

and 

https://github.com/opensearch-project/project-website/blob/main/_artifacts/opensearch-cli/_opensearch-cli-1.0.0-macos-arm64.markdown

**Comment by stockholmux** [comment]
Closed by #272
