### ISSUE TITLE
Slack invite is expired

### ISSUE THREAD

**Issue by dmoreira-sbp** [opensearch-project/project-website#2552]
Hello hello!

I was looking to join the slack workspace but I believe the link is expired.

https://github.com/opensearch-project/project-website/blob/a1a6c47f28b1dab6e4a75e02d3ef923c0a987764/slack.markdown?plain=1#L25

**Comment by krisfreedain** [comment]
thanks @dmoreira-sbp - will work on updating it this morning

**Comment by krisfreedain** [comment]
thanks again @dmoreira-sbp - page is now updated https://opensearch.org/slack.html

**Comment by dmoreira-sbp** [comment]
Thank you @krisfreedain! Much appreciated :)
