### ISSUE TITLE
Customer Experience Outcomes to Focused User Centered Product Design Improvements

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#2579]
**Describe the blog post your would like to write**
This blog describes how product managers and UX designers can capture the health of software experience using customer experience outcome metrics. It also describes how we can improve user experience using an objective user centered approach

**What is the title of the blog post?**
Customer Experience Outcomes to Focused User Centered Product Design Improvements

**Who are the authors?**
apasun

**What is the proposed posting date?**
Provide the date which you wish this post to go live2/15/2024

**Comment by nateynateynate** [comment]
Looks like this blog has been merged. Closing the issue out. 

#2640
