### ISSUE TITLE
[BUG] No data in Playgroun eCommerce sample

### ISSUE THREAD

**Issue by smacrakis** [opensearch-project/project-website#2594]
**Describe the bug**
There doesn't seem to be any data in the eCommerce dashboard.

**To Reproduce**
Go to https://playground.opensearch.org/app/home#/
Click on Manage sample data
Click on "View data" under "Sample eCommerce orders"
There is no data.

Try to filter on Manufacturer -- get error that Manufacturer.keyword doesn't exist in any documents.

**Expected behavior**
I expect a populated display.
I expect the filtering criteria to work.

**Plugins**
??? How do I determine this?

**Screenshots**
![Screenshot 2024-02-19 at 14 46 52](https://github.com/opensearch-project/project-website/assets/134456002/3a743990-997b-438e-b8ae-fa7adec5e8b6)

**Host/Environment (please complete the following information):**
MacOS 14.3.1
Chrome 121.0.6167.184 

**Additional context**

**Comment by nateynateynate** [comment]
Works for me. I'm assuming this has been fixed since last reported.

**Comment by nateynateynate** [comment]
@smacrakis - are you still seeing the above?
