### ISSUE TITLE
[BUG] release.html missing 2.12 info in list of releases.

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/project-website#2611]
https://opensearch.org/releases.html has a list of releases half way down the page, showing that 2.11.1 and 1.3.14 are the latest released versions. As of February 20, 2.12 has been released.

Also, above that, is a confusing table with the column labelled "Latest Minor Version." This table shows 2.0.0 as a latest minor. I think we should either remove the table, update it every release, or write "2.x"

**Comment by nateynateynate** [comment]
Sorry for not referencing this issue in a PR @wbeckler - it does appear that this has since been fixed. Going to mark this one as done.
