### ISSUE TITLE
Remove 'Stay Informed' button from OpenSEarchCon 2024 Europe landing page.

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#2672]
**Is your feature request related to a problem? Please describe.**

We just want to get rid of the button as it leads to a splashthat page that no longer needs maintaining. 

**Describe the solution you'd like**
A quick edit of the markdown for the landing page should do the trick.

**Comment by pajuric** [comment]
@krisfreedain @nateynateynate - Is this complete? Can I close this issue?

**Comment by pajuric** [comment]
@krisfreedain @nateynateynate - Can this issue be closed?

**Comment by krisfreedain** [comment]
yes
