### ISSUE TITLE
Hostkey

### ISSUE THREAD

**Issue by hkadm** [opensearch-project/project-website#2675]
**Organization name**
HOSTKEY B.V.

**Brief description of your business and what it does (50 words or less)**
We offer a wide range of dedicated servers from entry-level up to high-performance GPU servers and private cloud solutions. Our servers are hosted in TIER III data centers in the Netherlands, Germany, Finland, Iceland, Turkey and the USA.

**Name of your relevant product(s) or service for the OpenSearch audience**
Bare metal dedicated servers, GPU dedicated and VPS servers with pre-installed OpenSearch.

**What OpenSearch technologies do you specialize in**
We provide pre-installed and ready-to-use OpenSearch for our clients in our App Marketplace. 

**Type of business**
Server infrastructure provider

**Home/main office location or address**
Willem Frederik Hermansstraat 91, 1011DG Amsterdam, Netherlands

**How can people contact you (email and phone)**
support@hostkey.com

**Regions you serve**
North America, Europe, Middle East, Africa, Asia Pacific, Australia

**Industry specialization**
business services, consumer services

**Logo**
![hostkey](https://github.com/opensearch-project/project-website/assets/87852135/4824363f-a875-413c-8a3c-aa9666182e4a)

**Links**
https://hostkey.com/vps/
https://hostkey.com/dedicated-servers/
https://hostkey.com/apps/databases/opensearch/

**Comment by nateynateynate** [comment]
#2665 merged. Thanks for joining us Hostkey!
