### ISSUE TITLE
Partner Page v2

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#2677]
We require a new partner landing page that talks about all the advantages of being a partner. Our current implementation is an endless list of partners. Rather than this, we'd like a landing page that explains: 

* why partner with opensearch
* exploring partnership
* click throughs to become a partner and to also visit the "Partner Finder" (issue tba)
* a list of projects being worked on by our partner community
* a carousel of sorts to highlight partner blogs (tbd)
* a carousel / accordion of quotes about opensearch from a few of our existing partners.

**Comment by pajuric** [comment]
@nateynateynate @astephanus - Wireframe and design was already created by Maeve. The on-page content just needs to be updated in the staged page.

**Comment by nateynateynate** [comment]
#3082
