### ISSUE TITLE
Create OpenSearchCon NA 2024 save the date webpage and add to top-nav

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#2681]
Create OpenSearchCon North America 2024 webpage to start collecting interest and to tease "save the date."

- Add OpenSearchCon NA to the top navigation
- Build page using the OSCon EU page as the example
- Create page banner using design provide by team
- Add CTA to capture leads (TBD)
- Include social sharing buttons and icons to start promotion

Page should be ready to launch by May 1, 2024.

**Comment by nateynateynate** [comment]
Completed.
