### ISSUE TITLE
Using Documentation for Usability Studies

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#2682]
**Describe the blog post your would like to write**
Using Documentation for Usability Studies. We offer tools and guidance on how to use the documentation on Figma. We also offer the actual documentation on Figma

**What is the title of the blog post?**
Using Documentation for Usability Studies

**Who are the authors?**
Aparna Sundar and Xenia Tupitsyna

**What is the proposed posting date?**
April 3rd

**Comment by pajuric** [comment]
Thanks for your contribution.
