### ISSUE TITLE
[BUG] The Usability blog doesn't include the embedded video

### ISSUE THREAD

**Issue by xeniatup** [opensearch-project/project-website#2704]
**Describe the bug**
The https://opensearch.org/blog/UsingDocumentationForUsabilityStudies/ blog doesn't have the video embedded.

**To Reproduce**
1. Go to '[Using documentation for usability studies blog](https://opensearch.org/blog/UsingDocumentationForUsabilityStudies/)'
2. Scroll down to the very end of the blog
4. See the mention of the video

**Expected behavior**
The video should be included in the page.

**Screenshots**
<img width="891" alt="Screenshot 2024-04-02 at 4 03 40 PM" src="https://github.com/opensearch-project/project-website/assets/105245012/abfc7322-8169-4dcd-a56c-6ce631103b16">

The snippet provided by YouTube for embedding:

`<iframe width="560" height="315" src="https://www.youtube.com/embed/06o1yActr7M?si=30Dano3Irp07y6za" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`

**Comment by nateynateynate** [comment]
Thanks for filing an issue on this one Xenia! I've made a quick change to your PR and then merged it to staging.
