### ISSUE TITLE
A comprehensive guide to setup and connect self-managed dashboards with Amazon OpenSearch domain

### ISSUE THREAD

**Issue by madhankb** [opensearch-project/project-website#2713]
**Describe the blog post your would like to write**
In our service, Blue-Green deployment often results in downtime for managed service dashboards, impacting availability. Given the critical reliance of our customers on these dashboards for log analytics and other use cases, I've devised a workaround. By setting up self-managed dashboards and connecting them with the managed service domain, downtime issues during Blue-Green deployment are effectively mitigated. This guide walks through the setup process for self-managed dashboards, covering options such as no authentication, basic authentication, and SAML authentication. Customer to follow along with this blog to implement the solution at their end and ensure uninterrupted access to dashboards.

**What is the title of the blog post?**
A comprehensive guide to setup and connect self-managed dashboards with Amazon OpenSearch domain

**Who are the authors?**
@madhankb / @mkbn

**What is the proposed posting date?**
As early as possible.

**Comment by madhankb** [comment]
The blog details are already published in my personal Github repos. PFB the links
https://github.com/madhankb/OSD-SM-Compatibility-Matrix
https://github.com/madhankb/OSD-SM-No-Authentication
https://github.com/madhankb/OSD-SM-SAML
https://github.com/madhankb/OSD-SM-HTTP-basic-authentication

It can be taken for technical review.

**Comment by nateynateynate** [comment]
Hi @madhankb ! 

This doesn't quite read like a blog but rather a technical tutorial. Is there a way we could incorporate these into a longer narrative that has room for each section? 

We can also reach out to @hdhalter to see if she could use a quick tutorial to post on some of these things in the documentation site. 

Any particular preference?

**Comment by madhankb** [comment]
I concur! It would be fantastic if we have the ability to post these on the OpenSearch documentation site.

**Comment by madhankb** [comment]
I can also write up something like a blog along with the guide/steps to implement like this - https://quip-amazon.com/HtNeAnuOkSpT/Connecting-Standalone-Opensearch-Dashboards-with-Managed-Service-Opensearch-through-Basic-and-SAML-Authentication. 
Let me know if you don't have access to the above link

**Comment by madhankb** [comment]
Can we have an update in here please?

**Comment by madhankb** [comment]
Is there any update? Can someone help?

**Comment by pajuric** [comment]
@madhankb - Please go ahead an open a PR for your blog draft in the web repo using thus guide here: https://github.com/opensearch-project/project-website/blob/main/BLOG_GUIDE.md, and we'll get it pushed through the review process.

**Comment by madhankb** [comment]
@pajuric - Opened a PR - https://github.com/opensearch-project/project-website/pull/2852. Kindly do the needful

**Comment by madhankb** [comment]
@pajuric - The blog is approved and ready to be published. Whats the next steps?
https://app.asana.com/0/0/1207214431107391/f
