### ISSUE TITLE
Infino

### ISSUE THREAD

**Issue by ekechinwokah** [opensearch-project/project-website#2714]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Infino

**Brief description of your business and what it does (50 words or less)**
Infino offers a schemaless, serverless managed OpenSearch service optimized for Observability. Cheaper, faster, and with more observability features, it allows you to store logs, metrics, traces, code, tickets, etc. in a single index and query your data via several popular languages: Natural Language, Query DSL, PromQL, PPL, etc.

**Name of your relevant product(s) or service for the OpenSearch audience**
Infino OpenSearch

**What OpenSearch technologies do you specialize in**
Observability

**Type of business**
ISV

**Home/main office location or address**
Infino AI Inc.
19266 Coastal Hwy
Unit 4-250
Rehoboth Beach, DE 19971

**How can people contact you (email and phone)**
info@infino.ai

**Regions you serve**
North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia

**Industry specialization**
Business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology.

**Logo**
assets/media/partners/infino.png
assets/media/partners/infino/infino_logo.png

**Additional image**
TBD

**Links**
TBD

**Comment by nateynateynate** [comment]
Welcome to the list of partners!
