### ISSUE TITLE
Events breadcrumb links to 2024-4.html which 404's.

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#2721]
When visiting:  https://opensearch.org/events/calendar/2024/april/

The 'Events' button in the breadcrumbs leads to /events/calendar/2024-04.html which returns a 404. 

![Image](https://github.com/opensearch-project/project-website/assets/96254688/359f42e4-11fc-497b-a3b3-f1871ed22d05)

![Image](https://github.com/opensearch-project/project-website/assets/96254688/7f778558-137e-4c4e-b9af-380befed538a)

![Image](https://github.com/opensearch-project/project-website/assets/96254688/cf7f4c33-d9e9-446a-8a46-6697f3efd301)

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by nateynateynate** [comment]
#2746 
#3072 

We can close this one out.
