### ISSUE TITLE
Improve the search relevancy of the project&documentation website

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/project-website#2727]
**Is your feature request related to a problem? Please describe.**
Currently, when we do search within the opensearch.org website for some topics/documentations, the search results are not clear enough and might contain duplicate.

We could improve the relevancy of the search for users to look up any information.

**Comment by nateynateynate** [comment]
Awesome! Thanks @zelinh - you may want to checkout the repo here. https://github.com/opensearch-project/project-website-search

We've got a lambda or two that indexes our website, but it's almost exactly as you've stated: the results are sometimes repetitive, and there are certain collections of ours that we don't search through. I'd love to add community members, events, and certain forum threads to the list of potential items in that dropdown. 

Thank you for getting involved!

**Comment by pajuric** [comment]
@hdhalter - FYI

**Comment by zelinh** [comment]
We have completed the infra upgrade on our side. The query for searching is updated for better relevancy. Closing this issue for now.
