### ISSUE TITLE
Adding Quesma as a partner

### ISSUE THREAD

**Issue by ptbrzoska** [opensearch-project/project-website#2731]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Quesma

**Brief description of your business and what it does (50 words or less)**
We help customers innovate faster by reshaping how applications are built and connected to their DBs. Quesma database gateway enables development teams to modernize and evolve application architecture by enabling interoperability between OpenSearch stack and efficient analytical DB platforms of your choice.

**Name of your relevant product(s) or service for the OpenSearch audience**
Quesma for OpenSearch

**What OpenSearch technologies do you specialize in**
All

**Type of business**
product/technology

**Home/main office location or address**
Warsaw/Poland

**How can people contact you (email and phone)**
info@quesma.com

**Regions you serve**
Worldwide

**Industry specialization**
software and technology

**Logo**
https://drive.google.com/file/d/10EmTT9O4TSznLUdfnHvDbtAfD3uMGVEe/view?usp=drive_link
Other approved variants: https://drive.google.com/drive/folders/1vFSvqOnIGEF4AL3oUVBHBKsy5Hq8ynPU?usp=drive_link

**Additional image**
<img width="1600" alt="quesma-elk-nologos" src="https://github.com/opensearch-project/project-website/assets/150345712/c1e47996-f906-4666-b768-ef83a1257b98">

**Links**
https://quesma.com/blog

**Comment by pajuric** [comment]
@ptbrzoska - Thanks for submitting.

**Comment by pajuric** [comment]
@ptbrzoska - We'll still need you open a pull request to file for partnership. The instructions can be found here: https://opensearch.org/new-partner.html

**Comment by ptbrzoska** [comment]
ok, my co-founder Jacek Migdal will open the other PR

**Comment by ptbrzoska** [comment]
@pajuric should the second PR include the sub-page content or you prefer to handle this on your side using information from above?

**Comment by pajuric** [comment]
The PR process is a second piece, and it's the formal request to partner and list your logo on our website:

Here are the steps: 
Joining the partner program is accomplished through a pull request to [opensearch-project/project-website](https://github.com/opensearch-project/project-website) in the _partners folder. The suggested method is to fork the repo, add the [partner markdown file](https://github.com/opensearch-project/project-website/blob/main/_partners/_sample.md) and [build the website locally to verify it looks correct](https://github.com/opensearch-project/project-website#building-the-website) then contribute the changed file back to opensearch-project/project-website.

**Comment by ptbrzoska** [comment]
ok, thanks @pajuric Let us know if you have everything by now.

**Comment by pajuric** [comment]
Closing issue since the page is created.
