### ISSUE TITLE
Why is our footer so freakin' huge on every page? Let's shrink that down.

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#2740]
Remove some of the footer so that it doesn't take up so much real estate.

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)

**Comment by nateynateynate** [comment]
Solved by #3157
