### ISSUE TITLE
VisBuilder GA blog

### ISSUE THREAD

**Issue by mnkugler** [opensearch-project/project-website#2789]
**Describe the blog post your would like to write**
You can use the VisBuilder visualization type in OpenSearch Dashboards to create data visualizations by using a drag-and-drop gesture. With VisBuilder you have an immediate view of your data without the need to preselect the visualization output. This provides flexibility to change visualization types and index patterns quickly and the ability to easily navigate between multiple screens.

**What is the title of the blog post?**
VisBuilder is now generally available!

**Who are the authors?**
Ashwin P Chandran

**What is the proposed posting date?**
May 14

**Comment by pajuric** [comment]
Thanks for the contribution.
