### ISSUE TITLE
Issue with "Multi-tenancy for all workloads" OpenSearchCon Europe session page

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/project-website#2791]
**Describe the bug**

**To Reproduce**
1. Go to https://opensearch.org/events/opensearchcon/2024/europe/index.html
2. Click on Sessions - then try to click on 
![Screenshot 2024-04-23 at 9 49 38 PM](https://github.com/opensearch-project/project-website/assets/4873623/501ba8ab-3c07-4fad-9271-fee427416d64)

it looks like it links to https://opensearch.org/events/opensearchcon/sessions/multi-tenancy-for-all-workloadshtml - see 404
(I even try inserting the missing . for https://opensearch.org/events/opensearchcon/sessions/multi-tenancy-for-all-workloads.html - still see a 404)

**Comment by nateynateynate** [comment]
Thanks @krisfreedain !
