### ISSUE TITLE
Clarify in README that posts in the future can be rendered with "--future" flag

### ISSUE THREAD

**Issue by elfisher** [opensearch-project/project-website#280]
Per Jekyll we can append the `--future` flag when running serve so that blogs posted in the future can be tested. The README should reflect this in the serve instructions.

**Comment by stockholmux** [comment]
Placing a link to the docs is fine, but I don't want to re-create the Jekyll docs on our README.

Note: we should also be careful about sending the message that future dated posts will automatically appear - they won't - we're not setup to do that.

**Comment by elfisher** [comment]
> Placing a link to the docs is fine, but I don't want to re-create the Jekyll docs on our README.
> 
> Note: we should also be careful about sending the message that future dated posts will automatically appear - they won't - we're not setup to do that.

Interesting @stockholmux . Should we set ourselves up to do that?

**Comment by stockholmux** [comment]
@elfisher It's a little hard to achieve, but not impossible. Basically it's like a triggered cron job to generate the site, but since the site is entirely on S3, we'd have to either setup something like a server or serverless function to run it.

**Comment by elfisher** [comment]
> @elfisher It's a little hard to achieve, but not impossible. Basically it's like a triggered cron job to generate the site, but since the site is entirely on S3, we'd have to either setup something like a server or serverless function to run it.

got it. Sounds like a more involved enhancement. Makes sense to keep it separate from this issue. Also agreed with the earlier comment. Linking to docs makes more sense.

**Comment by stockholmux** [comment]
Fixed by #281
