### ISSUE TITLE
[Feature]  How to integrate multiple data source with Dashboards plugin from dev perspective

### ISSUE THREAD

**Issue by zhyuanqi** [opensearch-project/project-website#2815]
**Describe the blog post your would like to write**
With the release of version 2.4, OpenSearch has introduced the Multiple Data Source. Multiple Data Source helps to connect OpenSearch clusters with remote clusters, including AWS OpenSearch Service. This feature allows users to utilize remote data sources to create visualizations and dashboards in local OpenSearch Dashboards. 

Recently, various OpenSearch Dashboards plugins have integrated with Multiple Data Source. This functionality helps user to access data from remote clusters directly within OpenSearch Dashboards, expanding the range of available data sources.

For developers seeking to integrate OpenSearch Dashboards plugins with multiple data sources, want to write a blog on a concise introduction on how to do it

**What is the title of the blog post?**
Integrate with multiple data source from dev perspective

**Who are the authors?**
Who will be listed as the authors of this blog post

**What is the proposed posting date?**

**Comment by pajuric** [comment]
Adding the linked PR: https://github.com/opensearch-project/project-website/pull/2839
