### ISSUE TITLE
Update Infino partner page information

### ISSUE THREAD

**Issue by vinaykakade** [opensearch-project/project-website#2828]
[Infino](https://opensearch.org/partners/infino.html) would like to update the partner page information, esp. with a new tagline for the company. 

We'll provide a PR with the changes to the existing partner page.

**Comment by pajuric** [comment]
@nateynateynate - Confirming this is completed and if the issue can be closed?

**Comment by nateynateynate** [comment]
Looks like this one was completed by #3082 - will close. 

Thanks everyone.
