### ISSUE TITLE
So... You want better OpenSearch Documentation...?

### ISSUE THREAD

**Issue by hdhalter** [opensearch-project/project-website#2854]
**Describe the blog post your would like to write**
Charlie Hull and Eric Pugh of OpenSource Connections presented at OpenSearchCon EUI on the current state of OpenSearch documentation and requested feedback. 

**What is the title of the blog post?**
So... You want better OpenSearch Documentation...?

**Who are the authors?**
Eric Pugh, Charlie Hull, Heather Halter

**What is the proposed posting date?**
5/21

**Comment by pajuric** [comment]
@hdhalter - Do you still intend to write this one?

**Comment by hdhalter** [comment]
@Patty8122 - This is ready for the metadata additions.
