### ISSUE TITLE
LinkedIN URL sharing looks not great

### ISSUE THREAD

**Issue by dimwetoth** [opensearch-project/project-website#2858]
**Describe the bug**
The OpenSearchCon North America 2024 page when shared on LinkedIN by URL produces a blank graphic box

**To Reproduce**
1. Go to opensearch.org
2. Click on 'OpenSearchCon in the top-nav
3. Click on OpenSearchCon 2024 North America
4. share the URL to the OpenSearchCon North America home page
5. Watch as it brings up a huge blank picture box when you share the URL

**Expected behavior**
A picture in place of a blank image, or an opensearch logo, or no picture at all. This is a very shareable page and there should be a share image associated with it.

 - Browsers: Chrome

**Additional context**
This is likely a site-wide problem and we should perhaps be pursuing something that works as a default share image if one doesn't exist.

**Comment by pajuric** [comment]
@dimwetoth - Thank you for the callout on this. I was just encountering the same issue.

**Comment by nateynateynate** [comment]
I have to agree with this. We need to set up our twittercard and site sharing metadata. I'll prioritize this and add it to our upcoming issues to work on.

**Comment by nateynateynate** [comment]
Completed with #2987.
