### ISSUE TITLE
OpenSearch Project Update: A Look at Performance Progress through Version 2.13

### ISSUE THREAD

**Issue by getsaurabh02** [opensearch-project/project-website#2859]
**Describe the blog post your would like to write**
This blog will be second blog to the Performance blog series which we started in Jan 2024 with https://opensearch.org/blog/opensearch-performance-improvements

**What is the title of the blog post?**
OpenSearch Project Update: A Look at Performance Progress through Version 2.13

**Who are the authors?**
@getsaurabh02 Pallavi Priyadarshini @navneet1v Ian Hoang, Stavros Macrakis

**What is the proposed posting date?**
May 2024

**Comment by pajuric** [comment]
@getsaurabh02 - you will need to open an Asana request for editorial review. Has this also received peer review by PM?
