### ISSUE TITLE
[BUG] Add second speaker field in OpenSearchCon NA CfP form in Airtable

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#2862]
**Describe the bug**
A second field is need or the option to add an additional speaker for people submitting the OpenSearchCon NA CfP. 

**To Reproduce**
1. Go to opensearch.org
2. Click on OpenSearchCon 2024 North America
3. Scroll down to `Submit a Presentation`
4. Scroll down to the `New CfP Submission` section
5. Add the option in a drop down or using + to insert a second speaker and their information

**Expected behavior**
Anyone submitting the CfP who has a co-presenter will be able to include and have them listed on their CfP submission for consideration

<img width="865" alt="Screenshot 2024-05-14 at 12 19 00 PM" src="https://github.com/opensearch-project/project-website/assets/106779470/2f8e7deb-e96d-44f2-a6e8-51c74e3cf10f">

**Comment by pajuric** [comment]
@DarshitChanpura - Request made

**Comment by nateynateynate** [comment]
I've added a second set of presenter inputs hidden behind a checkbox that the submitter can use to indicate that there will be a copresenter. I'll consider this one closed, but feel free to reopen if the new form doesn't meet your needs.
