### ISSUE TITLE
Embed vectorsearch workload for lucene and nmslib to website

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/project-website#2871]
**Is your feature request related to a problem? Please describe.**
Similar to faiss engine, website should show nightly runs metrics for other two engines

**Describe the solution you'd like**
Embed links from benchmarks.opensearch.org and add it to existing list

**Describe alternatives you've considered**
N/A

**Additional context**
Related to https://github.com/opensearch-project/project-website/pull/2850

**Comment by nateynateynate** [comment]
Solved via #2872 -

Thanks @VijayanB !
