### ISSUE TITLE
Graylog - Update logo and link to Blog

### ISSUE THREAD

**Issue by GrayMary** [opensearch-project/project-website#2892]
![Graylog_Logo_2024_blue](https://github.com/opensearch-project/project-website/assets/163166975/6f35832f-2351-4d3d-b808-8c90e3b3db23)

**Logo**
Please upload a company logo

**Additional image**
Please delte the red /gray old image -- Just the logo please 

**Links**
Add links to your last three blogs that are relevant for the OpenSearch Project audience.

Please remove the first link on Anomaly detection and replace with a link to https://opensearch.org/blog/navigating-the-future-of-log-management/

**Comment by nateynateynate** [comment]
Thanks @GrayMary ! I'll drop the new logo in and replace the anomaly detection link.

**Comment by nateynateynate** [comment]
@GrayMary : Do you have a thumbnail we can use for the blog link we're replacing? I'd hate to leave a big blank right here: 

![image](https://github.com/opensearch-project/project-website/assets/96254688/f8ee8fe8-3c17-4435-b65f-1f28544083ac)

**Comment by nateynateynate** [comment]
@GrayMary - our partners page usually renders best when we have a company logo that has a square aspect ratio. Do you have anything like that available? 

Thanks!

**Comment by GrayMary** [comment]
@nateynateynate Let me go track one down Thanks

**Comment by GrayMary** [comment]
I just saw your comment about thumbnail -- I will get one.

**Comment by GrayMary** [comment]
Here is an intriguing navigation image -- 
![Navigating Graphic](https://github.com/opensearch-project/project-website/assets/163166975/9d3aaca0-d6e4-4891-b28d-ef2a24bd8826)
Let me know if it works

**Comment by GrayMary** [comment]
@nateynateynate Hello - I am a contractor with Graylog and today is my last day -- so if you have a chance to complete that would be great. Thanks!
