### ISSUE TITLE
Add jonkaimmer to community members 

### ISSUE THREAD

**Issue by kaimmej** [opensearch-project/project-website#2893]
I am not sure if this is a feature request, but this seemed like the most appropriate bucket to place this under. 

**Is your feature request related to a problem? Please describe.**
Jon is now a contributing member. We should add him (me) to the site as a contributing member. 
Title - Backend Software Engineer supporting AWS OpenSearch
Full name - Jon Kaimmer 

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kaimmej** [comment]
![Screenshot 2024-05-21 at 1 57 07 PM](https://github.com/opensearch-project/project-website/assets/28766727/a0031811-f8a0-4933-9ff6-1ee72c8b8973)

Added jonkaimmer.md profile page in the community members. 
Made my profile consistent with the profile of existing members. 
Added photo as well.

**Comment by nateynateynate** [comment]
Closed via #2895
