### ISSUE TITLE
Update Blog with Links to Graylog website

### ISSUE THREAD

**Issue by GrayMary** [opensearch-project/project-website#2894]
https://opensearch.org/blog/navigating-the-future-of-log-management/

I failed to properly load the links to the blog.  If you can add them in based on the original word file - the Graylog team would appreciate it.

[Introducing Graylog with OpenSearch](https://graylog.org/products/security/?utm_source=partner&utm_medium=blog&utm_campaign=opensearch)

https://graylog.org/use-cases/centralized-log-management/?utm_source=partner&utm_medium=blog&utm_campaign=opensearch

7. [Security](https://graylog.org/products/security/?utm_source=partner&utm_medium=blog&utm_campaign=opensearch) and Compliance Built-in with Graylog

 Learn more about Graylog’s Security capabilities. 
https://graylog.org/products/security/?utm_source=partner&utm_medium=blog&utm_campaign=opensearch

Graylog [blog](https://graylog.org/post/understanding-the-difference-between-opensearch-and-elasticsearch/?utm_source=partner&utm_medium=blog&utm_campaign=opensearch)
https://graylog.org/post/understanding-the-difference-between-opensearch-and-elasticsearch/?utm_source=partner&utm_medium=blog&utm_campaign=opensearch
[Blog OpenSearch Graylog Final Draft w_ links-2.docx](https://github.com/opensearch-project/project-website/files/15395334/Blog.OpenSearch.Graylog.Final.Draft.w_.links-2.docx)

**Comment by pajuric** [comment]
@nateynateynate - We've agreed to help Graylog with this blog and help address the links that broke or that were dropped when we moved to publish.

**Comment by pajuric** [comment]
@nateynateynate - Can you and Jon help get the Graylog logo and page updated?

**Comment by pajuric** [comment]
@nateynateynate - Floating this one to the top. Please note that Mary is not able to update this request.
