### ISSUE TITLE
Verify organization domain

### ISSUE THREAD

**Issue by dblock** [opensearch-project/project-website#29]
Let's get a verified icon like other AWS organizations for https://opensearch.org?

https://docs.github.com/en/organizations/managing-organization-settings/verifying-your-organizations-domain

![verified](https://user-images.githubusercontent.com/542335/114790057-0e6f8200-9d52-11eb-9ef6-40932c2e09ee.gif)

**Comment by stockholmux** [comment]
Love it. I believe this might be slightly complicated due to the indirect management of the organization but do-able.

**Comment by stockholmux** [comment]
@peterzhuamazon Do you anticipate any blockers on the TXT record?

**Comment by AMoo-Miki** [comment]
I will take this over.

**Comment by AMoo-Miki** [comment]
![opensearch-org-verified](https://user-images.githubusercontent.com/3527403/129240608-b3a69ed1-e27a-427b-855a-e5f89984fd1b.png)

**Comment by stockholmux** [comment]
Looks like this is now solved. Horray!
