### ISSUE TITLE
[BUG] Mobile navbar uses different color specifications than non-mobile.

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#2902]
When narrowing the screen on a page that displays the navbar to the point where the mobile style kicks in, the colors of the links change. Let's make sure they use both so that changing navbar colors doesn't require multiple edits.

**Comment by dblock** [comment]
Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)
