### ISSUE TITLE
Vector radial search blog

### ISSUE THREAD

**Issue by junqiu-lei** [opensearch-project/project-website#2936]
**Describe the blog post your would like to write**
This blog post will cover the concept and use cases of vector radial search using OpenSearch.

**What is the title of the blog post?**
Vector Radial Search in OpenSearch

**Who are the authors?**
@junqiu-lei @vamshin @dylan-tong-aws

**What is the proposed posting date?**
6/10/2024

**Comment by nateynateynate** [comment]
#2994
