### ISSUE TITLE
[New Collection] - OpenSearchCons

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#2941]
**Is your feature request related to a problem? Please describe.**

A lot of the opensearchcon data that we use changes. We need to be able to rely on certain pieces of data with a variable, so that when it changes we can change it in one spot instead of five. For instance, if we extend the CFP close date, we tend to refer to it in blog posts and in the main index page and various other places that we might socialize. 

It's unsustainable to make five edits to broadcast the change of a date.

**Describe the solution you'd like**

I propose a new collection to the tune of `_opensearchcon`, with one markdown file per opensearchcon. This allows us two important things. 

1. We previously had no means of implementing an 'Archive' of previous opensearchcons where we can list them out in a skimmable manner. We would now be able to iterate over these and create a specific archive page.
2. We can now change the various details about an opensearchcon and refer to those pieces with variables instead of hand-coding dates and things that tend to mutate throughout the course of the event creation. 

**Additional context**

Please help me think of the variable types of data so that we can create meaningful frontmatter for each conference.

**Comment by kaimmej** [comment]
Seconded. This is a good idea. 
How are we currently storing this data?

**Comment by krisfreedain** [comment]
So you would propose everything for a single opensearchcon is in one file? Sessions, unconference, everything??!

Please explain in more depth.
