### ISSUE TITLE
Redesign -- New Issue: Bug Report 

### ISSUE THREAD

**Issue by kaimmej** [opensearch-project/project-website#2962]
## Problem
**I think we could have better user experience when they people go to add an issue for our project.** This could be simple things such as text areas, instead of raw markdown, drop-down menus for what component of the website it buggy, or simple things, like an emoji in title -> 🐛 Bug report

 think it is a cleaner experience for users, and might make for higher quality submissions from people. 

I suggest that there are efficiency improvements as well
- we could automatically assign the 'website-Update-Project' to new bug requests. These will still get the untriaged label, and so will still need to be seen, and prioritized, but it takes one step out of the process for our maintainers. Additionaly, it seems like feature requests, and bug reports only go to the website-update-project.
- Validator "required=true" on the fields that we think deserve it.

## Example
[OpenSearch new bug issue](https://github.com/opensearch-project/OpenSearch/issues/new?assignees=&labels=bug%2C+untriaged&projects=&template=bug_template.yml&title=%5BBUG%5D+%3Ctitle%3E) is a good example of what 
> ![image](https://github.com/opensearch-project/project-website/assets/28766727/692aa83c-7412-4786-a626-f15473b3db6e)

## Solution
**Specific changes**
- An emoji in the Name of the issue (🐛 Bug report)
- default assign the 'website update project' 
- text areas for user-entry, instead of free form user-entry
- dropdown menu for the website component that is affected. 

## Note
These changes will not affect how the issue is rendered to us, it only affects the issue-intake, and makes it more user friendly. 
See these three recent [BUG] reports from OpenSearch, and notice how there are no dropdowns or text-areas being rendered, it looks normal. 
- https://github.com/opensearch-project/OpenSearch/issues/14199
- https://github.com/opensearch-project/OpenSearch/issues/14193
- https://github.com/opensearch-project/OpenSearch/issues/14169

**Comment by nateynateynate** [comment]
Closed with #2993
