### ISSUE TITLE
Redesign -- Issue: Feature request

### ISSUE THREAD

**Issue by kaimmej** [opensearch-project/project-website#2963]
## Problem
**Better user experience when we add issues for our project.** I am suggesting simple changes - such as text areas, instead of raw markdown and drop-down menus for what component of the website it buggy. Also an emoji in title ->  🎆 Feature request

**Our current labeling is inconsistent**, some of our feature requests are [Website update] and others are [FEATURE] and others are unlabled. I suggest that we standardize this, and soft-enforce it by automatically applying the same label whenever a new feature issue is created. 
Not having consistency makes it harder to visually search for past feature updates, however there is the "enhancement" label that provides searching. 

## Example
[OpenSearch new feature issue](https://github.com/opensearch-project/OpenSearch/issues/new?assignees=&labels=enhancement%2C+untriaged&projects=&template=feature_request.yml&title=%5BFeature+Request%5D+%3Ctitle%3E) is a good example
> ![image](https://github.com/opensearch-project/project-website/assets/28766727/758f09cd-8787-4279-85ef-e7c6fbbc8386)

Also: 
- we could automatically assign the 'website-Update-Project' to new feature requests. These will still get the untriaged label, and so will still need to be seen, and prioritized, but it takes one step out of the process for our maintainers. Additionally, it seems like feature requests, and bug reports only go to the website-update-project.
- Validator "required=true" on the fields that we think deserve it.

**Additional context**
We do have "enhancement" as an active label, so maybe we dont need to include the Feature label in the title of the Issue. 
should [website update], and [FEATURE] be different labels? I could go either way on this.

**Comment by nateynateynate** [comment]
Closed via #2993
