### ISSUE TITLE
New blog post - updates about the CFP and OpenSearchCon schedule

### ISSUE THREAD

**Issue by dimwetoth** [opensearch-project/project-website#2997]
**Describe the blog post your would like to write**
This blog post will cover the schedule and CFP updates for OpenSearchCon North America.

**What is the title of the blog post?**
OpenSearchCon San Francisco - Schedule and CFP Updates

**Who are the authors?**
Daryll Swager

**What is the proposed posting date?**
Monday the 24th of June.

**What is the markdown of the post?**
# OpenSearchCon San Francisco - Schedule and CFP Updates

CTA BUTTON: Submit CFP (closing on 06/28!)
CTA BUTTON: Register Now

Hi everyone, we’re getting ready for [OpenSearchCon in San Francisco](https://opensearch.org/events/opensearchcon/2024/north-america/index.html) and are thrilled with the level of registrations and talk submissions. Here are a couple of updates about the conference schedule and the call for presentations:

First, the [call for presentations](https://opensearch.org/events/opensearchcon/2024/north-america/cfp.html) is still open until June 28th. We’ll be sending the anonymized submissions through a panel of judges to be scored, sorted, and turned into a high-quality session mix! Please get your submissions in before the deadline as it won’t be extended again.

Also, the conference schedule is forming up nicely and we thought we’d share what’s happening on all three days. Have a look:

### Tuesday, September 24

Opening day will have our main keynote speech, two session rooms running, and a couple of special events, including an evening reception with appetizers and beer/wine. This will be a day full with stuff to do pretty much until evening time.

**7:00am-8:50am:** Continental breakfast
**7:00am-5:00pm:** Registration open
**7:00am-5:00pm:** Exhibitor setup
**9:00am-9:50am:** Opening keynote by Eli Fisher
**10:00am-11:50am:** Partner round table
**10:00am-11:50am:** General sessions
**Noon-12:55pm:** Grab-and-go lunch
**1:00pm-4:00pm:** The Unconference
**1:00pm-5:00pm:** General sessions
**1:00pm-7:00pm:** Exhibitor area open
**5:00pm-7:00pm:** Opening reception

### Wednesday, September 25

Day 2 is the main session day of the conference. Sessions will be running in three rooms, all day, right up to the Search Party starting at 5pm. Don’t miss out on the celebration!

**7:00am-8:50am:** Continental breakfast
**7:00am-5:00pm:** Registration open
**9:00am-5:00pm:** Exhibitor area open
**9:00am-9:10am:** Opening remarks
**9:15am-11:55am:** Main stage sessions
**9:15am-11:55am:** General sessions (room 1)
**9:15am-11:55am:** General sessions (room 2)
**Noon-12:55pm:** Grab-and-go lunch
**1:00pm-5:00pm:** Main stage sessions
**1:00pm-5:00pm:** General sessions (room 1)
**1:00pm-5:00pm:** General sessions (room 2)
**5:00pm-7:00pm:** The search party!

### Thursday, September 26

Day three is dedicated to training, workshops, and a special event that one of our partners wants to try out. We’re still working out the fine grained details for some of these, but here’s the current schedule:

**7:00am-8:50am:** Continental breakfast
**7:00am-9:00am:** Registration open
**8:00am-5:00pm:** Search training
**9:00am-Noon:** OpenSearch workshop
**9:00am-Noon:** Capture the Flag
**Noon-12:55pm:** Grab-and-go lunch

### Additional OpenSearchCon Resources:

- [Register for OpenSearchCon](https://opensearch.org/events/opensearchcon/2024/north-america/register.html)
- [Submit a CFP](https://opensearch.org/events/opensearchcon/2024/north-america/cfp.html)
- [Book a Room at the Hotel](https://book.passkey.com/e/50823627)

**Comment by pajuric** [comment]
Closing this issue out.

**Comment by krisfreedain** [comment]
https://opensearch.org/blog/opensearchcon-san-francisco-schedule-and-cfp-updates/
