### ISSUE TITLE
Write a blog post for "Behind the scenes with OpenSearch: Understanding Index request cache through code"

### ISSUE THREAD

**Issue by kiranprakash154** [opensearch-project/project-website#2999]
**Describe the blog post you would like to write**
Understanding Indices Request Cache Through Code covering 
	- what is this cache
	- what is a key and value
	- what is a cleanupKey
	- lifecycle of entries
		- how a cache key is inserted
		- how a cache key is invalidated

**What is the title of the blog post?**
Behind the Scenes with OpenSearch: Understanding Indices Request Cache Through Code

**Who are the authors?**
@kiranprakash154 

**What is the proposed posting date?**
July 12

**Comment by nateynateynate** [comment]
Completed per #3370
