### ISSUE TITLE
Remove Django language in the footer

### ISSUE THREAD

**Issue by dimwetoth** [opensearch-project/project-website#3016]
### Describe the bug

Our site used to be a derivative of the Django website (we forked the design directly and gave them credit).  Our site is no longer anywhere close to being a derivative of the Django website. We diverged in July of 2023 so it's been about a year now since we haven't been a fork.

### Expected behavior

I would expect that we don't give credit to Django when we aren't a fork of that website anymore. I think we should remove the entire Django snippet from the footer and reclaim the vertical real-estate. Please remember to update the docs repo as well if you make this change.

### To Reproduce

1. Go to the footer on opensearch.org
3. Notice the out of date Django language at the bottom of the footer

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by nateynateynate** [comment]
Solved by #3157
