### ISSUE TITLE
[BUG] Footer is not consistent between pages. 

### ISSUE THREAD

**Issue by kaimmej** [opensearch-project/project-website#3035]
### Describe the bug

blog's footer mentions Elasticsearch
https://opensearch.org/blog/
![image](https://github.com/opensearch-project/project-website/assets/28766727/5bcf60dd-618c-4e09-817c-8db10a770491)

Normal footer does not
![image](https://github.com/opensearch-project/project-website/assets/28766727/5b6ae0b2-d44b-4df8-a73f-a37920d86543)

This is coming from _includes/footer_legal.html
line 2 has a templating script that checks whether a variable "notice" is set to true. And if so, we display the Elasticsearch disclaimer. 
![image](https://github.com/opensearch-project/project-website/assets/28766727/f453a3ed-9f82-4fb7-9167-797b8c063d3a)

### Expected behavior

Should this be here? I do not know. 
Why are we applying it to the blog page and not to other pages? 

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by nateynateynate** [comment]
We'll be spec'ing out a new footer. Let's not forget the content here.

**Comment by nateynateynate** [comment]
Solved by #3157
