### ISSUE TITLE
[Urgent Website Updates]: Update OpenSearchCon NA CFP Page to Reflect Closed

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#3038]
CFP closed on June 28, 2024 at 11:59pn EST. Update [OpenSearchCon NA page] (https://opensearch.org/events/opensearchcon/2024/north-america/index.html) reflect that the CFP is now closed and that we are no longer accepting submissions. 

Updated copy: 
What makes the community want to attend OpenSearchCon? Beyond the opportunity to network with peers and commune with passionate open sourcers, OpenSearchCon is where you come to hear compelling stories, learn differentiated use cases, and gain educational insights shared by our community. Our CFP for OpenSearchCon North America 2024 has closed, but you can still share your uses cases and innovations with the community by signing up to speak at an upcoming OpenSearch Community meeting [here](https://airtable.com/appiypj6lBSmFpRVu/pagW4jSDcTV6ecdwH/form): 

Kill the button for: Submit a Presentation

Timeframe: To be completed on Monday, July 1. 
CC: @kaimmej

**Comment by nateynateynate** [comment]
This has been completed.
