### ISSUE TITLE
[URGENT] Update OpenSearchCon NA CFP page 

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#3039]
Update OpenSearchCon NA CFP page on the website and kill the link to the Airtable form at the bottom of this page [here](https://opensearch.org/events/opensearchcon/2024/north-america/cfp.html). The CFP closed on June 28, 2024 at 11:59pm EST. 

Timeframe: ASAP
@kaimmej @nateynateynate

**Comment by nateynateynate** [comment]
All set.
