### ISSUE TITLE
Suggestion: Update new blog layout / cards to include year of post

### ISSUE THREAD

**Issue by luttonm** [opensearch-project/project-website#3044]
### Is your feature request related to a problem?
The new layout for the blog landing page only shows "Month DD" which makes it hard to evaluate older content (which may have come from a previous year)

### What solution would you like?
Add the year of the blog's posting in the card view, "Month DD, YYYY"

### What alternatives have you considered?
n/a

### Do you have any additional context?
If looking at older posts on deeper pages of the blog it is unclear that they are 2+ years old
![Screenshot 2024-07-02 at 2 04 08 PM](https://github.com/opensearch-project/.github/assets/135266860/3de4e8e6-bcc7-4375-bc26-5313b89fb949)

**Comment by nateynateynate** [comment]
Thanks @peternied, @dblock
