### ISSUE TITLE
[BUG] New features and bug issues are not being assigned automatically to the Website Update Project

### ISSUE THREAD

**Issue by kaimmej** [opensearch-project/project-website#3054]
### Describe the bug

When we create a new Feature, it should be assigned automatically to the Website Update Project, but it is not. 

The project name was hardcoded into the new issue 
<img src = "https://github.com/opensearch-project/project-website/assets/28766727/ed8cf7a7-3ea8-473d-af8c-4c8534780784" width=50% height=50%>

However on the right side of these new issues, we see that no Project has been assigned... 
<img src = "https://github.com/opensearch-project/project-website/assets/28766727/114f00d2-2351-4b4b-a667-634da8d03c76" width=50% height=50%>

Note that the Labels are being correctly assigned. 

Maybe it is because of the doublequote? Instead of singlequote? 

### Expected behavior

New issues should be automatically assigned to the website update project.

**Comment by nateynateynate** [comment]
#3060 merged.
