### ISSUE TITLE
Blog Post for match_only text field

### ISSUE THREAD

**Issue by rishabhmaurya** [opensearch-project/project-website#3056]
Blog post for [match_only_text](https://opensearch.org/docs/latest/field-types/supported-field-types/match-only-text/) field introduced in OpenSearch 2.12.

**Comment by pajuric** [comment]
@getsaurabh02 - Looks like there are some details missing here. Please update the issue and ping me.

**Comment by rishabhmaurya** [comment]
@pajuric I have added required details in the PR

**Comment by pajuric** [comment]
Blog is pushing live.
