### ISSUE TITLE
Hyperspace

### ISSUE THREAD

**Issue by YanivHyper-Space** [opensearch-project/project-website#3058]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Hyperspace

**Brief description of your business and what it does (50 words or less)**
Hyperspace is a cloud search database that leverages cloud hardware to enhance search speed and relevancy. Hyperspace uses a Search Processing Unit (SPU) virtual chip—a domain-specific architecture optimized for search tasks, to provide unmatched performance for real-time applications at scale, maintaining cost efficiency without compromising over logic complexity. 

**Name of your relevant product(s) or service for the OpenSearch audience**
Hyperspace lexical search, Hyperspace Hybrid search, Hyperspace vector search

**What OpenSearch technologies do you specialize in**
Is there an area of the project where your business specializes?
search, data security, data privacy

**Type of business**
MSP

**Home/main office location or address**
Home/main office location or address (if applicable)

**How can people contact you (email and phone)**
amits@hyper-space.io 

**Regions you serve**
North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia

**Industry specialization**
software and technology, fraud detection, Ad-tech

**Logo**
![HS_Logo_-_400x400](https://github.com/opensearch-project/project-website/assets/124336435/f7542eb2-95fb-4821-8815-43a0112c3028)

**Additional image**
N\A

**Links**
N\A

**Comment by pajuric** [comment]
@kaimmej and @nateynateynate - Partner page is ready for implementation.

**Comment by nateynateynate** [comment]
#3040
