### ISSUE TITLE
Adding Aryn to partner page

### ISSUE THREAD

**Issue by jonfritz** [opensearch-project/project-website#3070]
**NOTE: This is an issue template for new partner pages we are building. Existing partners can use them to submit information needed as we build out enhanced pages. New partners, please continue to use the process outlined here for the time being: https://opensearch.org/new-partner.html

**Organization name**
Aryn

**Brief description of your business and what it does (50 words or less)**
Aryn is an LLM-powered data preparation, processing, and analytics system for complex, unstructured documents like PDFs, HTML, presentations, and more. With Aryn, data engineers and data scientists can prepare data for GenAI and RAG applications, power high-quality document processing workflows, and run analytics on large document collections with natural language. 

**Name of your relevant product(s) or service for the OpenSearch audience**
Aryn makes it easy to prepare complex, unstructured data (PDFs, presentations, documents, and more) for hybrid search and retrieval-augmented generation (RAG) in OpenSearch. Aryn has two main components. First, documents are processed with the Aryn Partitioning Service, a serverless, GPU-backed endpoint for segmenting PDF documents, doing OCR, extracting tables and images, and more. Next, Aryn uses Sycamore, its Apache v2.0 open source document processing engine, to enrich, extract, transform, and load data into OpenSearch. Built for data engineers and data scientists, Sycamore provides a declarative dataflow abstraction called DocSets to make manipulating unstructured documents easy and scalable. Sycamore is also 100% open source with an Apache v2.0 license.

**What OpenSearch technologies do you specialize in**
Search, Analytics, GenAI

**Type of business**
Product/technology

**Home/main office location or address**
Mountain View, CA

**How can people contact you (email and phone)**
info@aryn.ai

**Regions you serve**
North America, South America, Europe, Middle East, Africa, Asia Pacific, Australia

**Industry specialization**
Business services, consumer services, education, energy and utilities, financial services, healthcare, media and entertainment, public sector, non-profit, retail, software and technology

**Logo**
See below in comments.

**Additional image**
Attach any additional image you would like to provide that showcase your business (product, technology, offices)

**Links**
Purpose-built AI model for document processing -  https://www.aryn.ai/post/new-open-source-ai-model-for-document-segmentation-and-unstructured-etl

**Comment by jonfritz** [comment]
<img width="497" alt="ArynLogo" src="https://github.com/user-attachments/assets/4e69ef33-85a3-41b3-9d66-90030584b80d">

**Comment by pajuric** [comment]
@nateynateynate @kaimmej - Please reload and re-create the page for Aryn.

**Comment by nateynateynate** [comment]
#3074
