### ISSUE TITLE
Using heuristic evaluation to inform the user experience strategy of a product

### ISSUE THREAD

**Issue by apasun** [opensearch-project/project-website#3077]
**Describe the blog post your would like to write**
This blog will cover what a heuristic evaluation is. How it can benefit cloud tooling vs. a website and more, the way to conduct a heuristic evaluation and best practices offered to the community

**What is the title of the blog post?**
Using heuristic evaluation to inform the user experience strategy of a product

**Who are the authors?**
Ray and Aparna

**What is the proposed posting date?**
July 19th; write up is ready; see quip

**Comment by pajuric** [comment]
Attached blog draft for review. @nateynateynate - Can you help move this into a PR for review? 
[UX Heuristics Blog Post - AS comments and ray additions.docx](https://github.com/user-attachments/files/16317326/UX.Heuristics.Blog.Post.-.AS.comments.and.ray.additions.docx)

**Comment by nateynateynate** [comment]
I'll have to create a community member profile for Ray Salas. Will reach out for details privately.

**Comment by nateynateynate** [comment]
Completed with #3091
