### ISSUE TITLE
New Github Blog Issue Template

### ISSUE THREAD

**Issue by nateynateynate** [opensearch-project/project-website#3086]

**Comment by kaimmej** [comment]
All blogs categorized
https://airtable.com/appuhlYisHkrQNKur/tblRFaMyTkLgTLMrx/viwBTJGZq6RZw2dq8?blocks=bipqfcA0la4Y8Pw32

**Comment by nateynateynate** [comment]
I believe this is waiting on input from @pajuric regarding fields required.

**Comment by nateynateynate** [comment]
In the interests of time we're going to push forward with what we have here and deal with additions / modifications on a case by case basis.

**Comment by nateynateynate** [comment]
https://github.com/opensearch-project/project-website/blob/main/README.md#writing-a-blog makes reference as well.
