### ISSUE TITLE
ReliaQuest

### ISSUE THREAD

**Issue by cgerecke94** [opensearch-project/project-website#3097]
### Organization Name

ReliaQuest

### Main office location

Tampa, FL

### What regions of the world do you serve?

North America, Europe

### Business description

ReliaQuest is the force multiplier of security operations. Our security operations platform, GreyMatter, automates detection, investigation, and response across cloud, endpoint, and on-premises tools and applications. GreyMatter is cloud-native, built on an open XDR architecture, and delivered as a service any time of the day, anywhere in the world. With over 700 customers worldwide and 1,000+ teammates working across six global operating centers, ReliaQuest is driving outcomes for the most trusted enterprise brands in the world. We exist to make security possible.

### Business Type

Professional Services

### URL

https://www.reliaquest.com/about-us/

### Contact Email

cgerecke@reliaquest.com

### Contact Phone

8136252589

### Industry Specialization

Software and Technology

### Product description

ReliaQuest GreyMatter is a security operations platform built on an open XDR architecture and designed to help security teams increase visibility, reduce complexity, and manage risk across their security tools, including on-premises, clouds, networks, and endpoints.

### OpenSearch Specialty

Security

### Logo

https://www.reliaquest.com/about-us/

### Favicon

https://www.reliaquest.com/about-us/

### Blog posts

https://www.reliaquest.com/about-us/

### Additional Information

We are looking to integrate our GreyMatter platform to Opensearch.

**Comment by pajuric** [comment]
@cgerecke94 - Thank you for filing to partner with OpenSearch. I'd like to schedule time in the next week or two for us to talk and provide you with some project resources. I'll send yu a quick email. ~ Patti

**Comment by pajuric** [comment]
Adding @kaimmej for assistance with building their page.

**Comment by cgerecke94** [comment]
Thanks so much! Our mutual customer, Lowe's, is looking to have this integration built sooner vs. later. Please let me know what days work best for a meeting. I would like to get the demo environment for testing up as soon as we are able! Looking forward to partnering!

**Comment by cgerecke94** [comment]
Hi, wanted to see if there was any update. Our mutual customer, Lowe's, is specifically looking for this integration. Happy to hop on a call if easier but would love to get the demo environment set up this week.

**Comment by nateynateynate** [comment]
Looks like you're live! https://opensearch.org/partners/reliaquest.html

**Comment by cgerecke94** [comment]
Hi @nateynateynate - we took a look at the playground environment - it looks like this will work for research, but I was wondering if you could direct me to a demo/simulator environment within our account page or if you are able to help get one set up. Thanks!

**Comment by cgerecke94** [comment]
Hi @nateynateynate, I'm sorry for the confusion. I'm talking to Patti to provide more information on Friday, but we are looking for a technology partnership to integrate OpenSearch with our GreyMatter platform (open XDR platform using apis to build the integration) - this allows our common customers to utilize one platform, providing a single pane of glass, for each technology they use.

More information about GreyMatter:

- A centralized place for all alerts from a customer's SIEM, endpoint, network, cloud, and business applications, while reducing noise
- A platform that unifies the security operations workflows including threat detection, investigation, and response
- Automation across DIR to drive consistency and scaleability of SecOps
