### ISSUE TITLE
[PARTNER] <Chronosphere Inc>

### ISSUE THREAD

**Issue by BiggBirdGuy** [opensearch-project/project-website#3100]
### Organization Name

Chronosphere

### Main office location

224 W 35th Street, Suite 500, PMB47, New York NY 10001

### What regions of the world do you serve?

North America, South America, Europe, Asia Pacific, Australia

### Business description

Chronosphere is the only observability platform that helps DevOps teams control the speed, scale, and complexity that comes with the technology and organizational changes of a cloud native world. Chronosphere helps engineers resolve infrastructure and application issues before they affect customer experiences and the bottom line. Trusted by the world’s most innovative brands, including DoorDash, Snap, and Zillow, Chronosphere helps teams reign in costs, improve developer productivity, increase customer satisfaction, and gain competitive advantage. 

### Business Type

(ISV) Independent Software Vendor

### URL

Chronosphere.io

### Contact Email

events@Chronosphere.io

### Industry Specialization

Software and Technology

### Product description

**[Telemetry Pipeline](https://chronosphere.io/platform/telemetry-pipeline/)**
Simplified, End-to-end Observability Pipeline. Chronosphere Telemetry Pipeline, from the creators of Fluent Bit and Calyptia, streamlines log collection, aggregation, transformation, and routing from any source to any destination.

 **[The Observability Platform with Control](https://chronosphere.io/platform/)**
Chronosphere is a cloud native observability platform that provides deep insights into every layer of your stack — from the infrastructure to the applications to the business.

### OpenSearch Specialty

Observability, Logs, Analytics

### Logo

Logo attached below

### Favicon

Favicon attached below

### Twitter

https://x.com/chronosphereio

### LinkedIn

https://www.linkedin.com/company/chronosphereio

### Additional Information

Logo
<img width="1253" alt="Chronosphere_Inc_Logo" src="https://github.com/user-attachments/assets/f5183a0a-c642-481e-827d-139d15c1facd">

Favicon
<img width="96" alt="Small Square Chronosphere Logo" src="https://github.com/user-attachments/assets/fd37f94b-ae54-49ca-a746-1dcff71eae5a">

**Comment by pajuric** [comment]
@kaimmej - Adding Jon for visibility

**Comment by nateynateynate** [comment]
Closed with #3105
