### ISSUE TITLE
[UPDATE] Tornis Tecnologia

### ISSUE THREAD

**Issue by tornis** [opensearch-project/project-website#3104]
Hey guys,
Just request the update of my logo, which is attached.
Thanks!

# Organization Name
Tornis Tecnologia

# Main office location
Rua 7, N 225 - Jardins das Américas 2 Etapa - Anápolis - GO - Brazil

# What regions of the world do you serve?
South America and Europe 

# Business description
Our company partners with leaders in the data search technology market, offering advanced OpenSearch training to help your team reach new levels of agility and decision accuracy.

# Business Type
(ISV) Independent Software Vendor and Consultancy 

# URL
www.tornis.com.br

# Contact Email
[tornis@tornis.com.br](mailto:tornis@tornis.com.br)

# Contact Phone
+55 61 9 99062592

# Industry Specialization
Software, Technology, 

# Product description
OpenSearch Specialty
Observability, Logs, Analytics, GenAI

# Logo
![tornis_logo_color_400x96](https://github.com/user-attachments/assets/478b7e4c-ba07-4251-85e2-e00c29d75058)
![tornis_logo_colorida](https://github.com/user-attachments/assets/fcb3add5-4083-4e05-bfbb-0451070e8ac5)
![tornis_logo_colorida_250x60](https://github.com/user-attachments/assets/bb6121e9-8186-441e-a129-07ead9e9358a)
![tornis_logo_colorida_google](https://github.com/user-attachments/assets/fd0e8e54-eb80-47fe-9ee0-31390cdc22d9)

# Favicon
Favicon attached below

# Additional Information

**Comment by nateynateynate** [comment]
Thanks for the submission! We'll get you added as soon as we can.

**Comment by nateynateynate** [comment]
All set.
