### ISSUE TITLE
[Blog] New Search Latency Features in OpenSearch

### ISSUE THREAD

**Issue by dzane17** [opensearch-project/project-website#3143]
**Describe the blog post your would like to write**
Feature announcement covering 3 search latency tracking capabilities:
1. Coordinator Nodes Stats
2. Search Request Phase Took Time
3. Search Request Slow Logs

**What is the title of the blog post?**
New Search Latency Features in OpenSearch

**Who are the authors?**
David Zane

**What is the proposed posting date?**
Sep 2024

**Comment by pajuric** [comment]
@dzane17 - Thanks for opening the issue.
