### ISSUE TITLE
[BUG] At least 1 OpenSearchCon NA page has incorrect language at the bottom

### ISSUE THREAD

**Issue by dimwetoth** [opensearch-project/project-website#3175]
### Describe the bug

This page: https://opensearch.org/events/opensearchcon/2024/north-america/capture-the-flag.html

it's about the capture the flag event, but the language at the bottom is referencing the Open Source Connections paid training.

### Expected behavior

I would expect some other language that Graylog has approved, or none at all, in this spot.

### To Reproduce

Go to the page linked in this issue and scroll to the bottom and read the text :)

### Additional Details

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by nateynateynate** [comment]
Solved with #3178
