### ISSUE TITLE
Update OSCon NA 2024 Session Schedule

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#3190]
Please make the following updates to the OpenSearchCon NA 2024 session schedule: 

1. Please move this session: 9/25 - Continental 1-3 - Session 11 - 4:40-5:10 - Sarthak Aggarwal/AWS
    - Move to: 9/25 - Continental 7-9 - Session 4 - 11:30-12:00pm - Sarthak Aggarwal/AWS

2. Please remove the following session/speaker: 9/25 - Continental 1-3  - Session 10 - 4:05-4:35pm - Bree Hoffman/Breefield

I will be combining sessions 10 & 11 into a single 40-minute spot and reassigning it to someone on the waitlist. 

@kaimmej

**Comment by nateynateynate** [comment]
Solved via #3221.
