### ISSUE TITLE
[RELEASE] Data Prepper 2.9.0

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/project-website#3202]
### Describe the bug

Data Prepper will release 2.9.0 on Aug 22, 2024. 

### Expected behavior

Data Prepper will release 2.9.0 on Aug 22, 2024. We will need support on:

 - [ ] Downloads page update on website (we will supply a PR with this changes)
 - [ ] Slack announcement
 - [ ] Forum announcement
 - [ ] Social media announcements

**Comment by dlvenable** [comment]
We are now planning on release on Wednesday Aug 28, with Aug 29 as the last date we'd want to have it released by.

**Comment by nateynateynate** [comment]
All set.
