### ISSUE TITLE
Data Prepper 2.9.0 release blog

### ISSUE THREAD

**Issue by kkondaka** [opensearch-project/project-website#3203]
**Describe the blog post your would like to write**
We are releasing Data Prepper 2.9.0. We will have a release blog accompany this.

**What is the title of the blog post?**
Announcing Data Prepper 2.9.0

**Who are the authors?**
* Krishna Kondaka
* David Venable
* Taylor Gray

**What is the proposed posting date?**
Aug 22, 2024

**Comment by pajuric** [comment]
@kkondaka @dlvenable @graytaylor0 - Please add me to the working doc for the blog when you have a chance. This way I can follow the progress and ensure it publishes on time.

**Comment by dlvenable** [comment]
@pajuric , I will be the author for this blog post and will attempt to get a PR submitted as soon as possible.

We are going to release on Aug 28, or the 29th, at the latest. I'd like to have the blog available at release if possible, but I also see it is somewhat short turn-around.

**Comment by dlvenable** [comment]
@pajuric , I created #3228 with the initial blog post.
