### ISSUE TITLE
[BUG] Speaker bio updates

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/project-website#3223]
### Describe the bug

Update to:

https://opensearch.org/community/members/mehdi-bendriss.html

Mehdi Bedriss

Mehdi is a Senior Engineer and the Engineering Manager of the NoSQL team in Canonical's Data Platform department. He has been actively involved in managing, designing, and developing the Charmed OpenSearch operator and all of its components and artifacts.

https://www.linkedin.com/in/mehdibendriss/ 

Profile image is already there, not sure how that became unlinked: 
https://github.com/opensearch-project/project-website/blob/main/assets/media/community/members/mbendriss.png 

---- and ---- 

https://opensearch.org/community/members/michelleanne-tabirao.html

Michelle Anne Tabirao 

Michelle is a Data Solutions Product Manager at Canonical and has been working for Charmed OpenSearch innovations. She also advocates for open source, inclusive tech, and digital literacy through her non-profit organization - [www.ulap.org](http://www.ulap.org/).

https://www.linkedin.com/in/michelle-tabirao/

**Comment by krisfreedain** [comment]
thank you @nateynateynate 🎉

**Comment by nateynateynate** [comment]
Solved via #3225
