### ISSUE TITLE
[BUG] OpenSearchCon NA - speaker not displaying on Speakers page

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/project-website#3233]
### Describe the bug

This talk: https://opensearch.org/events/opensearchcon/sessions/the-future-of-ingestion-is-streaming.html 

Andriy Redko does not seem to be listed on the speakers page
https://opensearch.org/events/opensearchcon/2024/north-america/speakers/index.html

### Expected behavior

Expect to see Andriy Redko listed:

![Screenshot 2024-08-27 at 10 23 47 AM](https://github.com/user-attachments/assets/5320413b-4a76-4466-9c08-6c175a4d85b3)

**Comment by nateynateynate** [comment]
Thanks Kris!

**Comment by nateynateynate** [comment]
Solved via #3230

**Comment by kaimmej** [comment]
Thanks Nate!
