### ISSUE TITLE
docker-compose quickstart documentation security SNAFU

### ISSUE THREAD

**Issue by bwalsh** [opensearch-project/project-website#324]
Hi.
Thanks for a great product.

I attempted the `The best way to try out OpenSearch is to use Docker Compose. ` path.

Unfortunately, the instructions imply that a default security configuration is in place.

However, it appears that security still needs to be setup.

```
opensearch-node2         | [2021-09-20T17:51:05,880][ERROR][o.o.s.a.BackendRegistry  ] [opensearch-node2] Not yet initialized (you may need to run securityadmin)
opensearch-node1         | [2021-09-20T17:51:05,882][ERROR][o.o.s.a.BackendRegistry  ] [opensearch-node1] Not yet initialized (you may need to run securityadmin)
```

see: 

* https://opensearch.org/downloads.html#docker-compose
* https://github.com/opensearch-project/project-website/blob/main/_includes/downloads/opensearch-docker.markdown

**Comment by stockholmux** [comment]
@bwalsh That's odd. I can't seem to recreate this issue and security is in place for me.

**Comment by stockholmux** [comment]
Can you try standing up the `docker-compose` again?

**Comment by bwalsh** [comment]
Thank you.  I deleted all previous images and re pulled; all went as expected
