### ISSUE TITLE
Updates/Edits to OSCon NA 2024 Sessions

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#3264]
Please make the following edits/changes to the OSCon NA sessions here: https://opensearch.org/events/opensearchcon/2024/north-america/sessions/index.html

### 

**Speaker: Rohit Nair**
**Talk Title: A deep dive into OpenSearch Serverless**
**Details: Continental 1-3 on 9/25 from 4:40pm-5:20pm**
Add:

* For the headshot – you can use my phonetool photo https://drive.corp.amazon.com/documents/rohinair@/de07930dc3d74c2eb107136c848766ef-CROPPED_DOWNLOADABLE.jpeg
* “Rohit Nair is a Software Development Engineer at AWS currently working on OpenSearch Serverless. He has previously worked on areas like UltraWarm storage for Amazon OpenSearch Service and Amazon Kinesis Data Streams. He loves working at the intersection of distributed systems, scale and performance”
* I’m not active on Linkedin or Github - no links required

* * *
**Speaker[: Ramesh Kumar Manickam](mailto:RameshKumar.Manickam@transunion.com) of Transunion**
**Talk Title: Scaling Operational Intelligence into Business Intelligence using OpenSearch & GenAI for global rollouts**
**Details: Continental 7-9 on 9/25 from 4-4:40pm**
Add: 

* Co-presenter - Mohanraj Vanjiappan [Mohanraj.Vanjiappan@transunion.com](mailto:Mohanraj.Vanjiappan@transunion.com)
* Title: Senior Engineering Manager
* Company: TransUnion Global Capability Center Bangalore
* Bio: Working as a Senior Engineering Manager At TransUnion Global Capability Center Bangalore. Solving problems in the domain of Risk & Fraud by leveraging cutting edge Technologies in digital landscape. Having 16+ years of IT Industry experience with hands on exposure to Java, Microservices, Google Clod Platform, Python, Data Science. Working in OpenSearch APIs, leveraging it to the fullest extend in the past couple of years.

* * *
Update Jon Handler’s presentation: https://opensearch.org/events/opensearchcon/sessions/multitenancy-for-all-workloads.html - as he is going to give a different talk. 

**New title:** How AI/ML is changing information retrieval

**Abstract:** When we work with information systems, we capture information in text and find information with text queries. Advances in AI have made it possible to move from word-to-word matching to something like meaning-to-meaning matching. Learn how search and OpenSearch unlock the meaning in your information. This session is foundational, covering why we search, and how we search to retrieve the best results. I will cover the core search algorithm, BM25 scoring, vectors (dense and sparse), LLMs, embedding generation and the neural and kNN plugins, exact, and approximate scoring.

**Comment by pajuric** [comment]
CC: @kaimmej

**Comment by nateynateynate** [comment]
On it. Thanks @pajuric.

**Comment by nateynateynate** [comment]
> Co-presenter - Mohanraj Vanjiappan [Mohanraj.Vanjiappan@transunion.com](mailto:Mohanraj.Vanjiappan@transunion.com)

@pajuric Can I get a job title / bio / headshot of this person so I can create their community member profile?
