### ISSUE TITLE
Do we have plan to do a patch release for OpenDistro?

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/project-website#328]
1. What's the plan to deprecate OpenDistro. 
2. Do we have plan to do patch release for OpenDistro plugins? I think there're still people using them.

Is this repo the right place to put this type of issue?

**Comment by stockholmux** [comment]
@dblock We're likely to have more updates on this subject later this week, maybe next. I'll hold until then.

**Comment by stockholmux** [comment]
This has been addressed in https://github.com/opendistro/for-elasticsearch#186
