### ISSUE TITLE
Update on OpenSearch clients

### ISSUE THREAD

**Issue by elfisher** [opensearch-project/project-website#329]
**Describe the blog post your would like to write**
Write a blog that summarizes current status on clients and highlight where to download the published clients and how to get started.

**What is the title of the blog post?**
OpenSearch Clients Update - Python, Go, and JS are live!

**Who are the authors?**
@elfisher 

**What is the proposed posting date?**
9/30/2021

**Comment by stockholmux** [comment]
@elfisher Could you update this issue with this template:

https://github.com/opensearch-project/project-website/blob/main/.github/ISSUE_TEMPLATE/blog_post.md

**Comment by elfisher** [comment]
Yup!

**Comment by elfisher** [comment]
Resolved by https://github.com/opensearch-project/project-website/pull/339
