### ISSUE TITLE
[Feature Request] Project Roadmap -> Navbar

### ISSUE THREAD

**Issue by kaimmej** [opensearch-project/project-website#3292]
### Is your feature request related to a problem? Please describe

Add project roadmap back into the navbar. 
https://github.com/orgs/opensearch-project/projects/220

### Describe the solution you'd like to see

Maybe into documentation?

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/amistrn), [4](https://github.com/krisfreedain)]

**Comment by dblock** [comment]
@kaimmej Want to PR this?

**Comment by kaimmej** [comment]
I can take this yes. 
I should have a PR later this week.

**Comment by nateynateynate** [comment]
Closed per #3362
