### ISSUE TITLE
[PARTNER] Lucenia

### ISSUE THREAD

**Issue by nknize** [opensearch-project/project-website#3304]
### Organization Name

Lucenia

### Main office location

San Francisco, CA

### What regions of the world do you serve?

Global

### Business description

Lucenia is an enterprise search engine based on Lucene, the same open source library that powers Elasticsearch, and founded by the original creator of Amazon's OpenSearch (now OpenSearch Software Foundation).  It's an on-premise alternative that autoscales to any cloud provider only when needed, saving the largest enterprises millions of dollars in compute and storage costs.

### Business Type

(MSP) Managed Service Provider, (ISV) Independent Software Vendor, Training

### URL

https://lucenia.io

### Contact Email

info@lucenia.io

### Contact Phone

‪(415) 234-0752‬

### Industry Specialization

Software and Technology, Business Services, Education, Government, Public Sector

### Product description

Search - hybrid data and hybrid cloud search, built with cloud native best practices to "do more with less" without vendor control or vendor lock-in.
Analysis - petabyte scale analytics that integrates with existing data, eliminating any indexing requirements.
Auto-scale -  escape the shackles of the cloud and use it for what it's good for, "borrowing compute" by spilling only when needed.

### OpenSearch Specialty

Search, Logs, Analytics, Machine Learning & AI, GenAI

### Logo

https://lucenia.io/wp-content/uploads/2024/09/Lucenia_Logo_Stacked.png

### Favicon

https://lucenia.io/wp-content/uploads/2024/09/Asset-66192darklogo.png

### Twitter

https://x.com/luceniaio

### LinkedIn

https://www.linkedin.com/company/lucenia/

### Facebook

https://www.facebook.com/lucenia.io/

### Blog posts

1. https://lucenia.io/2024/09/06/getting-started-with-lucenia-in-five-easy-steps/
2. https://lucenia.io/2024/08/29/when-do-i-need-lucenia/
3. https://lucenia.io/2024/08/23/sneak-peek-an-exclusive-look-into-lucenia-0-1-for-self-hosted-search/

**Comment by pajuric** [comment]
@nknize - Thanks for partnering with the project. I look forward to working with you again.

**Comment by pajuric** [comment]
@kaimmej @nateynateynate - Please push this one live.
