### ISSUE TITLE
[BUG] The new documentation header has the wrong Benchmark URL and main doc text

### ISSUE THREAD

**Issue by kolchfa-aws** [opensearch-project/project-website#3306]
### Describe the bug

Two problems:
1. Instead of pointing to the documentation, the new Documentation > Benchmark menu option points to opensearch/benchmarks
2. The main doc text says "What is OpenSearch?"

### Expected behavior

1. The link to the Benchmark documentation should be https://opensearch.org/docs/latest/benchmark/
2. The text with the link https://opensearch.org/docs/latest/about/ should say "OpenSearch and Dashboards" instead of "What is OpenSearch?"

### To Reproduce

Go to opensearch.org and open the Documentation menu

**Comment by nateynateynate** [comment]
@kaimmej - got a sec for this one?

**Comment by dblock** [comment]
[Catch All [Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta),  [3](https://github.com/krisfreedain),  [4](https://github.com/lukas-vlcek/)]

Is this fixed in #3317? Close?

**Comment by kolchfa-aws** [comment]
Fixed by #3317
