### ISSUE TITLE
Add co-presenter & update talk description for Coursera session at OpenSearchCon NA

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#3314]
Please add update this OpenSearchCon session: https://opensearch.org/events/opensearchcon/sessions/enabling-a-scalable-ml-driven-search-experience-at-coursera.html

**Please update the talk description to:** 
Join us as we share Coursera’s experience of migrating to OpenSearch, impacting over 5 million monthly active users. In this presentation, we’ll cover the key decisions and challenges we encountered, including the integration of vector search capabilities, and our choice to leverage Coursera’s in-house ranking platform. We’ll also discuss how we conducted offline and online evaluation experiments to ensure a smooth transition and maintain search quality.

We’ll provide a detailed look at our approach to light and heavy ranking, as well as the load testing and performance tuning that were essential to optimizing our search infrastructure. Learn about the results of our migration efforts, including improvements in search accuracy, system performance, and user satisfaction. This session aims to offer practical insights and lessons learned for anyone interested in search technology and large-scale system migrations.

**Add co-presenter:**
Name: Karan Singh
Email - [ksingh@coursera.org](mailto:ksingh@coursera.org)
Title - Senior Software Developer
Bio - https://www.linkedin.com/in/karanyyz/: 

Karan Singh is a Senior Backend Software Engineer at Coursera. 

![Unknown-1](https://github.com/user-attachments/assets/5b474729-20cb-45ce-96d6-3f39666126df)

**Comment by pajuric** [comment]
@kaimmej - Please help with adding this last co-presenter

**Comment by dblock** [comment]
[Catch All [Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta),  [3](https://github.com/krisfreedain),  [4](https://github.com/lukas-vlcek/)]

**Comment by dblock** [comment]
Was this done in #3317? Close?
