### ISSUE TITLE
OpenSearchCon NA 24 - Session Edits 

### ISSUE THREAD

**Issue by pajuric** [opensearch-project/project-website#3328]
Please update the following sessions using the info provided below: 

1)Session link: https://opensearch.org/events/opensearchcon/sessions/airbnb-embedding-platform.html
Update time: 10:00AM to 10:40AM

2)Session link: https://opensearch.org/events/opensearchcon/sessions/youve-deployed-user-behavior-insights-to-understand-your-users-now-what.html
Update time: 10:45AM to 11:25AM

3)Session link: https://opensearch.org/events/opensearchcon/sessions/exploring-opensearch-python-and-serverless-crafting-efficient-and-modern-search-applications.html
Update time: 11:30AM  to 12:00PM

4)Session link:https://opensearch.org/events/opensearchcon/sessions/building-ai-models-with-opensearchs-user-behavior-insights.html
Update time: 10:45AM to 11:25AM
Update room: Continental 7-9

**Comment by pajuric** [comment]
@kaimmej - These should be the final session edits. Once this is done, we'll want to run a report to make sure they are all correct.

**Comment by dblock** [comment]
[Catch All [Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta),  [3](https://github.com/krisfreedain),  [4](https://github.com/lukas-vlcek/)]
