### ISSUE TITLE
Ensure DCO Workflow Check

### ISSUE THREAD

**Issue by peternied** [opensearch-project/project-website#334]
Coming from https://github.com/opensearch-project/project-meta/issues/17

A Developer Certificate of Origin is required on commits in the OpenSearch-Project.

See [doc.yml](https://github.com/opensearch-project/.github/blob/main/workflow/dco.yml) for an example workflow.  Ensure CONTRIBUTING.md to has a section on the DCO per the [project template](https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin). 

- [x] DCO Check Workflow
- [x] CONTRIBUTING.md DCO Section

**Comment by stockholmux** [comment]
@peternied No DCO in this repo due to a different license (BSD, inherited from forked project).

**Comment by dblock** [comment]
@stockholmux How does the BSD license relate to (not) needing developers to do DCO?

**Comment by CEHENKLE** [comment]
@stockholmux Are you running this down with OSPO, or do you need a hand?

Thanks!
/C

**Comment by stockholmux** [comment]
@CEHENKLE Yup. On it.
