### ISSUE TITLE
[Feature Request] Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [opensearch-project/project-website#3350]
### Is your feature request related to a problem? Please describe

Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing OpenSearch application as shown [here](https://elest.io/open-source/opensearch). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

### Describe the solution you'd like

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/opensearch)

### Related component

Other

**Comment by nateynateynate** [comment]
Thanks for your submission @kaiwalyakoparkar! We do our best to be vendor agnostic here at OpenSearch, so I have to agree with @dblock here. Let's get you on our partner page on an even playing field with the rest of the partners. 

The best way to do that is to fill out a PR [here.](https://github.com/opensearch-project/project-website/issues/new?assignees=&labels=enhancement%2C+untriaged&projects=opensearch-project%2FWebsite+Update+Project%2Copensearch-project%2FPartner+Updates+and+Additions&template=partner_add_new_partner.yml&title=%5BPARTNER%5D+%7B%7B+Company+name+%7D%7D+)
