### ISSUE TITLE
[BLOG] Session Spotlight - Keynote Address at OpenSearchCon North America 2024

### ISSUE THREAD

**Issue by luttonm** [opensearch-project/project-website#3373]
### Describe the blog post

This is the first in a series of posts highlighting the most important sessions from OpenSearchCon North America 2024. This post covers the keynote address on the first day.

### Expected Title

Session Spotlight - Keynote Address at OpenSearchCon North America 2024

### Authors Name

Matt Lutton

### Authors Email

mlutton@steyer.net

### Blog Post Category

community

### Target Publication Date

10/11/2024

**Comment by luttonm** [comment]
[2024-10-07-Session-Spotlight-OpenSearchCon-Keynote.md.txt](https://github.com/user-attachments/files/17318952/2024-10-07-Session-Spotlight-OpenSearchCon-Keynote.md.txt)

**Comment by luttonm** [comment]
Second try

[2024-10-07-Session-Spotlight-OpenSearchCon-Keynote.md](https://github.com/user-attachments/files/17318957/2024-10-07-Session-Spotlight-OpenSearchCon-Keynote.md)

**Comment by pajuric** [comment]
# Session Spotlight - Keynote Address at OpenSearchCon North America 2024

authors:
 - mlutton
date: 2024-10-07
categories:
 - community-updates
meta_keywords: 
meta_description: 
YoutubeID: WPVGfWoR0B8
excerpt: 
has_math: false
has_science_table: false


Whether or not you were able to join us in San Francisco for OpenSearchCon North America 2024 now is a fantastic time to catch up with recordings of the sessions. In our first Session Spotlight we’re bringing you back to the kickoff of the conference on September 24th, 2024. 

The Opening Keynote for OpenSearchCon North America 2024 was given by Eli Fisher, Senior Manager of Project Management at AWS for OpenSearch, alongside two very special guests: Anupam Chaturvedi, Engineering Manager for Acrobat GenAI Services at Adobe, and Jim Zemlin, Executive Director of the Linux Foundation. 

{% include youtube-player.html id=page.YoutubeID %}

In this keynote Eli Fisher outlines the history of the OpenSearch Project from inception to this momentous occasion of joining the [Linux Foundation](https://www.linuxfoundation.org/) as the [OpenSearch Software Foundation]([http://foundation.opensearch.org](http://foundation.opensearch.org/)) in September 2024. Anupam Chaturvedi also dives in to the exciting use case of GenAI-assisted search in PDF documents at [Adobe](https://www.adobe.com/acrobat/generative-ai-pdf.html), enabled by the powerful vector search capabilities of OpenSearch. And finally, Jim Zemlin makes the case for the bright future of open source software and highlights the strength of partnering with projects like OpenSearch. 

Follow the [OpenSearch Project on Youtube](https://www.youtube.com/@OpenSearchProject) to find other recordings of OpenSearchCon presentations going back to our original user conference in 2022, including this year's OpenSearchCons in Europe and India.











* * *
* * *

**Comment by kaimmej** [comment]
@pajuric please assign to me once you have input the metakeywords and metadescription

**Comment by pajuric** [comment]
@kaimmej - Will do. I am guessing that you will be building Matt's profile and opening the PR?

**Comment by kaimmej** [comment]
@pajuric yes and yes!

**Comment by pajuric** [comment]
@kaimmej - Meta is below: 

_meta_keywords:_   OpenSearchCon, OpenSearch Project, Adobe, Linux Foundation, GenAI, Vector Search, OpenSearch Software Foundation

_meta_description:_ Watch the OpenSearchCon North America 2024 keynote address and hear from featured speakers from OpenSearch, Adobe, and the Linux Foundation as they discuss uses cases along with the project’s history and future.

**Comment by pajuric** [comment]
Closing this one since it's live.
