### ISSUE TITLE
[BLOG] Tiered caching in OpenSearch

### ISSUE THREAD

**Issue by sgup432** [opensearch-project/project-website#3374]
### Describe the blog post

This will cover high level overview of Tiered caching in OpenSearch, its benefits and how can users use it. It will also includes details like in what cases it makes sense to use it and what are the things user need to keep in mind.

### Expected Title

Tiered caching in OpenSearch

### Authors Name
Sagar Upadhyaya
Ankit Jain
Peter Alfonsi
Kunal Khatua
Fanit Kolchina

### Authors Email
sagar.upadhyaya.121@gmail.com

### Target Draft Date

10/11/2024

### Blog Post Category

technical

### Target Publication Date

10/17/2024

**Comment by pajuric** [comment]
@sgup432 - Thanks for opening the blog issue. Please go back and edit the issue and provide the missing details.
