### ISSUE TITLE
[BLOG] <Introduction of new OpenSearch website search>

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/project-website#3379]
### Describe the blog post

This blog post will cover some new changes made to the OpenSearch.org website search infrastructure to fix some of the existing search issue such as duplicate search results.
We will also introduce a new search results landing page to display search results with a filter option to restrain the search file type or documentation version.

### Expected Title

Introduction of new OpenSearch website search

### Authors Name

Zelin Hao

### Authors Email

https://github.com/zelinh

### Target Draft Date

10/11/2024

### Blog Post Category

technical

**Comment by dblock** [comment]
[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta)]

**Comment by zelinh** [comment]
The blog post is out. We should be able to close this issue.
