### ISSUE TITLE
Building OpenSearch 1.1 Distributions using Automation

### ISSUE THREAD

**Issue by dblock** [opensearch-project/project-website#340]
**Describe the blog post your would like to write**

This post details how the OpenSearch project produces reliable and repeatable distributions.

**What is the title of the blog post?**

Building OpenSearch 1.1 Distributions using Automation

**Who are the authors?**

dblock@

**What is the proposed posting date?**

2021/09/30

**Comment by dblock** [comment]
Blog post is https://github.com/opensearch-project/project-website/pull/293

**Comment by stockholmux** [comment]
@dblock This can be published on 2021/10/04 - would that work?

**Comment by dblock** [comment]
Works for me. LMK if you want me to do anything else.

**Comment by stockholmux** [comment]
Closed by #351
