### ISSUE TITLE
[RELEASE] Release Data Prepper 2.10.1

### ISSUE THREAD

**Issue by dlvenable** [opensearch-project/project-website#3400]
### Is your feature request related to a problem? Please describe

We have a patch release of Data Prepper that we will release on Monday Oct 21, 2024

### Describe the solution you'd like to see

We will provide a PR with the downloads updates.

### Describe alternatives you've considered

N/A

**Comment by nateynateynate** [comment]
All set! 

#3394.

**Comment by dlvenable** [comment]
@nateynateynate , This is 2.10.1 which is a patch release. So it is not yet completed.
