### ISSUE TITLE
[PARTNER] Elestio

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [opensearch-project/project-website#3406]
### Organization Name

Elestio

### Main office location

Dublin, Ireland

### What regions of the world do you serve?

Global

### Business description

Elestio is a managed cloud hosting platform that simplifies deploying, scaling, and managing applications. It supports a variety of services like web applications, databases, and microservices. Elestio offers pre-configured environments for popular open-source software, allowing users to launch these services without worrying about the underlying infrastructure.

### Business Type

(MSP) Managed Service Provider

### URL

https://elest.io/

### Contact Email

contact@elest.io

### Industry Specialization

Software and Technology, Business Services, Consumer Services

### Product description

Elestio offers fully managed OpenSearch hosting solutions, making it easy for users to deploy, manage, and scale OpenSearch clusters. We provide automatic backups, real-time monitoring, and a user-friendly dashboard for managing data and search functionality. Our platform ensures high availability and performance, making OpenSearch management seamless for users.

### OpenSearch Specialty

Search, Observability, Analytics

### Logo

https://elest.io/images/elestio.svg

### Favicon

https://media.licdn.com/dms/image/v2/C4D0BAQEzgLoo5epXyA/company-logo_200_200/company-logo_200_200/0/1648970713766/elestio_logo?e=2147483647&v=beta&t=7nuO5DHShJRFRCxTiXFMdfSz4o54dRiPdouPl4NSi_I

### Twitter

https://x.com/elest_io

### LinkedIn

https://www.linkedin.com/company/elestio/

**Comment by pajuric** [comment]
@kaimmej - FYI

**Comment by kaiwalyakoparkar** [comment]
Hey @pajuric, Just sent an email. Looking forward to it 🙌

**Comment by krisfreedain** [comment]
@kaimmej - can you begin working on this one?
