### ISSUE TITLE
 OpenSearch Users Activity Analysis

### ISSUE THREAD

**Issue by skkosuri-amzn** [opensearch-project/project-website#364]
**Describe the blog post your would like to write**
OpenSearch audit logs maintain a record of user activity of the cluster. This blog provides details on OpenSearch audit logs,  creating new dashboards that gets insights into Users activity, a set of OpenSearch monitors that create alerts based on abnormal User activity, and a set of Saved Queries for ad-hoc exploration. 

**What is the title of the blog post?**
 OpenSearch Users Activity Analysis

**Who are the authors?**
TBD

**What is the proposed posting date?**
12.01.2021

**Comment by stockholmux** [comment]
@skkosuri-amzn sounds good- 2021-11-01 is a good posting date.

**Comment by stockholmux** [comment]
@skkosuri-amzn How is this going?

**Comment by stockholmux** [comment]
@skkosuri-amzn That's fine, please edit your initial issue to reflect that.
