### ISSUE TITLE
[discuss] Add explicit 'Downloads' link to opensearch.org

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/project-website#383]
**Is your feature request related to a problem? Please describe.**
Currently we have to click the 'Get started' link to get the downloads page and it can be very confusing for some users.

**Describe the solution you'd like**
Replace 'Get started' with 'Downloads' link on the top navigation menu in opensearch.org. 

**Describe alternatives you've considered**
Clicking 'Get started' to get to the downloads page

**Additional context**

**Comment by dblock** [comment]
I was thrown off by “get started” being downloads; I think we want both

**Comment by stockholmux** [comment]
3 PRs are ready - let's continue discussion of options on the forums:

https://discuss.opendistrocommunity.dev/t/download-or-get-started-on-opensearch-org/7317/5?u=searchymcsearchface

**Comment by stockholmux** [comment]
closed by #669
