### ISSUE TITLE
How to migrate from Elasticsearch to OpenSearch - blog by Opster team

### ISSUE THREAD

**Issue by ElishevaOpster** [opensearch-project/project-website#414]
**Describe the blog post your would like to write**
This post will cover the various methods that can be used to migrate from ES to OS.

**What is the title of the blog post?**
How to migrate from Elasticsearch to OpenSearch

**Who are the authors?**
Gustavo - The Opster Team

**What is the proposed posting date?**
November 1st

**Comment by ElishevaOpster** [comment]
Hi @stockholmux , we're not quite sure how you'd like us to put the blog post in a PR. Should we create a new file inside "posts" and name a branch?

Is it an option to just provide you with the google doc, or the full article in HTML format? We have the full article here, with a no index tag: https://opster.com/elasticsearch-glossary/migrate-from-elasticsearch-to-opensearch/
We will update it later on to be indexed after it is published on OpenSearch.org.

**Comment by stockholmux** [comment]
Hey @ElishevaOpster. The strong preference is to have you add the post yourself as it properly attributes the blog post to you in version control and you get to have formatting the way you want it. We've helped folks in the past but it becomes a lot of back and forth, it's quicker and cleaner if you take it yourself.

The basic flow is to fork the website, create a feature branch, add the post (it's all markdown and yaml), then do a PR. A good example of a PR for a blog post is this one: 
https://github.com/opensearch-project/project-website/pull/419/files
