### ISSUE TITLE
Add mermaid.js to Jekyll site generator

### ISSUE THREAD

**Issue by giocollina** [opensearch-project/project-website#415]
**Is your feature request related to a problem? Please describe.**
If you write technical blog posts you often have the requirement to add diagrams for clarification / visualisation. This can be flow charts, sequence diagrams and the like. Drawing them manually using a tool like draw.io is tedious. Especially if you need to make changes to an already existing diagram.

**Describe the solution you'd like**
I propose to add the [mermaid.js](https://mermaid-js.github.io/mermaid/#/) library to the Jekyll site generator for the website and also the documentation. The library makes it possible to "describe" diagrams in Markdown, and then render it as SVG.

It seems there is also a [Jekyll plugin for mermaid](https://github.com/jasonbellamy/jekyll-mermaid).

**Describe alternatives you've considered**
Using traditional tools like draw.io, creately, gliffy etc.

**Additional context**
I did not have a chance yet to explore how easy / difficult it would be to add mermaid to the existing Jekyll based site structure. However, if this is something of interest, I'd be happy to invest some time and eventually submit a PR. Let me know what you think!

**Comment by stockholmux** [comment]
@giocollina I'm going to close this as stale after many months of inactivity. If you get around to putting Mermaid in a PR, feel free to reopen.
