### ISSUE TITLE
Publish the JDBC and ODBC driver artifacts in OpenSearch download page

### ISSUE THREAD

**Issue by chloe-zh** [opensearch-project/project-website#429]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
We would like to release the OpenSearch JDBC and ODBC drivers for the OpenSearch users to connect their clusters with the BI tools like PowerBI, Tableau etc., the release will be compatible with both OpenSearch and legacy ODFE clusters.

**Describe alternatives you've considered**
Just like the ODFE releases https://opendistro.github.io/for-elasticsearch/downloads.html#all, we would like to release it to the OpenSearch artifact storage, and publish the link in the OpenSearch download page: https://opensearch.org/downloads.html

**Additional context**
JDBC and ODBC release issue: https://github.com/opensearch-project/opensearch-build/issues/794

**Comment by stockholmux** [comment]
@chloe-zh Can you provide an update on this?

**Comment by chloe-zh** [comment]
> @chloe-zh Can you provide an update on this?

@anirudha

**Comment by stockholmux** [comment]
Closed by #635
