### ISSUE TITLE
Create new section for OpenSearch drivers on Downloads/Getting Started page.

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/project-website#431]
**Is your feature request related to a problem? Please describe.**
The current downloads page doesn't have a section for downloading drivers such as ODBC/JDBC and potentially clients libs.

**Describe the solution you'd like**
A section to hold these artifacts with a heading (TBD) and a descriptive paragraph (TBD).

**Describe alternatives you've considered**
A single section to hold tools (opensearch-cli) and drivers but this would potentially disrupt the URL structure.

**Comment by elfisher** [comment]
> Current headings on the downloads page:
> 
> * Try OpenSearch with Docker Compose
> * OpenSearch
> * OpenSearch Dashboards
> * Ingest Tools
> * Command Line Tools
> * Minimal Distributions
> 
> We'll likely need to add another. Open to suggestions.

How about clients? We could link to clients respective package manager downloads too (NPM, PyPI, etc...)

I am starting to wonder if we should have a clients and tools section that combines some of these categories (cli, clients, ingest tools, etc...).

**Comment by stockholmux** [comment]
@elfisher I'm open to it, although I don't want to create a grab bag section. I think you run the risk of confusing folks with "one of these things is not like the rest."

To me language clients, CLI tools (opensearch-cli, perftop), and ingest tools (data prepper, logstash) all have their own section.

**Comment by elfisher** [comment]
> @elfisher I'm open to it, although I don't want to create a grab bag section. I think you run the risk of confusing folks with "one of these things is not like the rest."
> 
> To me language clients, CLI tools (opensearch-cli, perftop), and ingest tools (data prepper, logstash) all have their own section.

That makes sense.

**Comment by stockholmux** [comment]
Current thinking on sections & order

- Try OpenSearch
- OpenSearch
- OpenSearch Dashboards
- Command Line Tools
- Ingest Tools
- Client Libraries and Drivers (@elfisher ODBC/JDBC - thoughts on call that a "driver"?)
- Minimal Distributions


As far as clients, my current thinking is that we treat each language as a platform. So each language is part of a pull down.

**Comment by elfisher** [comment]
> Current thinking on sections & order
> 
> * Try OpenSearch
> * OpenSearch
> * OpenSearch Dashboards
> * Command Line Tools
> * Ingest Tools
> * Client Libraries and Drivers (@elfisher ODBC/JDBC - thoughts on call those a "driver"?)
> * Minimal Distributions
> 
> As far as clients, my current thinking is that we treat each language as a platform. So each language is part of a pull down.

"Drivers" sounds good!

**Comment by stockholmux** [comment]
@elfisher putting this together, I think we have quite a bit of writing to do:

![Screen Shot 2021-11-16 at 3 09 52 PM](https://user-images.githubusercontent.com/1152927/142074260-0c383909-7787-4c71-a637-3fe981c95f6d.png)

1) Dummy text starting with "Fusce": This should be the intro to the category
2) Dummy text starting with "Mauris": The paragraph describing ODBC driver
3) Dummy text starting with "Curabitur": The paragraph describing JDBC driver
4) The Dummy text starting with "Quisque": The paragraph describing _each_ client. As an example, we'll need one for opensearch-py, opensearch-go, and opensearch-js each.

**Comment by elfisher** [comment]
@stockholmux, agreed, we do have quite a bit of writing to do. I put some suggestions to start with inline below. For the clients I'd like to use similar text as much as possible and just swap out necessary details.

> 1. Dummy text starting with "Fusce": This should be the intro to the category

OpenSearch provides client libraries for several programming languages and drivers, like ODBC and JDBC, that let you integrate OpenSearch with your applications, business intelligence software and other tools.

> 2. Dummy text starting with "Mauris": The paragraph describing ODBC driver

The Open Database Connectivity (ODBC) driver is a read-only ODBC driver that lets you connect business intelligence and data visualization applications like Tableau, Microsoft Excel, and Power BI to OpenSearch using SQL.

> 3. Dummy text starting with "Curabitur": The paragraph describing JDBC driver

The Java Database Connectivity (JDBC) driver is a read-only driver for connecting business intelligence, and data visualization applications with OpenSearch using SQL. 

> 4. The Dummy text starting with "Quisque": The paragraph describing _each_ client. As an example, we'll need one for opensearch-py, opensearch-go, and opensearch-js each.

_JavaScript_
The OpenSearch JavaScript client ([opensearch-js](https://opensearch.org/docs/latest/clients/javascript/)) provides an easy way to interact with your OpenSearch cluster using the JavaScript language. The client contains a library of APIs that let you perform different operations on your cluster, like indexing and searching.

_Python_
The OpenSearch Python client ([opensearch-py](https://opensearch.org/docs/latest/clients/python/)) provides an easy way to interact with your OpenSearch cluster using the Python language. The client contains a library of APIs that let you perform different operations on your cluster, like indexing and searching.

_Go_
The OpenSearch Go client ([opensearch-go](https://opensearch.org/docs/latest/clients/go/)) provides an easy way to interact with your OpenSearch cluster using the Go language. The client contains a library of APIs that let you perform different operations on your cluster, like indexing and searching.

**Comment by stockholmux** [comment]
@elfisher Great start, I think we have to be less formulaic. I'll take a run at it in situ shortly.
