### ISSUE TITLE
Publish blog for Anomaly Detection 1.1 Unified Flow feature

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/project-website#437]
**Describe the blog post your would like to write**
A detailed description of the unified flow feature / enhancement in the Anomaly Detection plugin as part of the 1.1 release. Using an example, the blog will walk through how to set up and run real-time and historical anomaly detection using the unified workflow.

**What is the title of the blog post?**
[PENDING] "Simplifying real-time and historical anomaly detection in OpenSearch"

**Who are the authors?**
@ohltyler, Pavani Baddepudi

**What is the proposed posting date?**
On or before November 16, 2021

**Comment by stockholmux** [comment]
Thanks @ohltyler! This all looks good. Looking forward to a PR.
