### ISSUE TITLE
Blog post on how to use Java REST client with security enabled OpenSearch cluster

### ISSUE THREAD

**Issue by setiah** [opensearch-project/project-website#440]
**Describe the blog post your would like to write**
Increasingly we are seeing users facing trouble configuring clients with security enabled OpenSearch clusters. This blog post would cover details around how to configure SSL for Java High level REST client to work with secure OpenSearch clusters. 

**What is the title of the blog post?**
tbd

**Who are the authors?**
setiah@

**What is the proposed posting date?**
tbd

**Comment by stockholmux** [comment]
Thanks @setiah - can you give me a ball park of when you were thinking of wanting this posted?

**Comment by setiah** [comment]
> Thanks @setiah - can you give me a ball park of when you were thinking of wanting this posted?

Sure, it should be around 12th Nov

**Comment by stockholmux** [comment]
@setiah Any dependency on it being before OpenSearch 1.2.0?

**Comment by setiah** [comment]
> @setiah Any dependency on it being before OpenSearch 1.2.0?

Nope. This can go independent of the release.

**Comment by elfisher** [comment]
@setiah let's also think about how to articulate this for clients in general.

**Comment by setiah** [comment]
> @setiah let's also think about how to articulate this for clients in general.

Good point,. I was thinking along the same lines. :) I wanted to investigate the commonalities across other clients. Depending on the overlap, i'll extend the scope accordingly.

**Comment by stockholmux** [comment]
@elfisher From a perspective of SEO and link-ability, it's probably better to have a single post per language/client.

Think about it - a user isn't going to type "opensearch client security" or something into google. They are going to type "java client opensearch security"

Likewise, if a users is struggling with this issue, throwing them a specific link about Java will be really valuable and they won't care about what, say, Ruby is doing.

**Comment by stockholmux** [comment]
@elfisher Yeah, I think the cert complexity and confusion might also be a weakness in the documentation.

**Comment by elfisher** [comment]
> @elfisher Yeah, I think the cert complexity and confusion might also be a weakness in the documentation.

Agreed. I know there was an issue raised there. I'll follow up on it.

**Comment by stockholmux** [comment]
@setiah What's the status on this?
