### ISSUE TITLE
Blog post on how to use OpenSearch Dashboard custom branding

### ISSUE THREAD

**Issue by ahopp** [opensearch-project/project-website#441]
**Describe the blog post your would like to write**
We should write a blog post on how to use the new customer branding features in OpenSearch Dashboards. Most of the content is avail on this issue https://github.com/opensearch-project/documentation-website/issues/241 but needs some narrative structure. 

**What is the title of the blog post?**
[Working Title] Making OpenSearch Your Own 

**Who are the authors?**
@kavilla, @abbyhu2000 (if she's avail), and @ahopp 

**What is the proposed posting date?**
Post v1.2.0 (11/16) but should be somewhat of a fast follow.

**Comment by ahopp** [comment]
Hey @abbyhu2000 you interested in helping draft a blog post with me and @kavilla? All the cool kids are doing it.

**Comment by abbyhu2000** [comment]
@ahopp Sure!!! Would love to ;)

**Comment by stockholmux** [comment]
Seems like a great topic and glad to see @abbyhu2000 helping out.

I'd like to nail down a more precise timeline @ahopp - keep in mind: Thanksgiving, Re:Invent, and December holidays.

**Comment by ahopp** [comment]
@abbyhu2000 awesome! @kavilla and I will get it started and we can work in the PR together. 

@stockholmux make sense - are there any gap you'd like to fill post launch?

**Comment by stockholmux** [comment]
@ahopp I'm seeing a few that are being held until after 1.2.0, so I'm expecting a log jam right after that until reinvent. Perhaps during the week of reinvent? (I think we might slow to 0 or 1 blog post per week during dec)

**Comment by stockholmux** [comment]
@ahopp What's the status on this?

**Comment by stockholmux** [comment]
@ahopp Given the delay of 1.2.0, can you provide a new estimated date?

**Comment by stockholmux** [comment]
Any update on this post since 1.2.0 is now out?

**Comment by stockholmux** [comment]
Any update on this blog post as far as timing?

**Comment by stockholmux** [comment]
@ahopp I'm going to close this out since there has been no update. Feel free to reopen when/if the effort gets some attention
