### ISSUE TITLE
Proposal for a blog post on building a tracing pipeline using data prepper and opensearch with opentelemetry data. 

### ISSUE THREAD

**Issue by kuberkaul** [opensearch-project/project-website#444]
**Blog Description** : 

Documenting :
- how-to and learnings while building a distributed tracing pipeline with open telemetry agent/collector, data prepper and opensearch.
- Visualizing trace data in opensearch trace analytics and jaeger.  

**Blog Title** : 
Building a distributed tracing pipeline with opentelemetry collector, data prepper and opensearch.

**Who are the authors?**
- Kuber Kaul 
Distinguished Software Engineer, Dowjones

**What is the proposed posting date?**
Trying to publish before re;invent (Nov 29)

**Comment by stockholmux** [comment]
@kuberkaul That sounds awesome! 

You're covering a lot of ground here - do you have thoughts on how long it might end up being?

**Comment by kuberkaul** [comment]
@stockholmux I have just started writing a draft and am planning to compress the details and go slightly high level to be able to put everything in one blog. I was hoping to make a it an under 10 min read if that works. Is there a limit/recommendation to the amount words/reading time ?

**Comment by stockholmux** [comment]
@kuberkaul No hard limits - Occasionally, I get encyclopedic blog posts but a 10 minute read is appropriate.  👍

**Comment by kuberkaul** [comment]
Just an update, The blog is complete on my side, and is with our legal to get approved. Hopefully that is soon (🤞🏽), and I can push it here for feedback, approval, corrections. 

Happy Thanksgiving!

**Comment by stockholmux** [comment]
@kuberkaul Checking in - how's it going?

**Comment by kuberkaul** [comment]
sorry for the delay. This is approved on our side. I have a few images and config files. I will be keeping them in our org and linking from the post. Hope that works. I'll add the post under _post by tomorrow in a PR and link it here.

**Comment by stockholmux** [comment]
@kuberkaul Nice! 

Looks like we have a blog post cued up for tomorrow and Friday is a sub optimal day - would Monday be good for you?

**Comment by kuberkaul** [comment]
yes, I am at re;invent so have limited access to make changes anyway. I will push the PR and you can take your time with the feedback/corrections. I will make sure to turn on notifications so I am able to get to them in timely fashion 👍🏽

**Comment by kuberkaul** [comment]
@stockholmux I have a question, I have some manifest files, helm harts that are part of the blog. I have them in the blog but would also like to host them here to give out a link for all code at the end. Where can I push the manifest in this repo ? Any specific location ?

**Comment by kuberkaul** [comment]
Decided to host the manifest files in our own repo (should be made public today) ~ its also in the body of the blog. 

everything else is part of the PR. Hopefully this is helpful!

**Comment by stockholmux** [comment]
Thanks @kuberkaul - I'll review today!

**Comment by stockholmux** [comment]
@kuberkaul Congrats:

https://opensearch.org/blog/technical-post/2021/12/distributed-tracing-pipeline-with-opentelemetry/
