### ISSUE TITLE
Proposal for a blog post on how do plugins work

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/project-website#446]
**Describe the blog post your would like to write**
A blog post on how do plugins in OpenSearch. How are they loaded and what are the limitations...

**What is the title of the blog post?**
How do plugins work

**Who are the authors?**
@ashwin-pc for Dashboards.
@owaiskazi19 @saratvemulapalli - for OpenSearch

**What is the proposed posting date?**
11/29

**Comment by saratvemulapalli** [comment]
@stockholmux not really. With the work we are doing for 2.0, we have been learning how things work and wanted to put out the learnings for the community.

**Comment by stockholmux** [comment]
Ok Sounds good - we might have some other blog posts that will want this timeline, but I'm flexible

**Comment by stockholmux** [comment]
@saratvemulapalli How's this coming?

**Comment by saratvemulapalli** [comment]
@stockholmux the content is almost ready. 
I'll move this up to Wednesday 11/24 if thats works for you.

**Comment by stockholmux** [comment]
@saratvemulapalli That's fine but I don't think you'll get many eyeballs. In the US, Turkey will be on folk's mind by that point.

**Comment by ashwin-pc** [comment]
@stockholmux Is there a better date that you suggest?

**Comment by saratvemulapalli** [comment]
@stockholmux makes sense. We'll have the PR out for OpenSearch (while @ashwin-pc is working on another one for Dashboards). 
I'll move the date to Monday 11/29 if thats the best time to publish it.

**Comment by stockholmux** [comment]
closed by #546

**Comment by saratvemulapalli** [comment]
@stockholmux we should keep this open as @ashwin-pc is working on the second piece of the blog post for Dashboards.
It's up to you if you'd like this to be a different issue.

**Comment by asafm** [comment]
I have a general question here. Don't you prefer to have this blog post content be added as official documentation for Open Search? I couldn't find under Open Search any documentation for how the Plugin system works.

**Comment by saratvemulapalli** [comment]
@asafm if you think that helps we would be more happy to publish the content in our documentation. 
Do you mind opening an issue in https://github.com/opensearch-project/documentation-website?

**Comment by asafm** [comment]
@saratvemulapalli https://github.com/opensearch-project/documentation-website/issues/426 Thanks!
