### ISSUE TITLE
Deploy a multi-node cluster using Helm charts

### ISSUE THREAD

**Issue by TheAlgo** [opensearch-project/project-website#447]
**Describe the blog post your would like to write**
This blog post will walkthrough how can one set up a multi-node cluster in Kubernetes using the official OpenSearch and OpenSearch Dashboards Helm Charts.

**What is the title of the blog post?**
Setup multi-node OpenSearch Cluster on Kubernetes 

**Who are the authors?**
Dhiraj Kumar Jain (@TheAlgo)

Who will be listed as the authors of this blog post
Dhiraj Kumar Jain (@TheAlgo)

**What is the proposed posting date?**
11/19

Provide the date which you wish this post to go live
11/22 or in that week

**Comment by stockholmux** [comment]
@TheAlgo OK - Neat! Sounds like a good post.

**Comment by stockholmux** [comment]
closed by #523
