### ISSUE TITLE
Create announcement for OpenSearch Benchmark

### ISSUE THREAD

**Issue by achitojha** [opensearch-project/project-website#479]
**Describe the blog post your would like to write**
The blog will be an announcement around OpenSearch Benchmark launch. The blog would highlight what it is, why it is needed and encourage opensearch community members to install, run, request features, etc

**What is the title of the blog post?**
Introducing OpenSearch Benchmark

**Who are the authors?**
- achitojha
- stockholmux

**What is the proposed posting date?**
2021-12-07

**Comment by stockholmux** [comment]
Looks good!

**Comment by stockholmux** [comment]
@achitojha Do you want to update the date for this one?

**Comment by achitojha** [comment]
> @achitojha Do you want to update the date for this one?

Updated

**Comment by stockholmux** [comment]
closed by #559
