### ISSUE TITLE
[BUG] external link opens to same tab 

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/project-website#481]
**Describe the bug**
Opensearch project org, is an external link which should open in a new tab instead of replacing the current tab

**Screenshots**
<img width="459" alt="Screen Shot 2021-11-17 at 2 13 30 AM" src="https://user-images.githubusercontent.com/19362/142181506-6963941f-4b1e-4054-8200-7ddb4170d7b6.png">

**Comment by Marob-nod** [comment]
Hi ! Can I work on it ?

**Comment by stockholmux** [comment]
@Marob-nod Go for it!

**Comment by Aayush27032001** [comment]
Hi @anirudha!, Can I work on it? I also founded out very is the problem

**Comment by Aayush27032001** [comment]
Hi ! Can you assign this to me ? I also founded where is the problem.

**Comment by stockholmux** [comment]
@Aayush27032001 I think @Marob-nod is tackling this one.

**Comment by Aayush27032001** [comment]
I had done it and I was just creating pull request. 
![github opensearch (2)](https://user-images.githubusercontent.com/75034170/142232234-27938108-f3fe-4397-afa0-049fb8c99bd6.png)

**Comment by Aayush27032001** [comment]
hi @stockholmux I had even fixed this problem and was just creating pull request so may I go forward?

![github opensearch (2)](https://user-images.githubusercontent.com/75034170/142234102-71887d00-7f13-4b0f-8865-b6e76d8603eb.png)

**Comment by Marob-nod** [comment]
@stockholmux @Aayush27032001 Since you found the solution, I let you handle it. :)

**Comment by Marob-nod** [comment]
But that is interesting, bc when I inspect this link with the browser, it already has this attribute "_blank".

**Comment by Aayush27032001** [comment]
Hi @Marob-nod but it wasn't showing to me!

![Comparing opensearch-project_main Aayush27032001_main · opensearch-project_project-website - Google Chrome 17-11-2021 21_28_25](https://user-images.githubusercontent.com/75034170/142235343-baa87f17-5d89-4068-86be-80829805cf11.png)

**Comment by Aayush27032001** [comment]
@Marob-nod thankyou for giving it to me it was my first contribution

**Comment by Aayush27032001** [comment]
hi @stockholmux now I made a signed pull request please check that and approved it

**Comment by stockholmux** [comment]
closed by #489
