### ISSUE TITLE
[BUG] Documentation search requests from `www.opensearch.org` fail

### ISSUE THREAD

**Issue by tmarkley** [opensearch-project/project-website#524]
**Describe the bug**
Documentation search from https://www.opensearch.org/docs fails with a CORS error in the JavaScript console. Everything works fine at https://opensearch.org/docs.

**To Reproduce**
1. Go to www.opensearch.org/docs
2. Attempt to search the docs
3. Notice that no results populate
4. See error in the JS console

**Expected behavior**
Either the CORS request is allowed or `www.opensearch.org` automatically redirects to `opensearch.org`

**Host/Environment:**
 - OS: macOS
 - Browsers: Chrome, Safari, and Firefox

**Additional context**
Error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://opensearch.org/docs/latest/assets/js/search-data.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by stockholmux** [comment]
@abbashus and @AMoo-Miki - looks like this might be related to https://github.com/opensearch-project/project-website-search

**Comment by abbashus** [comment]
Checking

**Comment by abbashus** [comment]
We haven't officially release the OpenSearch based search function. I also checked that we are not making any calls to our search API (assuming something accidentally got released). It looks like more to do with how the S3 bucket is setup.

**Comment by stockholmux** [comment]
Thanks for checking @abbashus. Interestingly, I'm not seeing a problem any longer.

**Comment by stockholmux** [comment]
I'm actually wondering if we should redirect www.opensearch.org -> opensearch.org...

**Comment by abbashus** [comment]
This can be fixed by using relative file URL instead of absolute URL in `assets/js/just-the-docs.js`

```
// Site search

function initSearch() {
  var request = new XMLHttpRequest();
  request.open('GET', 'https://opensearch.org/docs/latest/assets/js/search-data.json', true);

  request.onload = function(){
    if (request.status >= 200 && request.status < 400) {
      var docs = JSON.parse(request.responseText);
      
      lunr.tokenizer.separator = /[\s/]+/
...
...
...
```
The thing is I am not able to find this `just-the-docs.js` in our source code

**Comment by AMoo-Miki** [comment]
Thanks for reporting this issue. The new search functionality released a few days ago does not suffer from this bug.

Please feel free to comment or reopen if you notice something we missed.

**Comment by tmarkley** [comment]
@AMoo-Miki thanks! Just out of curiosity, can you link the PR(s) that solved the problem?

**Comment by AMoo-Miki** [comment]
The PR for the website: https://github.com/opensearch-project/project-website/pull/540
The PR for the docsite: https://github.com/opensearch-project/documentation-website/pull/303
