### ISSUE TITLE
Publish new release for opensearch-cli in OpenSearch Download Page

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/project-website#557]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
We would like to update opensearch-cli download link to latest version

**Describe alternatives you've considered**
N/A

**Additional context**
Relevant issue to release artifacts: https://github.com/opensearch-project/opensearch-build/issues/833

**Comment by stockholmux** [comment]
@VijayanB Glad to help with this - most of it is actually self-service. 

Step 0: Create a private fork of the site
Step 1: Create the artifact files. [There is a how-to](https://github.com/opensearch-project/project-website/blob/main/_artifacts/_README.markdown). In this case, the artifact files would be added to [/_artifacts/opensearch-cli](https://github.com/opensearch-project/project-website/tree/main/_artifacts/opensearch-cli)
Step 3: Attach the artifacts to the compatible version(s). Go to the version files in [/_versions](https://github.com/opensearch-project/project-website/tree/main/_versions) and change the version number. [Here is the line opensearch-cli for the latest release](https://github.com/opensearch-project/project-website/blob/main/_versions/2021-11-23-opensearch-1.2.0.markdown?plain=1#L20). If it's compatible will all previous versions, you'd need to make a similar change to those versions.
Step 4: Do a PR. I'll review and push it live
