### ISSUE TITLE
Make main = staging and create a release branch.

### ISSUE THREAD

**Issue by dblock** [opensearch-project/project-website#57]
Match branching and releasing of OpenSearch.

* main is where all PRs and commits go, making it easy for everyone to contribute since it's the default branch
* main automatically deploys to a staging area
* a production branch (called opensearch.org for example) automatically deploys to opensearch.org
* merge to opensearch.org to deploy! (hands off)

<strike>I can't find anything about staging, other than there's a branch. Is this published somewhere? Document it in CONTRIBUTING? 

If the website is live, we should be extra careful with SEO to make sure Google bot doesn't pick it up instead of opensearch.org.  It needs a different robots.txt at least or [more](https://searchengineland.com/how-to-keep-staging-development-site-index-286987).</strike>

**Comment by stockholmux** [comment]
@dblock We have a public but not circulated URL to review staged changes. We don't have the automation finalized so I haven't documented it. 

Good point about the differential robots.txt  and some of the other points mentioned in your article. We'll need to patch the staging site.

**Comment by dblock** [comment]
Add a password to staging or add a robots.txt to it ASAP. Google is going to find that link accidentally and mark the content duplicate, and it will take a long time for opensearch.org to dig itself out of that.

**Comment by dblock** [comment]
Updated per https://github.com/opensearch-project/project-website/pull/79#issuecomment-848906358

**Comment by dblock** [comment]
Updated the description of this issue to clarify what I am suggesting.

**Comment by stockholmux** [comment]
`main` is now the working branch 🥳
