### ISSUE TITLE
Publish logstash-oss-with-opensearch-output 7.16.1 to download page

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/project-website#581]
Is your feature request related to a problem? Please describe.
NA

Describe the solution you'd like
We would like to update logstash-oss-with-opensearch-output download link to latest version

Describe alternatives you've considered
N/A

Additional context
Relevant issue to release artifacts: opensearch-project/opensearch-build#1347

**Comment by stockholmux** [comment]
closed by #582
