### ISSUE TITLE
Blog - OpenSearch SQL - Basic queries

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/project-website#612]
**Describe the blog post your would like to write**
In this blog, we’ll explore some of the features and capabilities supported by OpenSearch SQL. We also briefly introduce how SQL engine works internally.

**What is the title of the blog post?**
OpenSearch SQL - Basic queries

**Who are the authors?**
penghuo, jadhanir

**What is the proposed posting date?**
No hard date, as soon as possible

**Comment by stockholmux** [comment]
@penghuo and @anirudha This looks good! 

A point of guidance - the topic sounds a little broad. It would probably both be easier to write and more digestible by readers if you either talk about internals of OpenSearch SQL **or** features and capabilities.

As far as the date, when would you have the content ready? I need to find a place for you in the posting timeline.

**Comment by penghuo** [comment]
@stockholmux, thanks for your advices!

[OpenSerach SQL - Basic Queries] could be the first blog. We are planning  SQL feature blog series.
Content is ready to be reviewed. https://quip-amazon.com/0tOjA3xcupik/Blog-OpenSearch-SQL-Basic-queries.

**Comment by stockholmux** [comment]
@penghuo could you convert that to PR? Quip is internal to Amazon only and blog posts should be open for anyone to review.

**Comment by stockholmux** [comment]
Closed by #663
