### ISSUE TITLE
Blog post: Introduction to Dashboard plugins

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/project-website#619]
**Describe the blog post your would like to write**
This is a follow up article to #526. This time focussing on OpenSearch Dashboards instead of OpenSearch Core.

**What is the title of the blog post?**
Introduction to OpenSearch Dashboard Plugins

**Who are the authors?**
ashwin-pc

**What is the proposed posting date?**
1/21

**Comment by stockholmux** [comment]
Closed by #641
