### ISSUE TITLE
[BLOG POST] Partner Highlight: OpenSearch as a Service in Virtuozzo DevOps PaaS

### ISSUE THREAD

**Issue by TetianaFTV** [opensearch-project/project-website#623]
**Describe the blog post your would like to write**
Virtuozzo announces OpenSearch as the latest certified container available in the its DevOps PaaS solution and now it can be easily deployed with automatic clustering. The OpenSearch Cluster creation within Virtuozzo DevOps PaaS is a straightforward and fully automated process that can be performed directly from the topology wizard. We give the opportunity for cloud and hosting service providers to offer OpenSearch-as-a-service to their customers as a packaged solution with all required components already preconfigured.

**What is the title of the blog post?**
How to Offer OpenSearch as a Service using Virtuozzo DevOps PaaS 

**Who are the authors?**
Tetiana Fydorenchyk
Director of Global Product Marketing at Virtuozzo
https://twitter.com/tetiana_ftv
https://www.linkedin.com/in/tetiana-fydorenchyk/

**What is the proposed posting date?**
January 20th

**Comment by stockholmux** [comment]
That sounds awesome @TetianaFTV! FYI @ahopp

**Comment by ahopp** [comment]
I'll take a look this morning, thanks @TetianaFTV @stockholmux!

**Comment by TetianaFTV** [comment]
Great, thanks @ahopp!

Just in case, here is the image that can be used for sharing

![OpenSearch_cluster_1200x628](https://user-images.githubusercontent.com/38689227/149960450-6f4b1424-3576-40e6-a571-c199b3d7f4fd.png)

**Comment by ahopp** [comment]
Hey @TetianaFTV have you opened a PR for the OpenSearch.org blog post yet? I wasn't able to find it and I'd like to make sure we ready for post.

**Comment by TetianaFTV** [comment]
Hi @ahopp, and isn't this ticket for OpenSearch.org blog? should I open any other?
I also shared the link to the article draft in our email thread, let me know if I need to share it here also.

**Comment by ahopp** [comment]
Sorry for the confusion! I'll try to clarify - this ticket is meant to propose a blog post so the OpenSearch team can coordinate calendaring and make sure the content is appropriate (we're all set for both). It will also helps @stockholmux @krisfreedain know when they should post on the forum if applicable (again, we're set for this)! 

The PR (pull request) is to publish your content on the website. For example, [this](https://github.com/opensearch-project/project-website/pull/369) was the PR for the Aiven's [announcement post](https://opensearch.org/blog/partners/2021/10/partner-highlight-aiven/). Basically, translating your existing doc into a blog post on OpenSearch.org.

**Comment by ahopp** [comment]
@TetianaFTV let me know if that makes sense! Happy to help where I can!

**Comment by TetianaFTV** [comment]
@ahopp the PR is submitted https://github.com/opensearch-project/project-website/pull/639
Thanks!

**Comment by stockholmux** [comment]
closed by #639
