### ISSUE TITLE
To JDK or not to JDK (and what version)

### ISSUE THREAD

**Issue by dblock** [opensearch-project/project-website#628]
**Describe the blog post your would like to write**

Through multiple versions of OpenSearch we have recommended and bundled various versions of JDKs.

- Provide a timeline of which JDK was bundled with which version of OpenSearch.
- Explain the difference between LTS and non-LTS versions of the JDK.
- Document how and where to get a no-JDK version and why one would want to do that.
- Explain the difference of what JDK is used for development vs. test vs. operating OpenSearch.
- Specifics about platforms such as FreeBSD
- Highlight all the different environment variables that can be used such as JAVA_HOME vs. OPENSEARCH_JAVA_HOME (this isn't implemented).
- Link to work on changing the JDK in future versions of OpenSearch.
- Highlight the work on benchmarking various JDKs.
- What else?

**What is the title of the blog post?**

"Making sense of OpenSearch Java Runtimes"
(suggest better?)

**Who are the authors?**
@dblock

Would like some help and co-authoring with @reta, @rursprung, @ryanbogan, @smortex ...

**What is the proposed posting date?**
TBD, probably around release of 1.3.0

**Related Issues**
https://github.com/opensearch-project/opensearch-build/issues/74
https://github.com/opensearch-project/OpenSearch/issues/1910
https://github.com/opensearch-project/opensearch-plugins/issues/110
https://github.com/opensearch-project/opensearch-build/issues/99
https://github.com/opensearch-project/OpenSearch/issues/1872
https://github.com/opensearch-project/OpenSearch/issues/1276
https://github.com/opensearch-project/project-website/issues/624
https://github.com/opensearch-project/opensearch-build/issues/101#issuecomment-914663338

**Comment by stockholmux** [comment]
@dblock This looks like it would be a mega post. Would you want to split it up into smaller chunks?

Also, some of this looks like it's not currently reflected on the roadmap - is it dependent on anything?

**Comment by dblock** [comment]
I still have this queued up. If it gets long, will shorten/split. 

I collected the kitchen sink of related issues here, so we shall see what makes this into an actual release and obviously won't be talking about things that didn't/won't.

**Comment by stockholmux** [comment]
Sounds good @dblock. If this is tied to a release beyond the next one, I think might be wise to close the issue and reopen when we get closer.

**Comment by dblock** [comment]
I've started drafting a blog post, please contribute! 

https://github.com/opensearch-project/project-website/pull/670

**Comment by stockholmux** [comment]
closed by #744
