### ISSUE TITLE
[BLOG POST] Data Prepper 1.2.1 performance metrics

### ISSUE THREAD

**Issue by sbayer55** [opensearch-project/project-website#645]
**Describe the blog post you would like to write**
Describe performance testing results of Data Prepper 1.2.1, compare Data Prepper 1.2.1 performance metrics with comperable competitor, detail how to reproduce our results.

**What is the title of the blog post?**
Data Prepper 1.2.1 Performance Testing

**Who are the authors?**
@sbayer55

**What is the proposed posting date?**
January 25th

**Comment by stockholmux** [comment]
Closed by #662
