### ISSUE TITLE
BYOK for B2B SaaS Operators

### ISSUE THREAD

**Issue by pakshi** [opensearch-project/project-website#647]
**Describe the blog post your would like to write**
B2B SaaS companies with Opensearch as backend data store can rapidly implement BYOK (Bring your own key)

**What is the title of the blog post?**
BYOK for B2B SaaS Operators

**Who are the authors?**
Pakshi Rajan

**What is the proposed posting date?**
ASAP

**Comment by pakshi** [comment]
I have a content laid out in a Google doc. Happy to share if you provide an email.

**Comment by pakshi** [comment]
[BYOK for B2B SaaS Companies- Solution Brief.pdf](https://github.com/opensearch-project/project-website/files/7944073/BYOK.for.B2B.SaaS.Companies-.Solution.Brief.pdf)

@elfisher Attaching a PDF.

**Comment by pakshi** [comment]
[BYOK for B2B SaaS Companies- Solution Brief.pdf](https://github.com/opensearch-project/project-website/files/7953600/BYOK.for.B2B.SaaS.Companies-.Solution.Brief.pdf)

@elfisher, I  am attaching a copy of the document in PDF form. I am happy to share the Google doc to your email so that you can add your edit suggestions and comments in place.

**Comment by pakshi** [comment]
@elfisher any guidance on how to proceed further?

**Comment by elfisher** [comment]
Hey @pakshi thanks for attaching the brief. This makes sense. Let's work with @stockholmux to figure out when we can get this on the calendar. Also is it easier to do the review on a shared Google doc or on GitHub?

**Comment by pakshi** [comment]
Kyle,
I have the MD file... Should I just attach it here?
Also I have referred to image src like this:
 (/assets/media/blog-images/2022-02-18-partner-highlight-titaniam/xyz.png)
 
 But I am unable to create a folder and upload the image...
![image](https://user-images.githubusercontent.com/7464106/154597132-5c4c1165-445a-4bec-93fc-c1e7f0e128d6.png)

Should I just create a zip file with the following:
1. Instruction - where to copy the image
2. md file
3. All the images

and attach it to this ticket?

**Comment by pakshi** [comment]
Kyle,
I have attached the Markdown file and the one image it refers to as a zip file.
You would have to create a folder here with this path and drop the image there.
/assets/media/blog-images/2022-02-18-partner-highlight-titaniam/

Please let me know if this will suffice? Thanks for your help.

[2022-02-17-partner-highlight-titaniam-byok.zip](https://github.com/opensearch-project/project-website/files/8093767/2022-02-17-partner-highlight-titaniam-byok.zip)

**Comment by pakshi** [comment]
Created PR:
https://github.com/opensearch-project/project-website/pull/701

**Comment by pakshi** [comment]
@stockholmux 
Is this what you were expecting as for how content should be delivered?

**Comment by stockholmux** [comment]
Hey @pakshi - yep - that's more/less the right format.

**Comment by pakshi** [comment]
PR #701

**Comment by pakshi** [comment]
Thanks everyone for your help.
https://opensearch.org/blog/partners/2022/04/partner-highlight-titaniam-byok
