### ISSUE TITLE
Add a section for OpenSearch SQL CLI on Downloads/Getting Started page.

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/project-website#654]
Add a section for OpenSearch SQL CLI on [Downloads/Getting Started page](https://opensearch.org/downloads.html#opensearch). It could be 
- brief descriptive words for this cli tool
- links to Pypi https://pypi.org/project/opensearchsql/
- command to install `pip install opensearchsql`

**Comment by zhongnansu** [comment]
@stockholmux Hi Kyle, what's the plan of adding this?

**Comment by stockholmux** [comment]
@zhongnansu Currently backlogged as we have some other pressing matters, but we'll get to it.

**Comment by vimalMK** [comment]
Is this issue still open? I will be interested to look into it.

**Comment by zhongnansu** [comment]
> Is this issue still open? I will be interested to look into it.

I think it's still open. We'd love to see your proposed change or PR!
 @stockholmux could you involve documentation team to help or guide?

**Comment by vimalMK** [comment]
@zhongnansu  Great! Thank you. 

I just need some descriptive words for this cli tool. I can PR once I get that. Thank you again.

**Comment by vimalMK** [comment]
@zhongnansu  PR added for review #1051 . Thank you

**Comment by nateynateynate** [comment]
Solved with #3112 !
