### ISSUE TITLE
FluentD Formal Announcement Targeting Feb 10

### ISSUE THREAD

**Issue by brijos** [opensearch-project/project-website#671]
Draft targeted EOD Feb 8th...

**Describe the blog post your would like to write**
Formally announcing FluentD availability with a short Getting Started write up

**What is the title of the blog post?**
TBC

**Who are the authors?**
TBC (likely Anurag Gupta, Tim Stephens, Nate Boot)

**What is the proposed posting date?**
Feb 10

**Comment by stockholmux** [comment]
closed by #686
