### ISSUE TITLE
Solving flakey integration tests in OpenSearch

### ISSUE THREAD

**Issue by dblock** [opensearch-project/project-website#694]
**Describe the blog post your would like to write**

We've inherited at least [27 known flakey integration tests](https://github.com/opensearch-project/OpenSearch/labels/Flakey%20Random%20Test%20Failure) that constantly need to be retried by doing `start gradle check`'s. This blog post will call attention to this problem, highlight how some of these tests are being fixed, e.g. https://github.com/opensearch-project/OpenSearch/pull/2110, and ask for community help.

**What is the title of the blog post?**

_Improving the reliability and predictability of integration tests_

**Who are the authors?**

@jainankitk
@dblock 

**What is the proposed posting date?**

TBD

**Comment by andrross** [comment]
opensearch-project/OpenSearch#1925 is an example of a non-deterministic test bug that had a simple fix but took a lot of effort to track down

**Comment by stockholmux** [comment]
Hey @dblock - is fixing the tests part of a campaign? If so what's the timeline on that campaign?
