### ISSUE TITLE
Remove mapping type

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/project-website#709]
As part of v2.0 release, `mapping types` are getting removed from OpenSearch engine. Below are the changes in the opensearch-engine.
- Removal of type from rest end-points
- Removal of include_type_name parameter from API requests.

As part of this issue, please verify if type removal change on OpenSearch engine impacts this repository. If yes, then please remove the type references/usage from documentation. It may need to identify all examples of type API references and remove them with typeless APIs. 

Related: [OpenSearch-engine meta issue](https://github.com/opensearch-project/opensearch/issues/1940)

**Comment by stockholmux** [comment]
@dreamer-89 I don't think this affects the opensearch.org website :)
