### ISSUE TITLE
[Blog] write a blog about the launch of using "latest" in distribution urls

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/project-website#715]
**Describe the blog post your would like to write**

We support using "latest" keyword in the distribution url. 
https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.0/latest/linux/arm64/builds/opensearch/manifest.yml

As a contrast, previously we have to provide a Jenkins build number (e.g 1210)
https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/1.3.0/1210/linux/arm64/builds/opensearch/manifest.yml

See this https://github.com/opensearch-project/opensearch-build/issues/1492 for more details

**What is the title of the blog post?**

"latest" keyword is now supported in distribution urls

**Who are the authors?**
Who will be listed as the authors of this blog post

https://github.com/tianleh

**What is the proposed posting date?**
3/18/2022

**Comment by stockholmux** [comment]
Hey @tianleh - I like it. 

I think you'll need to setup the reason why this is important in the blog post. Average user of OpenSearch is probably not super familiar with distribution URLs.

Let me know how I can support!

**Comment by stockholmux** [comment]
@tianleh Any word on this post?

**Comment by tianleh** [comment]
> @tianleh Any word on this post?

@stockholmux Thanks for following up on this. Still trying to figure out the process.
