### ISSUE TITLE
OpenSearch Plugin artifacts for 1.0.x

### ISSUE THREAD

**Issue by guiangumpac** [opensearch-project/project-website#737]
**Is your feature request related to a problem? Please describe.**
We are trying to run integration tests for the [OpenSearch Net client](https://github.com/opensearch-project/opensearch-net). We were able to find plugin artifacts for OpenSearch version >= 1.1.0 but not for 1.0.x. For example, 1.2.0 integration tests passes because https://artifacts.opensearch.org/releases/plugins/mapper-murmur3/1.2.0/mapper-murmur3-1.2.0.zip exists while 1.0.0 fails because https://artifacts.opensearch.org/releases/plugins/mapper-murmur3/1.0.0/mapper-murmur3-1.0.0.zip does not exist.

**Describe the solution you'd like**
Publishing plugins artifacts for OpenSearch 1.0.x would solve our issue. Alternatively, a section on the website dedicated to downloading plugins and other artifacts similar to [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/plugins/8.1/mapper-murmur3.html) would be great.

**Describe alternatives you've considered**
We've tried using plugins from other version but we encounter a version mismatch.

**Comment by anirudha** [comment]
@stockholmux @bbarani can someone help here, thanks

**Comment by stockholmux** [comment]
I'm absolutely interested in adding the clients to the downloads page but the download webpage isn't blocking you here.

Perhaps this question belongs in the [opensearch-project/build](https://github.com/opensearch-project/opensearch-build)?

**Comment by stockholmux** [comment]
@bbarani thoughts?

**Comment by bbarani** [comment]
@guiangumpac We started [publishing](https://github.com/opensearch-project/opensearch-build/issues/86) the native plugins starting 1.1.0 version. You can use the alternative approach listed [here](https://github.com/opensearch-project/OpenSearch/issues/951#issuecomment-878482124) for previous versions.

**Comment by guiangumpac** [comment]
@anirudha, @stockholmux, and @bbarani thanks for your input!
