### ISSUE TITLE
Release Manager Blog Post

### ISSUE THREAD

**Issue by eugenesk24** [opensearch-project/project-website#740]
**Describe the blog post you would like to write**
This blog post will be about being release manager for the first time in OpenSearch and the mistakes I made and the things I learned.

**What is the title of the blog post?**
Day in the Life of a Release Manager

**Who are the authors?**
@eugenesk24
@stockholmux 

**What is the proposed posting date?**
As soon as possible.

**Comment by stockholmux** [comment]
Hey @eugenesk24 - the quip link you posted isn't accessible to the general public and doesn't belong on github.

**Comment by eugenesk24** [comment]
My bad! I removed it 👍

**Comment by stockholmux** [comment]
@krisfreedain FYI - just so this doesn't get list. @eugenesk24 shared this privately - please work together to get a PR made.

**Comment by krisfreedain** [comment]
@eugenesk24 - let me know when you have time so we can work on this one. thanks
