### ISSUE TITLE
Pureinsights adds OpenSearch to its Discovery Platform - Blog Post

### ISSUE THREAD

**Issue by nereo-campos-pi** [opensearch-project/project-website#762]
**Describe the blog post your would like to write**
We are pleased to announce that OpenSearch will be the default search engine of choice for the [Pureinsights Discovery Platform](https://pureinsights.com/technology/).

**What is the title of the blog post?**
Partner Highlight: Pureinsights adds OpenSearch to its Discovery Platform

**Who are the authors?**
Phil Lewis

**What is the proposed posting date?**
04/15/22

**Comment by stockholmux** [comment]
Closed by #774 & #775
