### ISSUE TITLE
FluentCon Announcement

### ISSUE THREAD

**Issue by brijos** [opensearch-project/project-website#805]
**Describe the blog post your would like to write**
Introduce FluentCon EU and OpenSearch's sponsorship 

**What is the title of the blog post?**
FluentCon Announcement

**Who are the authors?**
Anurag Gupta

**What is the proposed posting date?**
05/11/2022 or 5/12/2022

**Comment by krisfreedain** [comment]
Completed with https://github.com/opensearch-project/project-website/pull/809
