### ISSUE TITLE
Display drivers on downloads page

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/project-website#816]
**Is your feature request related to a problem? Please describe.**
We recently released the ODBC drivers (https://github.com/opensearch-project/project-website/pull/786), but on the [latest downloads page](https://opensearch.org/versions/opensearch-2-0-0-rc1.html) there is no drivers section, only OpenSearch and OpenSearch Dashboards. Users have to click on artifacts directory and scroll to the bottom to download ODBC drivers, which is not very straightforward.

**Describe the solution you'd like**
Not sure if they disappeared because latest is a rc1 release, but ideally drivers should always appear on the main download page, like the [download page for 1.3.2](https://opensearch.org/versions/opensearch-1-3-2.html). Or some other easy way for users to download drivers.

**Describe alternatives you've considered**

**Additional context**

**Comment by nateynateynate** [comment]
If I'm not mistaken this has been implemented - I see the ODBC drivers listed on the most recent download pages: 
![image](https://github.com/user-attachments/assets/81d0a13f-1cfd-4fde-8311-1c38a4ff4e44)

https://opensearch.org/downloads.html

Feel free to re-open.
