### ISSUE TITLE
How to use fluentbit and OpenSearch with Bottlerocket logs

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/project-website#855]
**Describe the blog post your would like to write**
This blog post will describe how to use Fluentbit to gather host container logs from Bottlerocket OS and then put them into OpenSearch to search and analyze.

**What is the title of the blog post?**
How to use fluentbit and OpenSearch with Bottlerocket logs

**Who are the authors?**
Kyle Davis

**What is the proposed posting date?**
July 15-ish

**Comment by krisfreedain** [comment]
Looking forward to this one!
