### ISSUE TITLE
[BLOG] Building your first ML Model with ML Commons

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/project-website#861]
**Describe the blog post your would like to write**
There should a blog that describes end to end how to create, use, and update a ML Commons model in OpenSearch. This blog should show the surface level work that is required as well as describe what is happening behind the scenes. 

**What is the title of the blog post?**
Building your first ML Model with ML Commons

**Who are the authors?**
@ylwu-amzn and @dtaivpp 

**What is the proposed posting date?**
7/15/2022

**Comment by krisfreedain** [comment]
any progress on this @dtaivpp?
