### ISSUE TITLE
Download OpenSearch and Dashboards images from Amazon ECR public gallery  

### ISSUE THREAD

**Issue by setiah** [opensearch-project/project-website#862]
**Is your feature request related to a problem? Please describe.**
The OpenSearch project just made docker images for OpenSearch and OpenSearch Dashboards available on Amazon ECR public gallery. https://gallery.ecr.aws/?searchTerm=opensearchproject. The request is provide an option on the Downloads page, for users to download OpenSearch and Dashboards from Amazon ECR public gallery.

**Describe the solution you'd like**
On the downloads page, add a drop down option for Amazon ECR Public gallery for OpenSearch and OpenSearch Dashboards.

**Describe alternatives you've considered**

**Additional context**

**Comment by setiah** [comment]
A few of us engaged on this proposal and discussed the problem with a couple of potential solutions. Penning down a summary for feedback/further discussion -
 
The **problem** with providing Amazon ECR public repository link as a download option on website is that ECR does not have image version specific URLs like DockerHub. For example, if a user wants to download a previous OpenSearch version say 1.3.3, clicking on the Docker option on the website takes him directly to [docker images for 1.3.3 version on DockerHub](https://hub.docker.com/r/opensearchproject/opensearch/tags?page=1&ordering=last_updated&name=1.3.3), but this kind of redirection is _not possible_ with [ECR url](https://gallery.ecr.aws/opensearchproject/opensearch)

One **potential solution** is -

Change the Docker option behavior on download page. Instead of `Get it` button redirecting users to DockerHub, make the `Get it` show commands to pull the Docker images from either DockerHub or Amazon ECR. Read this for example - 
a. User selects the Docker option from Dropdown menu
b. Clicks `Get it`
c. Instead of redirecting, the downloads page itself shows command to download the Docker images. For example if a user is trying to download x.y.z version -

>Docker images are available on both DockerHub and Amazon ECR.
>
>To pull the image from DockerHub, use
```docker pull opensearchproject/opensearch:x.y.z```
>
>To pull the image from Amazon ECR public repository, use
```docker pull public.ecr.aws/opensearchproject/opensearch:x.y.z```

 The benefit here is 
1. It preserves user context as users don't need to be redirected to other web pages 
2. Helps the website expose multiple options for downloads for any given platform. Same could be helpful for other distributions like RPM where there might be multiple ways of getting the distribution - repository managers or direct downloads. 
3. Requires minimal changes to the website downloads page.

While this is one way, please feel free to add if there are other pros/cons of this approach and/or there are better ways of doing this that translate to a better user experience. 

@bbarani @krisfreedain @dtaivpp

**Comment by dtaivpp** [comment]
After talking to a few other DevOps/Systems Engineers here is some of the feedback I have received: 

Users should be able to expect the same experience regardless of which option they select. When selecting Linux they are not redirected off page to fetch the tarball or package. Additionally, ECR is unable to provide the same experience docker hub provides of linking directly to a release and therefore they felt the best experience would be to stay on the page. 

However, they felt that the experience of navigating through drop down menus and navigating between pages for different releases to be challenging. Several shared the sentiment that they would prefer a scrollable page that was transparent about what releases were available. Similar to how either [Alpine](https://alpinelinux.org/downloads/), [Kafka](https://kafka.apache.org/downloads), or [Nginx](https://nginx.org/en/download.html) manages their download section.

Several shared that this more simple layout was easier to navigate and more familiar.

**Comment by AMoo-Miki** [comment]
This is what I had in mind. Please let me know how you feel with your 👍 and 👎
https://user-images.githubusercontent.com/3527403/176963059-eee5aa1c-c638-4b65-b5b4-f24c5be7e4da.mov

**Comment by setiah** [comment]
thanks @AMoo-Miki for the quick turnaround. This looks good to me and it seems extensible in future for more repository types based out on GCP, Azure. etc. Let's see what others think about this. + @elfisher @ahopp @brijos thoughts?

**Comment by dlvenable** [comment]
@AMoo-Miki , I like the concept you proposed above. The action of the "more info" link doesn't seem very obvious to me. Perhaps they could say "View on DockerHub" and "View on ECR" respectively.

**Comment by elfisher** [comment]
I like the concept proposed as well. Especially @setiah's point about it being extensible for more repo types.

**Comment by AMoo-Miki** [comment]
Since the only feedback has been positive, I will PR this.

**Comment by setiah** [comment]
Closing the issue since the work is done. Thanks everyone for contributing to this.
