### ISSUE TITLE
The announcements on top of the page are not clickable

### ISSUE THREAD

**Issue by dblock** [opensearch-project/project-website#91]
I really, really want to click this beta 1 available banner and get to the downloads page.

<img width="492" alt="Screen Shot 2021-05-26 at 10 03 09 AM" src="https://user-images.githubusercontent.com/542335/119673759-9e045800-be09-11eb-912f-f994200647a8.png">

**Comment by kgcreative** [comment]
+1

**Comment by stockholmux** [comment]
Fixed in #100
