### ISSUE TITLE
[Blog] What's new with Snapshot Management

### ISSUE THREAD

**Issue by setiah** [opensearch-project/project-website#913]
**Describe the blog post your would like to write**
Blog about the new Snapshot management feature in OpenSearch 2.1 and how to use the feature to automate snapshots of your data in OpenSearch cluster.

**What is the title of the blog post?**
tbd

**Who are the authors?**
tbd

**What is the proposed posting date?**
tbd

**Comment by pajuric** [comment]
@setiah - Please provide an update or close this if this is not moving forward
