### ISSUE TITLE
[BUG] Remove reference to ODFE artifacts from opensearch.org website

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/project-website#938]
**Describe the bug**
ODFE artifacts has reached EOL as per the blog on https://opendistro.github.io/for-elasticsearch/ but I still some references to ODFE artifacts on opensearch.org website

**To Reproduce**
Example: https://opensearch.org/faq#q2.3 

**Expected behavior**
Remove references to ODFE artifacts on opensearch.org website

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Version: [e.g. 22]
 - Browsers: [e.g. Chrome, Safari]
 - Browser Version: [e.g 93.0.4521.12]

**Additional context**

**Comment by krisfreedain** [comment]
thanks @bbarani - will work on it this week

**Comment by krisfreedain** [comment]
@bbarani @CEHENKLE @elfisher @pajuric @jhmcintyre 
There are a few areas of the FAQ that need updating, and I could use your input. 

* https://opensearch.org/faq/#q1.1

*1.1* What is OpenSearch? 

OpenSearch is a fully open source search and analytics suite. OpenSearch includes OpenSearch (derived from Elasticsearch 7.10.2) and OpenSearch Dashboards (derived from Kibana 7.10.2). OpenSearch is the new home for the plugins and advanced features distributed with Open Distro for Elasticsearch. Open Distro for Elasticsearch will end with version 1.13

_*Proposed*_:
OpenSearch is a fully open source search and analytics suite. OpenSearch includes OpenSearch (derived from Elasticsearch 7.10.2) and OpenSearch Dashboards (derived from Kibana 7.10.2). OpenSearch is the new home for the plugins and advanced features distributed with Open Distro for Elasticsearch. Open Distro for Elasticsearch ended with version 1.13 and is [now archived](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/) (https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/).


* https://opensearch.org/faq/#q2.3

*2.3* Will older versions of Open Distro for Elasticsearch plugins still be available for open source Elasticsearch? 

Yes, all older Open Distro for Elasticsearch versions of plugins, from 0.7 to 1.13 will continue to remain available for download.

_*Proposed*_:
No. [Open Distro has been archived](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/) (https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/). 
*do we want to include the option to email “[opensearch@amazon.com](mailto:opensearch@amazon.com)” if they require the plugins? 


* https://opensearch.org/faq/#q3.3

*3.3* Which versions of Elasticsearch OSS and Kibana OSS can I upgrade from to OpenSearch and OpenSearch Dashboards, directly? 

You can directly upgrade to OpenSearch 1.0 from Elasticsearch OSS and Kibana OSS 6.8.0-7.10.2, and Open Distro for Elasticsearch (ODFE) 1.x. For rolling upgrades from ODFE to OpenSearch, we recommend first upgrading to ODFE 1.13, then upgrading to OpenSearch 1.0.

_*Proposed*_:
? (include link to https://opensearch.org/docs/latest/upgrade-to/upgrade-to/) 
*need the group’s input on this at a technical level - which version(s) can we upgrade to? i.e, can users go directly to the latest version of OpenSearch?

**Comment by elfisher** [comment]
some recommendations

> OpenSearch is a fully open source search and analytics suite. OpenSearch includes OpenSearch (derived from Elasticsearch 7.10.2) and OpenSearch Dashboards (derived from Kibana 7.10.2). OpenSearch is the new home for the plugins and advanced features distributed with Open Distro for Elasticsearch. Open Distro for Elasticsearch ended with version 1.13 and is [now archived](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/) (https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/).

How about something more simple: 

OpenSearch is a fully open source search and analytics suite. OpenSearch includes OpenSearch (derived from Elasticsearch 7.10.2), OpenSearch Dashboards (derived from Kibana 7.10.2), and a range of features like built-in security, anomaly detection, alerting, observability experiences, and more.

> No. [Open Distro has been archived](https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/) (https://opendistro.github.io/for-elasticsearch/blog/2022/08/Open-Distro-is-archived/).
*do we want to include the option to email “[opensearch@amazon.com](mailto:opensearch@amazon.com)” if they require the plugins?

LGTM and I don't think the email is necessary in the FAQ

> You can directly upgrade to OpenSearch 1.0 from Elasticsearch OSS and Kibana OSS 6.8.0-7.10.2, and Open Distro for Elasticsearch (ODFE) 1.x. For rolling upgrades from ODFE to OpenSearch, we recommend first upgrading to ODFE 1.13, then upgrading to OpenSearch 1.0.

Let's give a simple answer and link to documentation for more details: 

You can directly upgrade to OpenSearch 1.x from Elasticsearch OSS and Kibana OSS 6.8.0-7.10.2, and Open Distro 1.x. For more information about upgrades, please see [the documentation](https://opensearch.org/docs/latest/upgrade-to/upgrade-to/)

**Comment by krisfreedain** [comment]
Perfect. thank you for the input @elfisher

**Comment by krisfreedain** [comment]
closed in https://github.com/opensearch-project/project-website/pull/941
