### ISSUE TITLE
[FEATURE] Add OpenSearch Slack chat link to the website

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/project-website#939]
**Is your feature request related to a problem? Please describe.**
ODFE project has a Slack chat. It is still alive, but not referenced on OpenSearch. Sometimes chat is more convenient than a forum.

**Describe the solution you'd like**
- [ ] Add Slack link to the website
- [ ] Rename Slack server ODFE -> OpenSearch
- [ ] Invite developers, maintainers and contributors to discuss ongoing tasks there
- [ ] Voice call Slack feature could simplify interaction between developers

[odfe-workspace.slack.com](https://odfe-workspace.slack.com)

**Comment by krisfreedain** [comment]
Hello @Yury-Fridlyand - we appreciate the idea. There is talk going on to add a public Slack for the OpenSearch community but that's all the details I have for now.

**Comment by Yury-Fridlyand** [comment]
Woohoo, it is launched!
Ref: #1491, #1493.
