### ISSUE TITLE
Client Ingestion Survey Results

### ISSUE THREAD

**Issue by brijos** [opensearch-project/project-website#961]
**Describe the blog post your would like to write**
In July 2022, we conducted a survey asking what ingestion agents are used within the community's ingestion pipeline. The post is to provide the results of that survey.

**What is the title of the blog post?**
Agent Ingestion Usage in OpenSearch Survey Results

**Who are the authors?**
jdbright

**What is the proposed posting date?**
8/23/2022

**Comment by krisfreedain** [comment]
Blog is out! https://opensearch.org/blog/technical-post/2022/08/Agent-Ingestion-Usage-In-OpenSearch-Survey-Results/
