### ISSUE TITLE
Add new blog on how to add new distribution for OpenSearch/Dashboards

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/project-website#968]
Add new blog on how to add new distribution for OpenSearch/Dashboards.

Using experience in RPM/Windows to inform and encourage the community to contribute more distribution to the project.

I will start a blog post later.

**Comment by vagimeli** [comment]
@peterzhuamazon I've completed the technical writer review. Please see my edits and comments and reach out if we need to discuss my edits or recommended changes.

**Comment by peterzhuamazon** [comment]
> @peterzhuamazon I've completed the technical writer review. Please see my edits and comments and reach out if we need to discuss my edits or recommended changes.

Thanks @vagimeli I will take a look and make the changes you suggested.

After that I assume I can raise a PR?
Thanks.

**Comment by vagimeli** [comment]
Yes, you can raise it to a PR. I'll approve my review in the PR too. Thanks!

**Comment by peterzhuamazon** [comment]
Hi @vagimeli @bbarani,

New blog post PR is here:
* https://github.com/opensearch-project/project-website/pull/1093

Please let me know if there is anything needed.

Thanks,
Peter

**Comment by peterzhuamazon** [comment]
This blog is released to the public now:
* https://opensearch.org/blog/community/2022/10/Adding-New-Distributions-to-OpenSearch-Project/

Thanks.
